// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { TranscribeRequest, TranscribeResponse } from "../types/aiservice";
import { Status } from "../types/shared";
import type { ClientConfig, RequestOptions } from "../client";
import { sdkRequest } from "../client";

export type AiServiceTranscribeError = Status;

export type AiServiceTranscribeParams = TranscribeRequest;

/**
 * Transcribes an audio file using the instance's configured AI provider. Supply the required `audio` object with the audio input. The response contains the transcribed text.
 *
 * Transcribe transcribes an audio file using an instance AI provider.
 *
 * @param audio - Required. Audio input.
 */
export async function aiServiceTranscribe(
  config: ClientConfig,
  { audio }: AiServiceTranscribeParams,
  requestOptions?: RequestOptions,
): Promise<TranscribeResponse> {
  const _resp = await sdkRequest<TranscribeResponse>({
    method: "POST",
    path: `/api/v1/ai:transcribe`,
    operationId: "aiServiceTranscribe",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      audio,
    },
    config,
  });
  return _resp.data;
}

export class AiServiceNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Transcribes an audio file using the instance's configured AI provider. Supply the required `audio` object with the audio input. The response contains the transcribed text.
   *
   * Transcribe transcribes an audio file using an instance AI provider.
   */
  transcribe(
    params: AiServiceTranscribeParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof aiServiceTranscribe> {
    return aiServiceTranscribe(this._config, params, requestOptions);
  }
}
