// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import {
  BatchDeleteAttachmentsRequest,
  ListAttachmentsResponse,
  UploadAttachmentRequest,
  UploadAttachmentResponse,
} from "../types/attachment-service";
import { Attachment, Status } from "../types/shared";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, queryValue, sdkRequest } from "../client";
import { validateDateTime } from "../validation";

export type AttachmentServiceListAttachmentsError = Status;

export interface AttachmentServiceListAttachmentsParams {
  pageSize?: number;
  pageToken?: string;
  filter?: string;
  orderBy?: string;
}

/**
 * Lists attachments linked to readable memos and unlinked uploads belonging to the authenticated user. Use `filter` to narrow the results and `orderBy` to sort them; use `pageToken` to retrieve subsequent pages.
 *
 * ListAttachments lists attachments linked to readable memos and the caller's unlinked uploads.
 *
 * @param pageSize - Optional. The maximum number of attachments to return. The
 *   service may return fewer than this value. If unspecified, at most 50
 *   attachments will be returned. The maximum value is 1000; values above 1000
 *   will be coerced to 1000.
 * @param pageToken - Optional. A page token, received from a previous
 *   `ListAttachments` call. Provide this to retrieve the subsequent page.
 * @param filter - Optional. Filter to apply to the list results. Example:
 *   "mime_type==\"image/png\"" or "filename.contains(\"test\")" Supported
 *   operators: =, !=, <, <=, >, >=, : (contains), in Supported fields: creator,
 *   filename, mime_type, create_time, memo_id, space. `creator` is the linked
 *   memo's creator, or the uploader for an unlinked attachment. It supports
 *   equality with a User resource name. `space` only supports a non-negated `==`
 *   comparison with a Space resource name or null. `space` is the linked memo's
 *   space resource name, or null when the attachment is unlinked or its linked
 *   memo has no space.
 * @param orderBy - Optional. The order to sort results by. Example: "create_time
 *   desc" or "filename asc"
 */
export async function attachmentServiceListAttachments(
  config: ClientConfig,
  { pageSize, pageToken, filter, orderBy }: AttachmentServiceListAttachmentsParams = {},
  requestOptions?: RequestOptions,
): Promise<ListAttachmentsResponse> {
  const _resp = await sdkRequest<ListAttachmentsResponse>({
    method: "GET",
    path: `/api/v1/attachments`,
    operationId: "attachmentServiceListAttachments",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      pageSize: queryValue(pageSize, "form", true),
      pageToken: queryValue(pageToken, "form", true),
      filter: queryValue(filter, "form", true),
      orderBy: queryValue(orderBy, "form", true),
    },
    config,
  });
  return _resp.data;
}

export type AttachmentServiceCreateAttachmentError = Status;

export type AttachmentServiceCreateAttachmentParams = Attachment & {
  attachmentId?: string;
};

/**
 * Creates a new attachment. Supply the required `filename` and `type`, and optionally associate the attachment with a memo using `memo`. Set `attachmentId` to choose an ID, or omit it to have one generated.
 *
 * CreateAttachment creates a new attachment.
 *
 * @param filename - The filename of the attachment.
 * @param type_ - The MIME type of the attachment.
 * @param attachmentId - Optional. The attachment ID to use for this attachment.
 *   If empty, a unique ID will be generated. Format:
 *   ^[a-zA-Z0-9]([a-zA-Z0-9-]{0,34}[a-zA-Z0-9])?$
 * @param name - The name of the attachment. Format: attachments/{attachment}
 * @param createTime - Output only. The creation timestamp.
 * @param content - Input only. The content of the attachment.
 * @param externalLink - Optional. The external link of the attachment.
 * @param size - Output only. The size of the attachment in bytes.
 * @param memo - Optional. The related memo. Refer to `Memo.name`. Format:
 *   memos/{memo}
 * @param motionMedia - Optional. Motion media metadata.
 * @param mediaMetadata - Optional. Immutable normalized media metadata
 *   explicitly supplied by the client at creation time.
 * @param creator - Output only. The user who uploaded this attachment, which may
 *   differ from the creator of the linked memo. Format: users/{user}.
 */
export async function attachmentServiceCreateAttachment(
  config: ClientConfig,
  {
    filename,
    type: type_,
    attachmentId,
    name,
    createTime,
    content,
    externalLink,
    size,
    memo,
    motionMedia,
    mediaMetadata,
    creator,
  }: AttachmentServiceCreateAttachmentParams,
  requestOptions?: RequestOptions,
): Promise<Attachment> {
  if (createTime != null) {
    validateDateTime("createTime", createTime);
  }

  const _resp = await sdkRequest<Attachment>({
    method: "POST",
    path: `/api/v1/attachments`,
    operationId: "attachmentServiceCreateAttachment",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      attachmentId: queryValue(attachmentId, "form", true),
    },
    body: {
      filename,
      ["type"]: type_,
      name,
      createTime,
      content,
      externalLink,
      size,
      memo,
      motionMedia,
      mediaMetadata,
      creator,
    },
    config,
  });
  return _resp.data;
}

export type AttachmentServiceGetAttachmentError = Status;

export interface AttachmentServiceGetAttachmentParams {
  attachment: string;
}

/**
 * Retrieves an attachment by its identifier. Use the `attachment` path value to select the attachment you want to retrieve.
 *
 * GetAttachment returns an attachment by name.
 *
 * @param attachment - The attachment id.
 */
export async function attachmentServiceGetAttachment(
  config: ClientConfig,
  { attachment }: AttachmentServiceGetAttachmentParams,
  requestOptions?: RequestOptions,
): Promise<Attachment> {
  const _resp = await sdkRequest<Attachment>({
    method: "GET",
    path: `/api/v1/attachments/${encodePathSegment(attachment)}`,
    operationId: "attachmentServiceGetAttachment",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type AttachmentServiceDeleteAttachmentError = Status;

export interface AttachmentServiceDeleteAttachmentParams {
  attachment: string;
}

/**
 * Deletes an attachment by its identifier. Use the `attachment` path value to select the attachment to remove.
 *
 * DeleteAttachment deletes an attachment by name.
 *
 * @param attachment - The attachment id.
 */
export async function attachmentServiceDeleteAttachment(
  config: ClientConfig,
  { attachment }: AttachmentServiceDeleteAttachmentParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "DELETE",
    path: `/api/v1/attachments/${encodePathSegment(attachment)}`,
    operationId: "attachmentServiceDeleteAttachment",
    responseDecoder: "empty",
    ...requestOptions,
    config,
  });
  void _resp.data;
  return;
}

export type AttachmentServiceUpdateAttachmentError = Status;

export type AttachmentServiceUpdateAttachmentParams = Attachment & {
  attachment: string;
  updateMask?: string;
};

/**
 * Updates an attachment identified by its resource name. Supply the attachment fields and use `updateMask` to specify which fields to update. The request body schema requires `filename` and `type`.
 *
 * UpdateAttachment updates an attachment.
 *
 * @param attachment - The attachment id.
 * @param filename - The filename of the attachment.
 * @param type_ - The MIME type of the attachment.
 * @param updateMask - Required. The list of fields to update.
 * @param name - The name of the attachment. Format: attachments/{attachment}
 * @param createTime - Output only. The creation timestamp.
 * @param content - Input only. The content of the attachment.
 * @param externalLink - Optional. The external link of the attachment.
 * @param size - Output only. The size of the attachment in bytes.
 * @param memo - Optional. The related memo. Refer to `Memo.name`. Format:
 *   memos/{memo}
 * @param motionMedia - Optional. Motion media metadata.
 * @param mediaMetadata - Optional. Immutable normalized media metadata
 *   explicitly supplied by the client at creation time.
 * @param creator - Output only. The user who uploaded this attachment, which may
 *   differ from the creator of the linked memo. Format: users/{user}.
 */
export async function attachmentServiceUpdateAttachment(
  config: ClientConfig,
  {
    attachment,
    filename,
    type: type_,
    updateMask,
    name,
    createTime,
    content,
    externalLink,
    size,
    memo,
    motionMedia,
    mediaMetadata,
    creator,
  }: AttachmentServiceUpdateAttachmentParams,
  requestOptions?: RequestOptions,
): Promise<Attachment> {
  if (createTime != null) {
    validateDateTime("createTime", createTime);
  }

  const _resp = await sdkRequest<Attachment>({
    method: "PATCH",
    path: `/api/v1/attachments/${encodePathSegment(attachment)}`,
    operationId: "attachmentServiceUpdateAttachment",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      updateMask: queryValue(updateMask, "form", true),
    },
    body: {
      filename,
      ["type"]: type_,
      name,
      createTime,
      content,
      externalLink,
      size,
      memo,
      motionMedia,
      mediaMetadata,
      creator,
    },
    config,
  });
  return _resp.data;
}

export type AttachmentServiceBatchDeleteAttachmentsError = Status;

export type AttachmentServiceBatchDeleteAttachmentsParams = BatchDeleteAttachmentsRequest;

/**
 * Deletes multiple attachments in one request. Provide their resource names in the required `names` array. The operation removes each attachment identified in that array.
 *
 * BatchDeleteAttachments deletes multiple attachments in one request.
 *
 * @param names - Required array value serialized in the `names` wire field.
 */
export async function attachmentServiceBatchDeleteAttachments(
  config: ClientConfig,
  { names }: AttachmentServiceBatchDeleteAttachmentsParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "POST",
    path: `/api/v1/attachments:batchDelete`,
    operationId: "attachmentServiceBatchDeleteAttachments",
    responseDecoder: "empty",
    ...requestOptions,
    body: {
      names,
    },
    config,
  });
  void _resp.data;
  return;
}

export type AttachmentServiceUploadAttachmentError = Status;

export type AttachmentServiceUploadAttachmentParams = UploadAttachmentRequest;

/**
 * Uploads a file in chunks to create an attachment. Start an upload with `spec`, then use the returned `uploadId` to continue; each write must use the current committed byte offset. Uploads are bound to the authenticated user, expire after 30 minutes of inactivity, and do not survive a server restart.
 *
 * UploadAttachment uploads a file in bounded chunks. The first call carries the spec and returns an upload_id; later calls carry that upload_id. Uploads are bound to the authenticated user, expire after 30 minutes of inactivity, and do not survive a server restart.
 *
 * @param writeOffset - Required. Zero-based byte offset at which data is
 *   written. Must equal the committed size, except when retrying the most recently
 *   accepted chunk with identical bytes and offset, which is accepted without
 *   writing again.
 * @param spec - Starts a new upload. The same call may also carry data and
 *   finish_write.
 * @param uploadId - Continues the upload identified by a previous response.
 * @param data - Optional. File bytes, at most max_chunk_size long. With no data
 *   and finish_write false, the call reports progress without writing, and
 *   write_offset is ignored.
 * @param finishWrite - Optional. Finalize the upload after writing data. The
 *   committed size must then equal total_size. Any later call for the same
 *   upload_id returns the created attachment.
 */
export async function attachmentServiceUploadAttachment(
  config: ClientConfig,
  { writeOffset, spec, uploadId, data, finishWrite }: AttachmentServiceUploadAttachmentParams,
  requestOptions?: RequestOptions,
): Promise<UploadAttachmentResponse> {
  const _resp = await sdkRequest<UploadAttachmentResponse>({
    method: "POST",
    path: `/api/v1/attachments:upload`,
    operationId: "attachmentServiceUploadAttachment",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      writeOffset,
      spec,
      uploadId,
      data,
      finishWrite,
    },
    config,
  });
  return _resp.data;
}

export class AttachmentServiceNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Lists attachments linked to readable memos and unlinked uploads belonging to the authenticated user. Use `filter` to narrow the results and `orderBy` to sort them; use `pageToken` to retrieve subsequent pages.
   *
   * ListAttachments lists attachments linked to readable memos and the caller's unlinked uploads.
   */
  listAttachments(
    params: AttachmentServiceListAttachmentsParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof attachmentServiceListAttachments> {
    return attachmentServiceListAttachments(this._config, params, requestOptions);
  }
  /**
   * Creates a new attachment. Supply the required `filename` and `type`, and optionally associate the attachment with a memo using `memo`. Set `attachmentId` to choose an ID, or omit it to have one generated.
   *
   * CreateAttachment creates a new attachment.
   */
  createAttachment(
    params: AttachmentServiceCreateAttachmentParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof attachmentServiceCreateAttachment> {
    return attachmentServiceCreateAttachment(this._config, params, requestOptions);
  }
  /**
   * Retrieves an attachment by its identifier. Use the `attachment` path value to select the attachment you want to retrieve.
   *
   * GetAttachment returns an attachment by name.
   */
  getAttachment(
    params: AttachmentServiceGetAttachmentParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof attachmentServiceGetAttachment> {
    return attachmentServiceGetAttachment(this._config, params, requestOptions);
  }
  /**
   * Deletes an attachment by its identifier. Use the `attachment` path value to select the attachment to remove.
   *
   * DeleteAttachment deletes an attachment by name.
   */
  deleteAttachment(
    params: AttachmentServiceDeleteAttachmentParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof attachmentServiceDeleteAttachment> {
    return attachmentServiceDeleteAttachment(this._config, params, requestOptions);
  }
  /**
   * Updates an attachment identified by its resource name. Supply the attachment fields and use `updateMask` to specify which fields to update. The request body schema requires `filename` and `type`.
   *
   * UpdateAttachment updates an attachment.
   */
  updateAttachment(
    params: AttachmentServiceUpdateAttachmentParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof attachmentServiceUpdateAttachment> {
    return attachmentServiceUpdateAttachment(this._config, params, requestOptions);
  }
  /**
   * Deletes multiple attachments in one request. Provide their resource names in the required `names` array. The operation removes each attachment identified in that array.
   *
   * BatchDeleteAttachments deletes multiple attachments in one request.
   */
  batchDeleteAttachments(
    params: AttachmentServiceBatchDeleteAttachmentsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof attachmentServiceBatchDeleteAttachments> {
    return attachmentServiceBatchDeleteAttachments(this._config, params, requestOptions);
  }
  /**
   * Uploads a file in chunks to create an attachment. Start an upload with `spec`, then use the returned `uploadId` to continue; each write must use the current committed byte offset. Uploads are bound to the authenticated user, expire after 30 minutes of inactivity, and do not survive a server restart.
   *
   * UploadAttachment uploads a file in bounded chunks. The first call carries the spec and returns an upload_id; later calls carry that upload_id. Uploads are bound to the authenticated user, expire after 30 minutes of inactivity, and do not survive a server restart.
   */
  uploadAttachment(
    params: AttachmentServiceUploadAttachmentParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof attachmentServiceUploadAttachment> {
    return attachmentServiceUploadAttachment(this._config, params, requestOptions);
  }
}
