// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import {
  GetCurrentUserResponse,
  RefreshTokenRequest,
  RefreshTokenResponse,
  SignInRequest,
  SignInResponse,
} from "../types/auth-service";
import { Status } from "../types/shared";
import type { ClientConfig, RequestOptions } from "../client";
import { sdkRequest } from "../client";

export type AuthServiceGetCurrentUserError = Status;

/**
 * Retrieves information about the authenticated user by validating the access token. Use this endpoint to obtain the user's details, similar to an OIDC userinfo request.
 *
 * GetCurrentUser returns the authenticated user's information. Validates the access token and returns user details. Similar to OIDC's /userinfo endpoint.
 */
export async function authServiceGetCurrentUser(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<GetCurrentUserResponse> {
  const _resp = await sdkRequest<GetCurrentUserResponse>({
    method: "GET",
    path: `/api/v1/auth/me`,
    operationId: "authServiceGetCurrentUser",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type AuthServiceRefreshTokenError = Status;

export type AuthServiceRefreshTokenParams = RefreshTokenRequest;

/**
 * Exchanges the refresh token in the HttpOnly cookie for a new short-lived access token. Send the request with the refresh token cookie; the response includes the token's expiration time.
 *
 * RefreshToken exchanges a valid refresh token for a new access token. The refresh token is read from the HttpOnly cookie. Returns a new short-lived access token.
 */
export async function authServiceRefreshToken(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<RefreshTokenResponse> {
  const _resp = await sdkRequest<RefreshTokenResponse>({
    method: "POST",
    path: `/api/v1/auth/refresh`,
    operationId: "authServiceRefreshToken",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type AuthServiceSignInError = Status;

export type AuthServiceSignInParams = SignInRequest;

/**
 * Authenticates a user with password credentials or an SSO provider. Supply the relevant credential object; password sign-in requires `username` and `password`, while SSO sign-in requires `idpName`, `code`, and `redirectUri`. The response includes an access token and sets a refresh-token cookie.
 *
 * SignIn authenticates a user with credentials and returns tokens. On success, returns an access token and sets a refresh token cookie. Supports password-based and SSO authentication methods.
 *
 * @param passwordCredentials - Username and password authentication.
 * @param ssoCredentials - SSO provider authentication.
 */
export async function authServiceSignIn(
  config: ClientConfig,
  { passwordCredentials, ssoCredentials }: AuthServiceSignInParams = {},
  requestOptions?: RequestOptions,
): Promise<SignInResponse> {
  const _resp = await sdkRequest<SignInResponse>({
    method: "POST",
    path: `/api/v1/auth/signin`,
    operationId: "authServiceSignIn",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      passwordCredentials,
      ssoCredentials,
    },
    config,
  });
  return _resp.data;
}

export type AuthServiceSignOutError = Status;

/**
 * Terminates the authenticated user's session by revoking the refresh token and clearing the authentication cookie. Call this operation when the user signs out so the refresh token can no longer be used to obtain access tokens.
 *
 * SignOut terminates the user's authentication. Revokes the refresh token and clears the authentication cookie.
 */
export async function authServiceSignOut(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "POST",
    path: `/api/v1/auth/signout`,
    operationId: "authServiceSignOut",
    responseDecoder: "empty",
    ...requestOptions,
    config,
  });
  void _resp.data;
  return;
}

export class AuthServiceNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Retrieves information about the authenticated user by validating the access token. Use this endpoint to obtain the user's details, similar to an OIDC userinfo request.
   *
   * GetCurrentUser returns the authenticated user's information. Validates the access token and returns user details. Similar to OIDC's /userinfo endpoint.
   */
  getCurrentUser(requestOptions?: RequestOptions): ReturnType<typeof authServiceGetCurrentUser> {
    return authServiceGetCurrentUser(this._config, requestOptions);
  }
  /**
   * Exchanges the refresh token in the HttpOnly cookie for a new short-lived access token. Send the request with the refresh token cookie; the response includes the token's expiration time.
   *
   * RefreshToken exchanges a valid refresh token for a new access token. The refresh token is read from the HttpOnly cookie. Returns a new short-lived access token.
   */
  refreshToken(requestOptions?: RequestOptions): ReturnType<typeof authServiceRefreshToken> {
    return authServiceRefreshToken(this._config, requestOptions);
  }
  /**
   * Authenticates a user with password credentials or an SSO provider. Supply the relevant credential object; password sign-in requires `username` and `password`, while SSO sign-in requires `idpName`, `code`, and `redirectUri`. The response includes an access token and sets a refresh-token cookie.
   *
   * SignIn authenticates a user with credentials and returns tokens. On success, returns an access token and sets a refresh token cookie. Supports password-based and SSO authentication methods.
   */
  signIn(
    params: AuthServiceSignInParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof authServiceSignIn> {
    return authServiceSignIn(this._config, params, requestOptions);
  }
  /**
   * Terminates the authenticated user's session by revoking the refresh token and clearing the authentication cookie. Call this operation when the user signs out so the refresh token can no longer be used to obtain access tokens.
   *
   * SignOut terminates the user's authentication. Revokes the refresh token and clears the authentication cookie.
   */
  signOut(requestOptions?: RequestOptions): ReturnType<typeof authServiceSignOut> {
    return authServiceSignOut(this._config, requestOptions);
  }
}
