// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import {
  IdentityProvider,
  ListIdentityProvidersResponse,
} from "../types/identity-provider-service";
import { Status } from "../types/shared";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, queryValue, sdkRequest } from "../client";

export type IdentityProviderServiceListIdentityProvidersError = Status;

/**
 * Lists the identity providers configured for the instance. Use this operation to retrieve provider types, display titles, identifier filters, and configuration details before choosing or managing an identity provider.
 *
 * ListIdentityProviders lists identity providers.
 */
export async function identityProviderServiceListIdentityProviders(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<ListIdentityProvidersResponse> {
  const _resp = await sdkRequest<ListIdentityProvidersResponse>({
    method: "GET",
    path: `/api/v1/identity-providers`,
    operationId: "identityProviderServiceListIdentityProviders",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type IdentityProviderServiceCreateIdentityProviderError = Status;

export type IdentityProviderServiceCreateIdentityProviderParams = IdentityProvider & {
  identityProviderId?: string;
};

/**
 * Creates an identity provider for the instance. Supply `type`, `title`, and `config`; use `identityProviderId` to choose the resource ID, or omit it to have one generated. The provider type must be `TYPE_UNSPECIFIED` or `OAUTH2`.
 *
 * CreateIdentityProvider creates an identity provider.
 *
 * @param type_ - Required. The type of the identity provider.
 * @param title - Required. The display title of the identity provider.
 * @param config_ - Required. Configuration for the identity provider.
 * @param identityProviderId - Optional. The ID to use for the identity provider,
 *   which will become the final component of the resource name. If not provided,
 *   the system will generate one. Format:
 *   ^[a-zA-Z0-9]([a-zA-Z0-9-]{0,34}[a-zA-Z0-9])?$
 * @param name - The resource name of the identity provider. Format:
 *   identity-providers/{idp}
 * @param identifierFilter - Optional. Filter applied to user identifiers.
 */
export async function identityProviderServiceCreateIdentityProvider(
  config: ClientConfig,
  {
    type: type_,
    title,
    config: config_,
    identityProviderId,
    name,
    identifierFilter,
  }: IdentityProviderServiceCreateIdentityProviderParams,
  requestOptions?: RequestOptions,
): Promise<IdentityProvider> {
  const _resp = await sdkRequest<IdentityProvider>({
    method: "POST",
    path: `/api/v1/identity-providers`,
    operationId: "identityProviderServiceCreateIdentityProvider",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      identityProviderId: queryValue(identityProviderId, "form", true),
    },
    body: {
      ["type"]: type_,
      title,
      ["config"]: config_,
      name,
      identifierFilter,
    },
    config,
  });
  return _resp.data;
}

export type IdentityProviderServiceGetIdentityProviderError = Status;

export interface IdentityProviderServiceGetIdentityProviderParams {
  identityProvider: string;
}

/**
 * Retrieves a configured identity provider by its ID. Use the identity provider's identifier to get its resource name, type, display title, identifier filter, and configuration.
 *
 * GetIdentityProvider gets an identity provider.
 *
 * @param identityProvider - The identity-provider id.
 */
export async function identityProviderServiceGetIdentityProvider(
  config: ClientConfig,
  { identityProvider }: IdentityProviderServiceGetIdentityProviderParams,
  requestOptions?: RequestOptions,
): Promise<IdentityProvider> {
  const _resp = await sdkRequest<IdentityProvider>({
    method: "GET",
    path: `/api/v1/identity-providers/${encodePathSegment(identityProvider)}`,
    operationId: "identityProviderServiceGetIdentityProvider",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type IdentityProviderServiceDeleteIdentityProviderError = Status;

export interface IdentityProviderServiceDeleteIdentityProviderParams {
  identityProvider: string;
}

/**
 * Deletes an identity provider from the instance. Supply the identity provider's ID to select the resource to remove. Use this operation when the provider should no longer be available for authentication.
 *
 * DeleteIdentityProvider deletes an identity provider.
 *
 * @param identityProvider - The identity-provider id.
 */
export async function identityProviderServiceDeleteIdentityProvider(
  config: ClientConfig,
  { identityProvider }: IdentityProviderServiceDeleteIdentityProviderParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "DELETE",
    path: `/api/v1/identity-providers/${encodePathSegment(identityProvider)}`,
    operationId: "identityProviderServiceDeleteIdentityProvider",
    responseDecoder: "empty",
    ...requestOptions,
    config,
  });
  void _resp.data;
  return;
}

export type IdentityProviderServiceUpdateIdentityProviderError = Status;

export type IdentityProviderServiceUpdateIdentityProviderParams = IdentityProvider & {
  identityProvider: string;
  updateMask?: string;
};

/**
 * Updates an identity provider using the supplied resource fields and update mask. Include `type`, `title`, and `config` in the request body, and use `updateMask` to select the top-level fields to update. Only top-level fields of the identity provider are supported by the mask.
 *
 * UpdateIdentityProvider updates an identity provider.
 *
 * @param identityProvider - The identity-provider id.
 * @param type_ - Required. The type of the identity provider.
 * @param title - Required. The display title of the identity provider.
 * @param config_ - Required. Configuration for the identity provider.
 * @param updateMask - Required. The update mask applies to the resource. Only
 *   the top level fields of IdentityProvider are supported.
 * @param name - The resource name of the identity provider. Format:
 *   identity-providers/{idp}
 * @param identifierFilter - Optional. Filter applied to user identifiers.
 */
export async function identityProviderServiceUpdateIdentityProvider(
  config: ClientConfig,
  {
    identityProvider,
    type: type_,
    title,
    config: config_,
    updateMask,
    name,
    identifierFilter,
  }: IdentityProviderServiceUpdateIdentityProviderParams,
  requestOptions?: RequestOptions,
): Promise<IdentityProvider> {
  const _resp = await sdkRequest<IdentityProvider>({
    method: "PATCH",
    path: `/api/v1/identity-providers/${encodePathSegment(identityProvider)}`,
    operationId: "identityProviderServiceUpdateIdentityProvider",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      updateMask: queryValue(updateMask, "form", true),
    },
    body: {
      ["type"]: type_,
      title,
      ["config"]: config_,
      name,
      identifierFilter,
    },
    config,
  });
  return _resp.data;
}

export class IdentityProviderServiceNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Lists the identity providers configured for the instance. Use this operation to retrieve provider types, display titles, identifier filters, and configuration details before choosing or managing an identity provider.
   *
   * ListIdentityProviders lists identity providers.
   */
  listIdentityProviders(
    requestOptions?: RequestOptions,
  ): ReturnType<typeof identityProviderServiceListIdentityProviders> {
    return identityProviderServiceListIdentityProviders(this._config, requestOptions);
  }
  /**
   * Creates an identity provider for the instance. Supply `type`, `title`, and `config`; use `identityProviderId` to choose the resource ID, or omit it to have one generated. The provider type must be `TYPE_UNSPECIFIED` or `OAUTH2`.
   *
   * CreateIdentityProvider creates an identity provider.
   */
  createIdentityProvider(
    params: IdentityProviderServiceCreateIdentityProviderParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof identityProviderServiceCreateIdentityProvider> {
    return identityProviderServiceCreateIdentityProvider(this._config, params, requestOptions);
  }
  /**
   * Retrieves a configured identity provider by its ID. Use the identity provider's identifier to get its resource name, type, display title, identifier filter, and configuration.
   *
   * GetIdentityProvider gets an identity provider.
   */
  getIdentityProvider(
    params: IdentityProviderServiceGetIdentityProviderParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof identityProviderServiceGetIdentityProvider> {
    return identityProviderServiceGetIdentityProvider(this._config, params, requestOptions);
  }
  /**
   * Deletes an identity provider from the instance. Supply the identity provider's ID to select the resource to remove. Use this operation when the provider should no longer be available for authentication.
   *
   * DeleteIdentityProvider deletes an identity provider.
   */
  deleteIdentityProvider(
    params: IdentityProviderServiceDeleteIdentityProviderParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof identityProviderServiceDeleteIdentityProvider> {
    return identityProviderServiceDeleteIdentityProvider(this._config, params, requestOptions);
  }
  /**
   * Updates an identity provider using the supplied resource fields and update mask. Include `type`, `title`, and `config` in the request body, and use `updateMask` to select the top-level fields to update. Only top-level fields of the identity provider are supported by the mask.
   *
   * UpdateIdentityProvider updates an identity provider.
   */
  updateIdentityProvider(
    params: IdentityProviderServiceUpdateIdentityProviderParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof identityProviderServiceUpdateIdentityProvider> {
    return identityProviderServiceUpdateIdentityProvider(this._config, params, requestOptions);
  }
}
