// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import {
  BatchGetInstanceSettingsRequest,
  BatchGetInstanceSettingsResponse,
  InstanceProfile,
  InstanceSetting,
  InstanceStats,
  TestInstanceEmailSettingRequest,
} from "../types/instance-service";
import { Status } from "../types/shared";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, queryValue, sdkRequest } from "../client";

export type InstanceServiceGetInstanceProfileError = Status;

/**
 * Retrieves the instance profile and its basic deployment information. Use the profile to inspect the instance version, access mode, setup state, and any configured proof-of-humanity challenge.
 *
 * Gets the instance profile.
 */
export async function instanceServiceGetInstanceProfile(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<InstanceProfile> {
  const _resp = await sdkRequest<InstanceProfile>({
    method: "GET",
    path: `/api/v1/instance/profile`,
    operationId: "instanceServiceGetInstanceProfile",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type InstanceServiceTestInstanceEmailSettingError = Status;

export type InstanceServiceTestInstanceEmailSettingParams = TestInstanceEmailSettingRequest;

/**
 * Tests notification email delivery using the supplied SMTP settings or the settings already stored for the instance. Set `recipientEmail` to choose a recipient; when omitted, the authenticated user's email address is used.
 *
 * Tests notification email delivery with the provided or stored SMTP settings.
 *
 * @param email - Optional. SMTP email settings to test. If omitted, the stored
 *   notification email setting is used.
 * @param recipientEmail - Optional. Recipient email address. If omitted, the
 *   current user's email address is used.
 */
export async function instanceServiceTestInstanceEmailSetting(
  config: ClientConfig,
  { email, recipientEmail }: InstanceServiceTestInstanceEmailSettingParams = {},
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "POST",
    path: `/api/v1/instance/settings/notification:testEmail`,
    operationId: "instanceServiceTestInstanceEmailSetting",
    responseDecoder: "empty",
    ...requestOptions,
    body: {
      email,
      recipientEmail,
    },
    config,
  });
  void _resp.data;
  return;
}

export type InstanceServiceBatchGetInstanceSettingsError = Status;

export type InstanceServiceBatchGetInstanceSettingsParams = BatchGetInstanceSettingsRequest;

/**
 * Retrieves multiple instance settings in a single request. Provide the resource names in `names`; the response returns the matching settings in the same order as the requested names.
 *
 * Batch gets instance settings.
 *
 * @param names - The resource names of the instance settings. Format:
 *   instance/settings/{setting}
 */
export async function instanceServiceBatchGetInstanceSettings(
  config: ClientConfig,
  { names }: InstanceServiceBatchGetInstanceSettingsParams,
  requestOptions?: RequestOptions,
): Promise<BatchGetInstanceSettingsResponse> {
  const _resp = await sdkRequest<BatchGetInstanceSettingsResponse>({
    method: "POST",
    path: `/api/v1/instance/settings:batchGet`,
    operationId: "instanceServiceBatchGetInstanceSettings",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      names,
    },
    config,
  });
  return _resp.data;
}

export type InstanceServiceGetInstanceStatsError = Status;

/**
 * Retrieves resource usage statistics for the instance. Access is restricted to administrators, so use an account with the `admin` role.
 *
 * GetInstanceStats returns resource usage statistics for the instance. Admin only.
 */
export async function instanceServiceGetInstanceStats(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<InstanceStats> {
  const _resp = await sdkRequest<InstanceStats>({
    method: "GET",
    path: `/api/v1/instance/stats`,
    operationId: "instanceServiceGetInstanceStats",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type InstanceServiceGetInstanceSettingError = Status;

export interface InstanceServiceGetInstanceSettingParams {
  instance: string;
}

/**
 * Retrieves a setting for the specified instance. Use the `instance` identifier to select the instance and request the setting by its resource name, formatted as `instance/settings/{setting}`.
 *
 * Gets an instance setting.
 *
 * @param instance - The instance id.
 */
export async function instanceServiceGetInstanceSetting(
  config: ClientConfig,
  { instance }: InstanceServiceGetInstanceSettingParams,
  requestOptions?: RequestOptions,
): Promise<InstanceSetting> {
  const _resp = await sdkRequest<InstanceSetting>({
    method: "GET",
    path: `/api/v1/instance/${encodePathSegment(instance)}/*`,
    operationId: "instanceServiceGetInstanceSetting",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type InstanceServiceUpdateInstanceSettingError = Status;

export type InstanceServiceUpdateInstanceSettingParams = InstanceSetting & {
  instance: string;
  updateMask?: string;
};

/**
 * Updates configuration for an instance setting. Supply the setting resource in the request body and use `updateMask` to specify which fields to update; `storageType` and `accessMode` accept only their documented enum values.
 *
 * Updates an instance setting.
 *
 * @param instance - The instance id.
 * @param updateMask - The list of fields to update.
 * @param name - The name of the instance setting. Format:
 *   instance/settings/{setting}
 * @param generalSetting - General instance settings configuration.
 * @param storageSetting - Storage configuration settings for instance
 *   attachments.
 * @param memoRelatedSetting - Memo-related instance settings and policies.
 * @param tagsSetting - Tag metadata configuration. Active tag metadata is stored
 *   in per-user tag settings. This message remains for backward compatibility with
 *   existing clients and migrations.
 * @param notificationSetting - Notification transport configuration.
 * @param aiSetting - AI provider configuration settings.
 * @param accessSetting - Access policy configuration for the instance.
 */
export async function instanceServiceUpdateInstanceSetting(
  config: ClientConfig,
  {
    instance,
    updateMask,
    name,
    generalSetting,
    storageSetting,
    memoRelatedSetting,
    tagsSetting,
    notificationSetting,
    aiSetting,
    accessSetting,
  }: InstanceServiceUpdateInstanceSettingParams,
  requestOptions?: RequestOptions,
): Promise<InstanceSetting> {
  const _resp = await sdkRequest<InstanceSetting>({
    method: "PATCH",
    path: `/api/v1/instance/${encodePathSegment(instance)}/*`,
    operationId: "instanceServiceUpdateInstanceSetting",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      updateMask: queryValue(updateMask, "form", true),
    },
    body: {
      name,
      generalSetting,
      storageSetting,
      memoRelatedSetting,
      tagsSetting,
      notificationSetting,
      aiSetting,
      accessSetting,
    },
    config,
  });
  return _resp.data;
}

export class InstanceServiceNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Retrieves the instance profile and its basic deployment information. Use the profile to inspect the instance version, access mode, setup state, and any configured proof-of-humanity challenge.
   *
   * Gets the instance profile.
   */
  getInstanceProfile(
    requestOptions?: RequestOptions,
  ): ReturnType<typeof instanceServiceGetInstanceProfile> {
    return instanceServiceGetInstanceProfile(this._config, requestOptions);
  }
  /**
   * Tests notification email delivery using the supplied SMTP settings or the settings already stored for the instance. Set `recipientEmail` to choose a recipient; when omitted, the authenticated user's email address is used.
   *
   * Tests notification email delivery with the provided or stored SMTP settings.
   */
  testInstanceEmailSetting(
    params: InstanceServiceTestInstanceEmailSettingParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof instanceServiceTestInstanceEmailSetting> {
    return instanceServiceTestInstanceEmailSetting(this._config, params, requestOptions);
  }
  /**
   * Retrieves multiple instance settings in a single request. Provide the resource names in `names`; the response returns the matching settings in the same order as the requested names.
   *
   * Batch gets instance settings.
   */
  batchGetInstanceSettings(
    params: InstanceServiceBatchGetInstanceSettingsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof instanceServiceBatchGetInstanceSettings> {
    return instanceServiceBatchGetInstanceSettings(this._config, params, requestOptions);
  }
  /**
   * Retrieves resource usage statistics for the instance. Access is restricted to administrators, so use an account with the `admin` role.
   *
   * GetInstanceStats returns resource usage statistics for the instance. Admin only.
   */
  getInstanceStats(
    requestOptions?: RequestOptions,
  ): ReturnType<typeof instanceServiceGetInstanceStats> {
    return instanceServiceGetInstanceStats(this._config, requestOptions);
  }
  /**
   * Retrieves a setting for the specified instance. Use the `instance` identifier to select the instance and request the setting by its resource name, formatted as `instance/settings/{setting}`.
   *
   * Gets an instance setting.
   */
  getInstanceSetting(
    params: InstanceServiceGetInstanceSettingParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof instanceServiceGetInstanceSetting> {
    return instanceServiceGetInstanceSetting(this._config, params, requestOptions);
  }
  /**
   * Updates configuration for an instance setting. Supply the setting resource in the request body and use `updateMask` to specify which fields to update; `storageType` and `accessMode` accept only their documented enum values.
   *
   * Updates an instance setting.
   */
  updateInstanceSetting(
    params: InstanceServiceUpdateInstanceSettingParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof instanceServiceUpdateInstanceSetting> {
    return instanceServiceUpdateInstanceSetting(this._config, params, requestOptions);
  }
}
