// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

export * from "./memoService/part1";
export * from "./memoService/part2";
import type { ClientConfig, RequestOptions } from "../client";

import type {
  MemoServiceBatchGetLinkMetadataParams,
  MemoServiceCreateMemoCommentParams,
  MemoServiceCreateMemoParams,
  MemoServiceDeleteMemoParams,
  MemoServiceGetLinkMetadataParams,
  MemoServiceGetMemoParams,
  MemoServiceListMemoAttachmentsParams,
  MemoServiceListMemoCommentsParams,
  MemoServiceListMemoReactionsParams,
  MemoServiceListMemosParams,
  MemoServiceSetMemoAttachmentsParams,
  MemoServiceUpdateMemoParams,
  MemoServiceUpsertMemoReactionParams,
} from "./memoService/part1";
import {
  memoServiceBatchGetLinkMetadata,
  memoServiceCreateMemo,
  memoServiceCreateMemoComment,
  memoServiceDeleteMemo,
  memoServiceGetLinkMetadata,
  memoServiceGetMemo,
  memoServiceListMemoAttachments,
  memoServiceListMemoComments,
  memoServiceListMemoReactions,
  memoServiceListMemos,
  memoServiceSetMemoAttachments,
  memoServiceUpdateMemo,
  memoServiceUpsertMemoReaction,
} from "./memoService/part1";
import type {
  MemoServiceCreateMemoShareParams,
  MemoServiceDeleteMemoReactionParams,
  MemoServiceDeleteMemoShareParams,
  MemoServiceGetSharedMemoParams,
  MemoServiceListMemoRelationsParams,
  MemoServiceListMemoSharesParams,
  MemoServiceSetMemoRelationsParams,
} from "./memoService/part2";
import {
  memoServiceCreateMemoShare,
  memoServiceDeleteMemoReaction,
  memoServiceDeleteMemoShare,
  memoServiceGetSharedMemo,
  memoServiceListMemoRelations,
  memoServiceListMemoShares,
  memoServiceSetMemoRelations,
} from "./memoService/part2";

export class MemoServiceNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Lists readable, non-comment memos, with support for pagination, filtering, and sorting. Use `filter` to select memos and `orderBy` to control their order; `pageToken` continues a listing from a previous response.
   *
   * ListMemos lists readable non-comment memos with pagination and filter.
   */
  listMemos(
    params: MemoServiceListMemosParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof memoServiceListMemos> {
    return memoServiceListMemos(this._config, params, requestOptions);
  }
  /**
   * Creates a memo owned by the authenticated user. Supply `content` in Markdown and choose a `visibility`; visibility defaults to PRIVATE when omitted. You must authenticate to create a memo.
   *
   * CreateMemo creates a memo. The request body is a Memo; set its content (Markdown) and visibility (PRIVATE | PROTECTED | PUBLIC | SPACE, default PRIVATE). The memo is owned by the authenticated user; requires authentication.
   */
  createMemo(
    params: MemoServiceCreateMemoParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof memoServiceCreateMemo> {
    return memoServiceCreateMemo(this._config, params, requestOptions);
  }
  /**
   * Retrieves metadata for a link. Provide the link's `url` to get its title, description, and image URL.
   *
   * GetLinkMetadata gets metadata for a link.
   */
  getLinkMetadata(
    params: MemoServiceGetLinkMetadataParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof memoServiceGetLinkMetadata> {
    return memoServiceGetLinkMetadata(this._config, params, requestOptions);
  }
  /**
   * Retrieves metadata for multiple links in one request. Supply the link URLs in `urls`; the response preserves the input order.
   *
   * BatchGetLinkMetadata gets metadata for links.
   */
  batchGetLinkMetadata(
    params: MemoServiceBatchGetLinkMetadataParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof memoServiceBatchGetLinkMetadata> {
    return memoServiceBatchGetLinkMetadata(this._config, params, requestOptions);
  }
  /**
   * Retrieves a memo by its identifier. Use the `memo` path parameter to specify which memo to retrieve.
   *
   * GetMemo gets a memo.
   */
  getMemo(
    params: MemoServiceGetMemoParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof memoServiceGetMemo> {
    return memoServiceGetMemo(this._config, params, requestOptions);
  }
  /**
   * Deletes the named memo and its owned resources without deleting other memos. Use `force` to delete the memo even when it has associated data; incident relations are removed.
   *
   * DeleteMemo deletes only the named memo and its owned resources. It removes incident relations but never deletes another memo.
   */
  deleteMemo(
    params: MemoServiceDeleteMemoParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof memoServiceDeleteMemo> {
    return memoServiceDeleteMemo(this._config, params, requestOptions);
  }
  /**
   * Updates a memo with the fields supplied in the request body. Use `updateMask` to identify the fields to update; `state`, `content`, and `visibility` are required by the request schema.
   *
   * UpdateMemo updates a memo.
   */
  updateMemo(
    params: MemoServiceUpdateMemoParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof memoServiceUpdateMemo> {
    return memoServiceUpdateMemo(this._config, params, requestOptions);
  }
  /**
   * Lists attachments associated with a specific memo. Use `pageSize` to limit the number of results and `pageToken` to continue through the results.
   *
   * ListMemoAttachments lists attachments for a memo.
   */
  listMemoAttachments(
    params: MemoServiceListMemoAttachmentsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof memoServiceListMemoAttachments> {
    return memoServiceListMemoAttachments(this._config, params, requestOptions);
  }
  /**
   * Replaces the full set of attachments associated with a memo. Pass the complete desired list in `attachments`; an empty list clears the memo's attachments, and repeating the same request is idempotent.
   *
   * SetMemoAttachments replaces the full set of attachments on a memo with the provided list (not an append). Pass the complete desired set; an empty list clears all attachments. Idempotent.
   */
  setMemoAttachments(
    params: MemoServiceSetMemoAttachmentsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof memoServiceSetMemoAttachments> {
    return memoServiceSetMemoAttachments(this._config, params, requestOptions);
  }
  /**
   * Lists comments associated with a specific memo. Use `pageSize` and `pageToken` to control pagination, and `orderBy` to specify the result sort order.
   *
   * ListMemoComments lists comments for a memo.
   */
  listMemoComments(
    params: MemoServiceListMemoCommentsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof memoServiceListMemoComments> {
    return memoServiceListMemoComments(this._config, params, requestOptions);
  }
  /**
   * Creates an independent memo with an immutable COMMENT relation to the specified memo. Supply `state`, `content`, and `visibility`; the new memo retains its own placement, visibility, authorship, and lifecycle.
   *
   * CreateMemoComment atomically creates an independent memo plus one immutable COMMENT context relation to the named memo. The new memo keeps its own placement, visibility, authorship, and lifecycle.
   */
  createMemoComment(
    params: MemoServiceCreateMemoCommentParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof memoServiceCreateMemoComment> {
    return memoServiceCreateMemoComment(this._config, params, requestOptions);
  }
  /**
   * Lists reactions associated with a specific memo. Use `pageSize` to limit the number of results and `pageToken` to retrieve subsequent pages.
   *
   * ListMemoReactions lists reactions for a memo.
   */
  listMemoReactions(
    params: MemoServiceListMemoReactionsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof memoServiceListMemoReactions> {
    return memoServiceListMemoReactions(this._config, params, requestOptions);
  }
  /**
   * Adds or updates the authenticated user's reaction on a memo. Supply the memo resource name and the reaction with its `reactionType`; the operation upserts the authenticated user's reaction.
   *
   * UpsertMemoReaction adds or updates the authenticated user's reaction on a memo.
   */
  upsertMemoReaction(
    params: MemoServiceUpsertMemoReactionParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof memoServiceUpsertMemoReaction> {
    return memoServiceUpsertMemoReaction(this._config, params, requestOptions);
  }
  /**
   * Deletes a reaction from a memo. Supply both the memo identifier and the reaction identifier to select the reaction to remove.
   *
   * DeleteMemoReaction deletes a reaction for a memo.
   */
  deleteMemoReaction(
    params: MemoServiceDeleteMemoReactionParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof memoServiceDeleteMemoReaction> {
    return memoServiceDeleteMemoReaction(this._config, params, requestOptions);
  }
  /**
   * Lists relations associated with a specific memo. Use `pageSize` to limit the number of results and `pageToken` to retrieve subsequent pages.
   *
   * ListMemoRelations lists relations for a memo.
   */
  listMemoRelations(
    params: MemoServiceListMemoRelationsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof memoServiceListMemoRelations> {
    return memoServiceListMemoRelations(this._config, params, requestOptions);
  }
  /**
   * Replaces the full set of mutable REFERENCE relations on a memo. Pass the complete desired list in `relations`; an empty list clears REFERENCE relations, while COMMENT relations remain unchanged and cannot be set through this operation.
   *
   * SetMemoRelations replaces the full set of mutable REFERENCE relations on a memo. COMMENT relations are immutable creation context and are rejected by this RPC. An empty list clears references without changing COMMENT.
   */
  setMemoRelations(
    params: MemoServiceSetMemoRelationsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof memoServiceSetMemoRelations> {
    return memoServiceSetMemoRelations(this._config, params, requestOptions);
  }
  /**
   * Lists share links that grant read-only access to a memo through opaque bearer tokens. The authenticated user must be the memo creator or an instance administrator.
   *
   * ListMemoShares lists all share links for a memo. Requires the memo creator or an instance administrator.
   */
  listMemoShares(
    params: MemoServiceListMemoSharesParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof memoServiceListMemoShares> {
    return memoServiceListMemoShares(this._config, params, requestOptions);
  }
  /**
   * Creates a share link that grants read-only access to a memo through an opaque bearer token. The authenticated user must be the memo creator or an instance administrator; set `expireTime` to limit how long the link works.
   *
   * CreateMemoShare creates a share link for a memo. Requires the memo creator or an instance administrator.
   */
  createMemoShare(
    params: MemoServiceCreateMemoShareParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof memoServiceCreateMemoShare> {
    return memoServiceCreateMemoShare(this._config, params, requestOptions);
  }
  /**
   * Deletes a share link and revokes its read-only access to a memo. The authenticated user must be the memo creator or an instance administrator, and the share must belong to the specified memo.
   *
   * DeleteMemoShare revokes a share link. Requires the memo creator or an instance administrator.
   */
  deleteMemoShare(
    params: MemoServiceDeleteMemoShareParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof memoServiceDeleteMemoShare> {
    return memoServiceDeleteMemoShare(this._config, params, requestOptions);
  }
  /**
   * Retrieves the memo associated with a share token without requiring authentication. Use the opaque `shareToken` from the share URL; the token must be valid and unexpired to resolve the memo.
   *
   * GetSharedMemo resolves a share token to its memo. No authentication required. Returns NOT_FOUND if the token is invalid or expired.
   */
  getSharedMemo(
    params: MemoServiceGetSharedMemoParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof memoServiceGetSharedMemo> {
    return memoServiceGetSharedMemo(this._config, params, requestOptions);
  }
}
