// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import {
  AcceptSpaceInvitationRequest,
  DeclineSpaceInvitationRequest,
  ListSpaceInvitationsResponse,
  ListSpaceMembersResponse,
  ListSpacesResponse,
  ListUserSpaceInvitationsResponse,
  SpaceInvitation,
  SpaceMember,
} from "../types/space-service";
import { Space, Status } from "../types/shared";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, queryValue, sdkRequest } from "../client";

export type SpaceServiceListSpacesError = Status;

export interface SpaceServiceListSpacesParams {
  pageSize?: number;
  pageToken?: string;
}

/**
 * Lists spaces that the authenticated user is a member of. Use `pageSize` to limit the number of results and `pageToken` to continue from a previous response.
 *
 * ListSpaces lists spaces of which the authenticated caller is a member.
 *
 * @param pageSize - Optional. The maximum number of spaces to return.
 * @param pageToken - Optional. A token from a previous ListSpaces response.
 */
export async function spaceServiceListSpaces(
  config: ClientConfig,
  { pageSize, pageToken }: SpaceServiceListSpacesParams = {},
  requestOptions?: RequestOptions,
): Promise<ListSpacesResponse> {
  const _resp = await sdkRequest<ListSpacesResponse>({
    method: "GET",
    path: `/api/v1/spaces`,
    operationId: "spaceServiceListSpaces",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      pageSize: queryValue(pageSize, "form", true),
      pageToken: queryValue(pageToken, "form", true),
    },
    config,
  });
  return _resp.data;
}

export type SpaceServiceCreateSpaceError = Status;

export type SpaceServiceCreateSpaceParams = Space & {
  spaceId?: string;
};

/**
 * Creates a space and makes the authenticated user its first administrator. Provide a `title` for the space, and optionally supply `spaceId` to choose its identifier; an empty or omitted `spaceId` generates a canonical UUID v4.
 *
 * CreateSpace creates a space and makes the authenticated caller its first administrator.
 *
 * @param title - Required. The human-readable title.
 * @param spaceId - Optional. The space UID to use for this space. If empty, a
 *   canonical UUID v4 will be generated. Format:
 *   ^[a-zA-Z0-9]([a-zA-Z0-9-]{0,34}[a-zA-Z0-9])?$
 * @param name - The resource name of the space. Format: spaces/{space}.
 * @param description - Optional. A description of the space.
 * @param currentUserRole - Output only. The authenticated user's membership role
 *   in this space. ROLE_UNSPECIFIED when this Space is exposed as metadata-only.
 * @param memberCount - Output only. The number of accepted members in this
 *   space. Pending invitations are excluded. Zero when this Space is exposed as
 *   metadata-only.
 * @param icon - Optional. Display icon. Omit when updating with the "icon" mask
 *   to reset to the default Space mark.
 */
export async function spaceServiceCreateSpace(
  config: ClientConfig,
  {
    title,
    spaceId,
    name,
    description,
    currentUserRole,
    memberCount,
    icon,
  }: SpaceServiceCreateSpaceParams,
  requestOptions?: RequestOptions,
): Promise<Space> {
  const _resp = await sdkRequest<Space>({
    method: "POST",
    path: `/api/v1/spaces`,
    operationId: "spaceServiceCreateSpace",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      spaceId: queryValue(spaceId, "form", true),
    },
    body: {
      title,
      name,
      description,
      currentUserRole,
      memberCount,
      icon,
    },
    config,
  });
  return _resp.data;
}

export type SpaceServiceGetSpaceError = Status;

export interface SpaceServiceGetSpaceParams {
  space: string;
}

/**
 * Retrieves a space that the authenticated user is a member of. Supply the space identifier to view its title, description, membership information, and other available metadata.
 *
 * GetSpace gets a space of which the authenticated caller is a member.
 *
 * @param space - The space id.
 */
export async function spaceServiceGetSpace(
  config: ClientConfig,
  { space }: SpaceServiceGetSpaceParams,
  requestOptions?: RequestOptions,
): Promise<Space> {
  const _resp = await sdkRequest<Space>({
    method: "GET",
    path: `/api/v1/spaces/${encodePathSegment(space)}`,
    operationId: "spaceServiceGetSpace",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type SpaceServiceDeleteSpaceError = Status;

export interface SpaceServiceDeleteSpaceParams {
  space: string;
}

/**
 * Deletes a space and every memo currently placed in it. This permanently removes those memos; deletion does not follow memo relations to other memos.
 *
 * DeleteSpace permanently deletes a space and every memo currently placed in it. It never follows memo relations to other memos.
 *
 * @param space - The space id.
 */
export async function spaceServiceDeleteSpace(
  config: ClientConfig,
  { space }: SpaceServiceDeleteSpaceParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "DELETE",
    path: `/api/v1/spaces/${encodePathSegment(space)}`,
    operationId: "spaceServiceDeleteSpace",
    responseDecoder: "empty",
    ...requestOptions,
    config,
  });
  void _resp.data;
  return;
}

export type SpaceServiceUpdateSpaceError = Status;

export type SpaceServiceUpdateSpaceParams = Space & {
  space: string;
  updateMask?: string;
};

/**
 * Updates metadata for a space. Use `updateMask` to select `title` or `description`, and provide `title` as required by the request schema.
 *
 * UpdateSpace updates space metadata.
 *
 * @param space - The space id.
 * @param title - Required. The human-readable title.
 * @param updateMask - Required. The fields to update: title or description.
 * @param name - The resource name of the space. Format: spaces/{space}.
 * @param description - Optional. A description of the space.
 * @param currentUserRole - Output only. The authenticated user's membership role
 *   in this space. ROLE_UNSPECIFIED when this Space is exposed as metadata-only.
 * @param memberCount - Output only. The number of accepted members in this
 *   space. Pending invitations are excluded. Zero when this Space is exposed as
 *   metadata-only.
 * @param icon - Optional. Display icon. Omit when updating with the "icon" mask
 *   to reset to the default Space mark.
 */
export async function spaceServiceUpdateSpace(
  config: ClientConfig,
  {
    space,
    title,
    updateMask,
    name,
    description,
    currentUserRole,
    memberCount,
    icon,
  }: SpaceServiceUpdateSpaceParams,
  requestOptions?: RequestOptions,
): Promise<Space> {
  const _resp = await sdkRequest<Space>({
    method: "PATCH",
    path: `/api/v1/spaces/${encodePathSegment(space)}`,
    operationId: "spaceServiceUpdateSpace",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      updateMask: queryValue(updateMask, "form", true),
    },
    body: {
      title,
      name,
      description,
      currentUserRole,
      memberCount,
      icon,
    },
    config,
  });
  return _resp.data;
}

export type SpaceServiceListSpaceInvitationsError = Status;

export interface SpaceServiceListSpaceInvitationsParams {
  space: string;
  pageSize?: number;
  pageToken?: string;
}

/**
 * Lists pending invitations for a space. Use `pageSize` to limit the number of invitations returned and `pageToken` to continue from a previous response.
 *
 * ListSpaceInvitations lists the pending invitations for a space.
 *
 * @param space - The space id.
 * @param pageSize - Optional. The maximum number of invitations to return.
 * @param pageToken - Optional. A token from a previous ListSpaceInvitations
 *   response.
 */
export async function spaceServiceListSpaceInvitations(
  config: ClientConfig,
  { space, pageSize, pageToken }: SpaceServiceListSpaceInvitationsParams,
  requestOptions?: RequestOptions,
): Promise<ListSpaceInvitationsResponse> {
  const _resp = await sdkRequest<ListSpaceInvitationsResponse>({
    method: "GET",
    path: `/api/v1/spaces/${encodePathSegment(space)}/invitations`,
    operationId: "spaceServiceListSpaceInvitations",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      pageSize: queryValue(pageSize, "form", true),
      pageToken: queryValue(pageToken, "form", true),
    },
    config,
  });
  return _resp.data;
}

export type SpaceServiceCreateSpaceInvitationError = Status;

export type SpaceServiceCreateSpaceInvitationParams = SpaceInvitation & {
  space: string;
};

/**
 * Creates an invitation for an existing active user to join a space. Provide the invitee's user resource name in `invitee` and choose the role they will receive after accepting.
 *
 * CreateSpaceInvitation invites an existing active user to a space.
 *
 * @param space - The space id.
 * @param invitee - Required. The invited user. Format: users/{username}.
 * @param role - Required. The role the user will receive after accepting the
 *   invitation.
 * @param name - The resource name. Format:
 *   spaces/{space}/invitations/{username}.
 * @param space_2 - Output only. The Space the user is invited to. This lets an
 *   invitee understand the invitation without granting membership-based GetSpace
 *   access.
 */
export async function spaceServiceCreateSpaceInvitation(
  config: ClientConfig,
  { space, invitee, role, name, space: space_2 }: SpaceServiceCreateSpaceInvitationParams,
  requestOptions?: RequestOptions,
): Promise<SpaceInvitation> {
  const _resp = await sdkRequest<SpaceInvitation>({
    method: "POST",
    path: `/api/v1/spaces/${encodePathSegment(space)}/invitations`,
    operationId: "spaceServiceCreateSpaceInvitation",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      invitee,
      role,
      name,
      space: space_2,
    },
    config,
  });
  return _resp.data;
}

export type SpaceServiceGetSpaceInvitationError = Status;

export interface SpaceServiceGetSpaceInvitationParams {
  space: string;
  invitation: string;
}

/**
 * Retrieves a pending invitation to join a space. Use `space` and `invitation` to identify the invitation whose details you need, including its invitee and assigned role.
 *
 * GetSpaceInvitation gets one pending invitation.
 *
 * @param space - The space id.
 * @param invitation - The invitation id.
 */
export async function spaceServiceGetSpaceInvitation(
  config: ClientConfig,
  { space, invitation }: SpaceServiceGetSpaceInvitationParams,
  requestOptions?: RequestOptions,
): Promise<SpaceInvitation> {
  const _resp = await sdkRequest<SpaceInvitation>({
    method: "GET",
    path: `/api/v1/spaces/${encodePathSegment(space)}/invitations/${encodePathSegment(invitation)}`,
    operationId: "spaceServiceGetSpaceInvitation",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type SpaceServiceDeleteSpaceInvitationError = Status;

export interface SpaceServiceDeleteSpaceInvitationParams {
  space: string;
  invitation: string;
}

/**
 * Deletes a pending invitation to join a space, revoking the invitation. Identify the space and invitation so you remove the intended invitation.
 *
 * DeleteSpaceInvitation revokes a pending invitation.
 *
 * @param space - The space id.
 * @param invitation - The invitation id.
 */
export async function spaceServiceDeleteSpaceInvitation(
  config: ClientConfig,
  { space, invitation }: SpaceServiceDeleteSpaceInvitationParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "DELETE",
    path: `/api/v1/spaces/${encodePathSegment(space)}/invitations/${encodePathSegment(invitation)}`,
    operationId: "spaceServiceDeleteSpaceInvitation",
    responseDecoder: "empty",
    ...requestOptions,
    config,
  });
  void _resp.data;
  return;
}

export type SpaceServiceAcceptSpaceInvitationError = Status;

export type SpaceServiceAcceptSpaceInvitationParams = AcceptSpaceInvitationRequest & {
  space: string;
  invitation: string;
};

/**
 * Accepts a pending invitation to join a space and creates a membership for the invitee. Supply the invitation resource name in `name`; the returned membership includes the user's role in the space.
 *
 * AcceptSpaceInvitation accepts a pending invitation and creates a membership.
 *
 * @param space - The space id.
 * @param invitation - The invitation id.
 * @param name - Required. Format: spaces/{space}/invitations/{username}.
 */
export async function spaceServiceAcceptSpaceInvitation(
  config: ClientConfig,
  { space, invitation, name }: SpaceServiceAcceptSpaceInvitationParams,
  requestOptions?: RequestOptions,
): Promise<SpaceMember> {
  const _resp = await sdkRequest<SpaceMember>({
    method: "POST",
    path: `/api/v1/spaces/${encodePathSegment(space)}/invitations/${encodePathSegment(invitation)}:accept`,
    operationId: "spaceServiceAcceptSpaceInvitation",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      name,
    },
    config,
  });
  return _resp.data;
}

export type SpaceServiceDeclineSpaceInvitationError = Status;

export type SpaceServiceDeclineSpaceInvitationParams = DeclineSpaceInvitationRequest & {
  space: string;
  invitation: string;
};

/**
 * Declines a pending invitation to join a space. Supply the invitation resource name in `name` to identify the invitation being declined.
 *
 * DeclineSpaceInvitation declines a pending invitation.
 *
 * @param space - The space id.
 * @param invitation - The invitation id.
 * @param name - Required. Format: spaces/{space}/invitations/{username}.
 */
export async function spaceServiceDeclineSpaceInvitation(
  config: ClientConfig,
  { space, invitation, name }: SpaceServiceDeclineSpaceInvitationParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "POST",
    path: `/api/v1/spaces/${encodePathSegment(space)}/invitations/${encodePathSegment(invitation)}:decline`,
    operationId: "spaceServiceDeclineSpaceInvitation",
    responseDecoder: "empty",
    ...requestOptions,
    body: {
      name,
    },
    config,
  });
  void _resp.data;
  return;
}

export type SpaceServiceListSpaceMembersError = Status;

export interface SpaceServiceListSpaceMembersParams {
  space: string;
  pageSize?: number;
  pageToken?: string;
}

/**
 * Lists the members of a space. Use `pageSize` to limit the number of members returned and `pageToken` to continue from a previous response.
 *
 * ListSpaceMembers lists the members of a space.
 *
 * @param space - The space id.
 * @param pageSize - Optional. The maximum number of members to return.
 * @param pageToken - Optional. A token from a previous ListSpaceMembers
 *   response.
 */
export async function spaceServiceListSpaceMembers(
  config: ClientConfig,
  { space, pageSize, pageToken }: SpaceServiceListSpaceMembersParams,
  requestOptions?: RequestOptions,
): Promise<ListSpaceMembersResponse> {
  const _resp = await sdkRequest<ListSpaceMembersResponse>({
    method: "GET",
    path: `/api/v1/spaces/${encodePathSegment(space)}/members`,
    operationId: "spaceServiceListSpaceMembers",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      pageSize: queryValue(pageSize, "form", true),
      pageToken: queryValue(pageToken, "form", true),
    },
    config,
  });
  return _resp.data;
}

export type SpaceServiceGetSpaceMemberError = Status;

export interface SpaceServiceGetSpaceMemberParams {
  space: string;
  member: string;
}

/**
 * Retrieves one membership in a space. Use `space` and `member` to identify the space membership whose user and role you need.
 *
 * GetSpaceMember gets one membership in a space.
 *
 * @param space - The space id.
 * @param member - The member id.
 */
export async function spaceServiceGetSpaceMember(
  config: ClientConfig,
  { space, member }: SpaceServiceGetSpaceMemberParams,
  requestOptions?: RequestOptions,
): Promise<SpaceMember> {
  const _resp = await sdkRequest<SpaceMember>({
    method: "GET",
    path: `/api/v1/spaces/${encodePathSegment(space)}/members/${encodePathSegment(member)}`,
    operationId: "spaceServiceGetSpaceMember",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type SpaceServiceDeleteSpaceMemberError = Status;

export interface SpaceServiceDeleteSpaceMemberParams {
  space: string;
  member: string;
}

/**
 * Deletes a membership from a space, removing the member. A member can delete their own membership to leave the space.
 *
 * DeleteSpaceMember removes a member. A member may delete their own membership to leave the space.
 *
 * @param space - The space id.
 * @param member - The member id.
 */
export async function spaceServiceDeleteSpaceMember(
  config: ClientConfig,
  { space, member }: SpaceServiceDeleteSpaceMemberParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "DELETE",
    path: `/api/v1/spaces/${encodePathSegment(space)}/members/${encodePathSegment(member)}`,
    operationId: "spaceServiceDeleteSpaceMember",
    responseDecoder: "empty",
    ...requestOptions,
    config,
  });
  void _resp.data;
  return;
}

export type SpaceServiceUpdateSpaceMemberError = Status;

export type SpaceServiceUpdateSpaceMemberParams = SpaceMember & {
  space: string;
  member: string;
  updateMask?: string;
};

/**
 * Updates a member's role in a space. Supply the member resource in the body and use `updateMask` to select the supported `role` field for the update.
 *
 * UpdateSpaceMember changes a member's space role.
 *
 * @param space - The space id.
 * @param member - The member id.
 * @param user - Required. The member user. Format: users/{username}.
 * @param role - Required. The member's role within this space.
 * @param updateMask - Required. Only role is supported.
 * @param name - The resource name. Format: spaces/{space}/members/{username}.
 */
export async function spaceServiceUpdateSpaceMember(
  config: ClientConfig,
  { space, member, user, role, updateMask, name }: SpaceServiceUpdateSpaceMemberParams,
  requestOptions?: RequestOptions,
): Promise<SpaceMember> {
  const _resp = await sdkRequest<SpaceMember>({
    method: "PATCH",
    path: `/api/v1/spaces/${encodePathSegment(space)}/members/${encodePathSegment(member)}`,
    operationId: "spaceServiceUpdateSpaceMember",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      updateMask: queryValue(updateMask, "form", true),
    },
    body: {
      user,
      role,
      name,
    },
    config,
  });
  return _resp.data;
}

export type SpaceServiceListUserSpaceInvitationsError = Status;

export interface SpaceServiceListUserSpaceInvitationsParams {
  user: string;
  pageSize?: number;
  pageToken?: string;
}

/**
 * Lists pending space invitations for a user. Use `pageSize` to set the maximum number of invitations to return and `pageToken` to continue through the results. The invitations are for joining spaces.
 *
 * ListUserSpaceInvitations lists the authenticated user's pending space invitations.
 *
 * @param user - The user id.
 * @param pageSize - Optional. The maximum number of invitations to return.
 * @param pageToken - Optional. A token from a previous ListUserSpaceInvitations
 *   response.
 */
export async function spaceServiceListUserSpaceInvitations(
  config: ClientConfig,
  { user, pageSize, pageToken }: SpaceServiceListUserSpaceInvitationsParams,
  requestOptions?: RequestOptions,
): Promise<ListUserSpaceInvitationsResponse> {
  const _resp = await sdkRequest<ListUserSpaceInvitationsResponse>({
    method: "GET",
    path: `/api/v1/users/${encodePathSegment(user)}/spaceInvitations`,
    operationId: "spaceServiceListUserSpaceInvitations",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      pageSize: queryValue(pageSize, "form", true),
      pageToken: queryValue(pageToken, "form", true),
    },
    config,
  });
  return _resp.data;
}

export class SpaceServiceNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Lists spaces that the authenticated user is a member of. Use `pageSize` to limit the number of results and `pageToken` to continue from a previous response.
   *
   * ListSpaces lists spaces of which the authenticated caller is a member.
   */
  listSpaces(
    params: SpaceServiceListSpacesParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof spaceServiceListSpaces> {
    return spaceServiceListSpaces(this._config, params, requestOptions);
  }
  /**
   * Creates a space and makes the authenticated user its first administrator. Provide a `title` for the space, and optionally supply `spaceId` to choose its identifier; an empty or omitted `spaceId` generates a canonical UUID v4.
   *
   * CreateSpace creates a space and makes the authenticated caller its first administrator.
   */
  createSpace(
    params: SpaceServiceCreateSpaceParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof spaceServiceCreateSpace> {
    return spaceServiceCreateSpace(this._config, params, requestOptions);
  }
  /**
   * Retrieves a space that the authenticated user is a member of. Supply the space identifier to view its title, description, membership information, and other available metadata.
   *
   * GetSpace gets a space of which the authenticated caller is a member.
   */
  getSpace(
    params: SpaceServiceGetSpaceParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof spaceServiceGetSpace> {
    return spaceServiceGetSpace(this._config, params, requestOptions);
  }
  /**
   * Deletes a space and every memo currently placed in it. This permanently removes those memos; deletion does not follow memo relations to other memos.
   *
   * DeleteSpace permanently deletes a space and every memo currently placed in it. It never follows memo relations to other memos.
   */
  deleteSpace(
    params: SpaceServiceDeleteSpaceParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof spaceServiceDeleteSpace> {
    return spaceServiceDeleteSpace(this._config, params, requestOptions);
  }
  /**
   * Updates metadata for a space. Use `updateMask` to select `title` or `description`, and provide `title` as required by the request schema.
   *
   * UpdateSpace updates space metadata.
   */
  updateSpace(
    params: SpaceServiceUpdateSpaceParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof spaceServiceUpdateSpace> {
    return spaceServiceUpdateSpace(this._config, params, requestOptions);
  }
  /**
   * Lists pending invitations for a space. Use `pageSize` to limit the number of invitations returned and `pageToken` to continue from a previous response.
   *
   * ListSpaceInvitations lists the pending invitations for a space.
   */
  listSpaceInvitations(
    params: SpaceServiceListSpaceInvitationsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof spaceServiceListSpaceInvitations> {
    return spaceServiceListSpaceInvitations(this._config, params, requestOptions);
  }
  /**
   * Creates an invitation for an existing active user to join a space. Provide the invitee's user resource name in `invitee` and choose the role they will receive after accepting.
   *
   * CreateSpaceInvitation invites an existing active user to a space.
   */
  createSpaceInvitation(
    params: SpaceServiceCreateSpaceInvitationParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof spaceServiceCreateSpaceInvitation> {
    return spaceServiceCreateSpaceInvitation(this._config, params, requestOptions);
  }
  /**
   * Retrieves a pending invitation to join a space. Use `space` and `invitation` to identify the invitation whose details you need, including its invitee and assigned role.
   *
   * GetSpaceInvitation gets one pending invitation.
   */
  getSpaceInvitation(
    params: SpaceServiceGetSpaceInvitationParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof spaceServiceGetSpaceInvitation> {
    return spaceServiceGetSpaceInvitation(this._config, params, requestOptions);
  }
  /**
   * Deletes a pending invitation to join a space, revoking the invitation. Identify the space and invitation so you remove the intended invitation.
   *
   * DeleteSpaceInvitation revokes a pending invitation.
   */
  deleteSpaceInvitation(
    params: SpaceServiceDeleteSpaceInvitationParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof spaceServiceDeleteSpaceInvitation> {
    return spaceServiceDeleteSpaceInvitation(this._config, params, requestOptions);
  }
  /**
   * Accepts a pending invitation to join a space and creates a membership for the invitee. Supply the invitation resource name in `name`; the returned membership includes the user's role in the space.
   *
   * AcceptSpaceInvitation accepts a pending invitation and creates a membership.
   */
  acceptSpaceInvitation(
    params: SpaceServiceAcceptSpaceInvitationParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof spaceServiceAcceptSpaceInvitation> {
    return spaceServiceAcceptSpaceInvitation(this._config, params, requestOptions);
  }
  /**
   * Declines a pending invitation to join a space. Supply the invitation resource name in `name` to identify the invitation being declined.
   *
   * DeclineSpaceInvitation declines a pending invitation.
   */
  declineSpaceInvitation(
    params: SpaceServiceDeclineSpaceInvitationParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof spaceServiceDeclineSpaceInvitation> {
    return spaceServiceDeclineSpaceInvitation(this._config, params, requestOptions);
  }
  /**
   * Lists the members of a space. Use `pageSize` to limit the number of members returned and `pageToken` to continue from a previous response.
   *
   * ListSpaceMembers lists the members of a space.
   */
  listSpaceMembers(
    params: SpaceServiceListSpaceMembersParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof spaceServiceListSpaceMembers> {
    return spaceServiceListSpaceMembers(this._config, params, requestOptions);
  }
  /**
   * Retrieves one membership in a space. Use `space` and `member` to identify the space membership whose user and role you need.
   *
   * GetSpaceMember gets one membership in a space.
   */
  getSpaceMember(
    params: SpaceServiceGetSpaceMemberParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof spaceServiceGetSpaceMember> {
    return spaceServiceGetSpaceMember(this._config, params, requestOptions);
  }
  /**
   * Deletes a membership from a space, removing the member. A member can delete their own membership to leave the space.
   *
   * DeleteSpaceMember removes a member. A member may delete their own membership to leave the space.
   */
  deleteSpaceMember(
    params: SpaceServiceDeleteSpaceMemberParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof spaceServiceDeleteSpaceMember> {
    return spaceServiceDeleteSpaceMember(this._config, params, requestOptions);
  }
  /**
   * Updates a member's role in a space. Supply the member resource in the body and use `updateMask` to select the supported `role` field for the update.
   *
   * UpdateSpaceMember changes a member's space role.
   */
  updateSpaceMember(
    params: SpaceServiceUpdateSpaceMemberParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof spaceServiceUpdateSpaceMember> {
    return spaceServiceUpdateSpaceMember(this._config, params, requestOptions);
  }
  /**
   * Lists pending space invitations for a user. Use `pageSize` to set the maximum number of invitations to return and `pageToken` to continue through the results. The invitations are for joining spaces.
   *
   * ListUserSpaceInvitations lists the authenticated user's pending space invitations.
   */
  listUserSpaceInvitations(
    params: SpaceServiceListUserSpaceInvitationsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof spaceServiceListUserSpaceInvitations> {
    return spaceServiceListUserSpaceInvitations(this._config, params, requestOptions);
  }
}
