// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

export * from "./userService/part1";
export * from "./userService/part2";
export * from "./userService/part3";
import type { ClientConfig, RequestOptions } from "../client";

import type {
  UserServiceCreateLinkedIdentityParams,
  UserServiceCreatePersonalAccessTokenParams,
  UserServiceCreateUserParams,
  UserServiceDeleteLinkedIdentityParams,
  UserServiceDeletePersonalAccessTokenParams,
  UserServiceDeleteUserNotificationParams,
  UserServiceDeleteUserParams,
  UserServiceGetLinkedIdentityParams,
  UserServiceGetUserParams,
  UserServiceListLinkedIdentitiesParams,
  UserServiceListPersonalAccessTokensParams,
  UserServiceListUserNotificationsParams,
  UserServiceListUsersParams,
  UserServiceUpdateUserNotificationParams,
  UserServiceUpdateUserParams,
} from "./userService/part1";
import {
  userServiceCreateLinkedIdentity,
  userServiceCreatePersonalAccessToken,
  userServiceCreateUser,
  userServiceDeleteLinkedIdentity,
  userServiceDeletePersonalAccessToken,
  userServiceDeleteUser,
  userServiceDeleteUserNotification,
  userServiceGetLinkedIdentity,
  userServiceGetUser,
  userServiceListLinkedIdentities,
  userServiceListPersonalAccessTokens,
  userServiceListUserNotifications,
  userServiceListUsers,
  userServiceUpdateUser,
  userServiceUpdateUserNotification,
} from "./userService/part1";
import type {
  UserServiceCreateMemoViewParams,
  UserServiceCreateUserWebhookParams,
  UserServiceDeleteMemoViewParams,
  UserServiceDeleteUserWebhookParams,
  UserServiceExportMemosParams,
  UserServiceGetMemoViewParams,
  UserServiceGetUserSettingParams,
  UserServiceGetUserStatsParams,
  UserServiceGetUserWebhookSigningSecretParams,
  UserServiceImportMemosParams,
  UserServiceListMemoViewsParams,
  UserServiceListUserSettingsParams,
  UserServiceListUserWebhooksParams,
  UserServiceUpdateMemoViewParams,
  UserServiceUpdateUserSettingParams,
  UserServiceUpdateUserWebhookParams,
} from "./userService/part2";
import {
  userServiceCreateMemoView,
  userServiceCreateUserWebhook,
  userServiceDeleteMemoView,
  userServiceDeleteUserWebhook,
  userServiceExportMemos,
  userServiceGetMemoView,
  userServiceGetUserSetting,
  userServiceGetUserStats,
  userServiceGetUserWebhookSigningSecret,
  userServiceImportMemos,
  userServiceListMemoViews,
  userServiceListUserSettings,
  userServiceListUserWebhooks,
  userServiceUpdateMemoView,
  userServiceUpdateUserSetting,
  userServiceUpdateUserWebhook,
} from "./userService/part2";
import type {
  UserServiceBatchGetUsersParams,
  UserServiceListAllUserStatsParams,
} from "./userService/part3";
import { userServiceBatchGetUsers, userServiceListAllUserStats } from "./userService/part3";

export class UserServiceNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Lists users on the instance, with optional filtering and inclusion of deleted users. Use `pageToken` to continue through results; `pageSize` defaults to at most 50 and values above 1000 are coerced to 1000.
   *
   * ListUsers returns a list of users.
   */
  listUsers(
    params: UserServiceListUsersParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof userServiceListUsers> {
    return userServiceListUsers(this._config, params, requestOptions);
  }
  /**
   * Creates a user with a username, role, and state, along with any optional profile details. Set `validateOnly` to validate the request without creating the user, or pass `requestId` to make repeated creation requests idempotent.
   *
   * CreateUser creates a new user.
   */
  createUser(
    params: UserServiceCreateUserParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof userServiceCreateUser> {
    return userServiceCreateUser(this._config, params, requestOptions);
  }
  /**
   * Retrieves a user by username. Use the `user` resource name in the format `users/{user}`; specify `readMask` to limit the fields in the response, or omit it to receive all fields.
   *
   * GetUser gets a user by username. Format: users/{user} (e.g., users/steven)
   */
  getUser(
    params: UserServiceGetUserParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof userServiceGetUser> {
    return userServiceGetUser(this._config, params, requestOptions);
  }
  /**
   * Deletes a user. Set `force` to true to delete the user even when associated data exists; otherwise, the user is deleted without that override.
   *
   * DeleteUser deletes a user.
   */
  deleteUser(
    params: UserServiceDeleteUserParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof userServiceDeleteUser> {
    return userServiceDeleteUser(this._config, params, requestOptions);
  }
  /**
   * Updates a user's fields using a partial update. Supply the user resource name and an `updateMask` to select the fields being updated; the request body schema requires `role`, `username`, and `state`.
   *
   * UpdateUser updates a user.
   */
  updateUser(
    params: UserServiceUpdateUserParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof userServiceUpdateUser> {
    return userServiceUpdateUser(this._config, params, requestOptions);
  }
  /**
   * Lists the linked SSO identities for a user. Supply the user's identifier to retrieve the identities associated with that account.
   *
   * ListLinkedIdentities returns a list of linked SSO identities for a user.
   */
  listLinkedIdentities(
    params: UserServiceListLinkedIdentitiesParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof userServiceListLinkedIdentities> {
    return userServiceListLinkedIdentities(this._config, params, requestOptions);
  }
  /**
   * Links an SSO identity to a user through an identity provider's OAuth flow. Provide the parent user, identity provider, authorization code, and redirect URI; include `codeVerifier` when the flow uses PKCE.
   *
   * CreateLinkedIdentity links an SSO identity to the authenticated user.
   */
  createLinkedIdentity(
    params: UserServiceCreateLinkedIdentityParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof userServiceCreateLinkedIdentity> {
    return userServiceCreateLinkedIdentity(this._config, params, requestOptions);
  }
  /**
   * Retrieves a linked SSO identity for a user. Supply both resource identifiers to retrieve the identity associated with that user account.
   *
   * GetLinkedIdentity gets a linked SSO identity for a user.
   */
  getLinkedIdentity(
    params: UserServiceGetLinkedIdentityParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof userServiceGetLinkedIdentity> {
    return userServiceGetLinkedIdentity(this._config, params, requestOptions);
  }
  /**
   * Deletes a linked SSO identity from a user account. Supply the user and linked identity identifiers for the identity you want to unlink.
   *
   * DeleteLinkedIdentity unlinks an SSO identity from a user.
   */
  deleteLinkedIdentity(
    params: UserServiceDeleteLinkedIdentityParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof userServiceDeleteLinkedIdentity> {
    return userServiceDeleteLinkedIdentity(this._config, params, requestOptions);
  }
  /**
   * Lists notifications for a user. Use `pageSize` to control the number of results and `pageToken` to continue through paginated results; optionally use `filter` to narrow the list.
   *
   * ListUserNotifications lists notifications for a user.
   */
  listUserNotifications(
    params: UserServiceListUserNotificationsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof userServiceListUserNotifications> {
    return userServiceListUserNotifications(this._config, params, requestOptions);
  }
  /**
   * Deletes a notification from a user's notification list. Supply the user and notification identifiers for the notification you want to delete.
   *
   * DeleteUserNotification deletes a notification.
   */
  deleteUserNotification(
    params: UserServiceDeleteUserNotificationParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof userServiceDeleteUserNotification> {
    return userServiceDeleteUserNotification(this._config, params, requestOptions);
  }
  /**
   * Updates a user's notification. Use `updateMask` to select the fields to change; the request body schema exposes `status` as an editable field, while the other defined fields are read-only.
   *
   * UpdateUserNotification updates a notification.
   */
  updateUserNotification(
    params: UserServiceUpdateUserNotificationParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof userServiceUpdateUserNotification> {
    return userServiceUpdateUserNotification(this._config, params, requestOptions);
  }
  /**
   * Lists long-lived personal access tokens (PATs) for a user. Use `pageSize` and `pageToken` to retrieve results in pages; PATs provide API and script access and are distinct from short-lived JWTs used for session authentication.
   *
   * ListPersonalAccessTokens returns a list of Personal Access Tokens (PATs) for a user. PATs are long-lived tokens for API/script access, distinct from short-lived JWT access tokens.
   */
  listPersonalAccessTokens(
    params: UserServiceListPersonalAccessTokensParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof userServiceListPersonalAccessTokens> {
    return userServiceListPersonalAccessTokens(this._config, params, requestOptions);
  }
  /**
   * Creates a long-lived personal access token for a user. Supply the required `parent` resource name in the format `users/{user}`; you can optionally provide a `description` and an `expiresInDays` value. The token value is returned only when you create the token, so store it securely at that time.
   *
   * CreatePersonalAccessToken creates a new Personal Access Token for a user. The token value is only returned once upon creation.
   */
  createPersonalAccessToken(
    params: UserServiceCreatePersonalAccessTokenParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof userServiceCreatePersonalAccessToken> {
    return userServiceCreatePersonalAccessToken(this._config, params, requestOptions);
  }
  /**
   * Deletes a personal access token. Provide the user and token identifiers to specify which PAT to delete. The token is a long-lived credential for API or script access.
   *
   * DeletePersonalAccessToken deletes a Personal Access Token.
   */
  deletePersonalAccessToken(
    params: UserServiceDeletePersonalAccessTokenParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof userServiceDeletePersonalAccessToken> {
    return userServiceDeletePersonalAccessToken(this._config, params, requestOptions);
  }
  /**
   * Lists settings for a user. Use `pageSize` to limit the number of settings returned and `pageToken` to continue from a previous page. The service returns at most 50 settings by default and coerces `pageSize` values above 1000 to 1000.
   *
   * ListUserSettings returns a list of user settings.
   */
  listUserSettings(
    params: UserServiceListUserSettingsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof userServiceListUserSettings> {
    return userServiceListUserSettings(this._config, params, requestOptions);
  }
  /**
   * Retrieves a specific setting for a user. Provide the user ID and setting key to identify the setting resource. The setting key appears in the resource name as `users/{user}/settings/{setting}`.
   *
   * GetUserSetting returns the user setting.
   */
  getUserSetting(
    params: UserServiceGetUserSettingParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof userServiceGetUserSetting> {
    return userServiceGetUserSetting(this._config, params, requestOptions);
  }
  /**
   * Updates a user's setting. Supply the setting fields to change and use `updateMask` to specify which fields to update. The setting resource name follows the format `users/{user}/settings/{setting}`.
   *
   * UpdateUserSetting updates the user setting.
   */
  updateUserSetting(
    params: UserServiceUpdateUserSettingParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof userServiceUpdateUserSetting> {
    return userServiceUpdateUserSetting(this._config, params, requestOptions);
  }
  /**
   * Lists a user's saved memo views, each of which stores a reusable CEL filter. Use a view's `filter` value as the `filter` argument when listing memos. The list contains the saved views for the specified user.
   *
   * ListMemoViews returns a user's memo views. Each view is a named, reusable CEL filter (see MemoView.filter); pass its filter string directly to the ListMemos `filter` argument.
   */
  listMemoViews(
    params: UserServiceListMemoViewsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof userServiceListMemoViews> {
    return userServiceListMemoViews(this._config, params, requestOptions);
  }
  /**
   * Creates a saved memo view for a user. Provide the required `title` and CEL `filter` expression; you can optionally provide a display `icon`. Set `validateOnly` to validate the request without creating the view.
   *
   * CreateMemoView creates a new memo view for a user.
   */
  createMemoView(
    params: UserServiceCreateMemoViewParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof userServiceCreateMemoView> {
    return userServiceCreateMemoView(this._config, params, requestOptions);
  }
  /**
   * Retrieves a saved memo view by name. Provide the user ID and view ID to identify the view. The response includes the saved view's CEL filter, which you can pass to the ListMemos `filter` argument.
   *
   * GetMemoView gets a memo view by name.
   */
  getMemoView(
    params: UserServiceGetMemoViewParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof userServiceGetMemoView> {
    return userServiceGetMemoView(this._config, params, requestOptions);
  }
  /**
   * Deletes a saved memo view for a user. Identify the user and the view to remove with the `user` and `view` path parameters.
   *
   * DeleteMemoView deletes a memo view for a user.
   */
  deleteMemoView(
    params: UserServiceDeleteMemoViewParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof userServiceDeleteMemoView> {
    return userServiceDeleteMemoView(this._config, params, requestOptions);
  }
  /**
   * Updates a saved memo view for a user. Supply `title` and `filter`; `filter` uses the CEL grammar accepted by ListMemos, and `updateMask` limits which fields change. Include `icon` in the update mask and omit its value to reset the view icon to the default.
   *
   * UpdateMemoView updates a memo view for a user.
   */
  updateMemoView(
    params: UserServiceUpdateMemoViewParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof userServiceUpdateMemoView> {
    return userServiceUpdateMemoView(this._config, params, requestOptions);
  }
  /**
   * Lists the webhooks owned by a user. Use the `user` path parameter to select whose webhooks to retrieve; the results include webhook configuration and whether a signing secret is set.
   *
   * ListUserWebhooks returns a list of webhooks for a user.
   */
  listUserWebhooks(
    params: UserServiceListUserWebhooksParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof userServiceListUserWebhooks> {
    return userServiceListUserWebhooks(this._config, params, requestOptions);
  }
  /**
   * Creates a webhook for a user. Provide the destination `url` and, if needed, a `signingSecret` for HMAC-SHA256 signing; the secret is not included in the response. The `name` field uses the `users/{user}/webhooks/{webhook}` resource-name format.
   *
   * CreateUserWebhook creates a new webhook for a user.
   */
  createUserWebhook(
    params: UserServiceCreateUserWebhookParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof userServiceCreateUserWebhook> {
    return userServiceCreateUserWebhook(this._config, params, requestOptions);
  }
  /**
   * Deletes a webhook owned by a user. Identify the owner and the webhook to remove with the `user` and `webhook` path parameters.
   *
   * DeleteUserWebhook deletes a webhook for a user.
   */
  deleteUserWebhook(
    params: UserServiceDeleteUserWebhookParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof userServiceDeleteUserWebhook> {
    return userServiceDeleteUserWebhook(this._config, params, requestOptions);
  }
  /**
   * Updates an existing webhook for a user. Use `updateMask` to identify the fields to change, and provide a `signingSecret` when you need to set or change the secret used to sign webhook requests. The `name` field uses the `users/{user}/webhooks/{webhook}` resource-name format.
   *
   * UpdateUserWebhook updates an existing webhook for a user.
   */
  updateUserWebhook(
    params: UserServiceUpdateUserWebhookParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof userServiceUpdateUserWebhook> {
    return userServiceUpdateUserWebhook(this._config, params, requestOptions);
  }
  /**
   * Retrieves the signing secret for a user's webhook through an explicit, owner-gated call. Use this operation when you need the secret; it is not included in webhook list, create, or update responses.
   *
   * GetUserWebhookSigningSecret returns the signing secret for a webhook. The secret is returned only through this explicit, owner-gated call; it is never included in List/Create/Update responses.
   */
  getUserWebhookSigningSecret(
    params: UserServiceGetUserWebhookSigningSecretParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof userServiceGetUserWebhookSigningSecret> {
    return userServiceGetUserWebhookSigningSecret(this._config, params, requestOptions);
  }
  /**
   * Exports the authenticated user's memos as a ZIP archive, including comments, archived memos, and attachment files. The `user` path parameter must identify the authenticated user; the response body is the archive, and its media type is provided as `content_type`.
   *
   * ExportMemos writes every memo the user created, with comments, archived memos, and attachment files, as a Memos export file (a ZIP file, see docs/design/memos-export-format.md). Only the user may export their own memos. The body is the archive; content_type is its media type.
   */
  exportMemos(
    params: UserServiceExportMemosParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof userServiceExportMemos> {
    return userServiceExportMemos(this._config, params, requestOptions);
  }
  /**
   * Retrieves statistics for a specific user, including memo counts, tag counts, memo timestamps, and pinned memos. Use `filter` to select readable non-comment memos using a CEL expression compatible with ListMemos.
   *
   * GetUserStats returns statistics for a specific user.
   */
  getUserStats(
    params: UserServiceGetUserStatsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof userServiceGetUserStats> {
    return userServiceGetUserStats(this._config, params, requestOptions);
  }
  /**
   * Imports a Memos export archive into a user's memos through bounded chunk uploads. Start with `spec`, then use the returned `uploadId` for subsequent chunks; a finishing call can validate the archive without importing it or import it and return a report. Uploads are bound to the authenticated user and expire after 30 minutes of inactivity.
   *
   * ImportMemos uploads a Memos export file in bounded chunks and imports it into the user's memos. The first call carries the spec and returns an upload_id; later calls carry that upload_id. A finishing call with validate_only returns the plan and keeps the archive staged; a finishing call without it imports and returns the report. Uploads are bound to the authenticated user, expire after 30 minutes of inactivity, and do not survive a server restart.
   */
  importMemos(
    params: UserServiceImportMemosParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof userServiceImportMemos> {
    return userServiceImportMemos(this._config, params, requestOptions);
  }
  /**
   * Lists active users matching the supplied usernames. Provide `usernames` as an array of strings to identify the users to look up. The response contains the matching user records.
   *
   * BatchGetUsers returns active users by usernames.
   */
  batchGetUsers(
    params: UserServiceBatchGetUsersParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof userServiceBatchGetUsers> {
    return userServiceBatchGetUsers(this._config, params, requestOptions);
  }
  /**
   * Lists statistics for users, optionally scoped by memo state and filtered using the `ListMemos` filter syntax. `state` defaults to `NORMAL` and accepts `STATE_UNSPECIFIED`, `NORMAL`, or `ARCHIVED`.
   *
   * ListAllUserStats returns statistics for all users.
   */
  listAllUserStats(
    params: UserServiceListAllUserStatsParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof userServiceListAllUserStats> {
    return userServiceListAllUserStats(this._config, params, requestOptions);
  }
}
