// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { Status } from "../../types/shared";
import {
  GetUserWebhookSigningSecretResponse,
  ImportMemosRequest,
  ImportMemosResponse,
  ListMemoViewsResponse,
  ListUserSettingsResponse,
  ListUserWebhooksResponse,
  MemoView,
  UserSetting,
  UserStats,
  UserWebhook,
} from "../../types/user-service";
import type { ClientConfig, RequestOptions } from "../../client";
import { encodePathSegment, queryValue, sdkRequest } from "../../client";
import { validateDateTime } from "../../validation";

export type UserServiceListUserSettingsError = Status;

export interface UserServiceListUserSettingsParams {
  user: string;
  pageSize?: number;
  pageToken?: string;
}

/**
 * Lists settings for a user. Use `pageSize` to limit the number of settings returned and `pageToken` to continue from a previous page. The service returns at most 50 settings by default and coerces `pageSize` values above 1000 to 1000.
 *
 * ListUserSettings returns a list of user settings.
 *
 * @param user - The user id.
 * @param pageSize - Optional. The maximum number of settings to return. The
 *   service may return fewer than this value. If unspecified, at most 50 settings
 *   will be returned. The maximum value is 1000; values above 1000 will be coerced
 *   to 1000.
 * @param pageToken - Optional. A page token, received from a previous
 *   `ListUserSettings` call. Provide this to retrieve the subsequent page.
 */
export async function userServiceListUserSettings(
  config: ClientConfig,
  { user, pageSize, pageToken }: UserServiceListUserSettingsParams,
  requestOptions?: RequestOptions,
): Promise<ListUserSettingsResponse> {
  const _resp = await sdkRequest<ListUserSettingsResponse>({
    method: "GET",
    path: `/api/v1/users/${encodePathSegment(user)}/settings`,
    operationId: "userServiceListUserSettings",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      pageSize: queryValue(pageSize, "form", true),
      pageToken: queryValue(pageToken, "form", true),
    },
    config,
  });
  return _resp.data;
}

export type UserServiceGetUserSettingError = Status;

export interface UserServiceGetUserSettingParams {
  user: string;
  setting: string;
}

/**
 * Retrieves a specific setting for a user. Provide the user ID and setting key to identify the setting resource. The setting key appears in the resource name as `users/{user}/settings/{setting}`.
 *
 * GetUserSetting returns the user setting.
 *
 * @param user - The user id.
 * @param setting - The setting id.
 */
export async function userServiceGetUserSetting(
  config: ClientConfig,
  { user, setting }: UserServiceGetUserSettingParams,
  requestOptions?: RequestOptions,
): Promise<UserSetting> {
  const _resp = await sdkRequest<UserSetting>({
    method: "GET",
    path: `/api/v1/users/${encodePathSegment(user)}/settings/${encodePathSegment(setting)}`,
    operationId: "userServiceGetUserSetting",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type UserServiceUpdateUserSettingError = Status;

export type UserServiceUpdateUserSettingParams = UserSetting & {
  user: string;
  setting: string;
  updateMask?: string;
};

/**
 * Updates a user's setting. Supply the setting fields to change and use `updateMask` to specify which fields to update. The setting resource name follows the format `users/{user}/settings/{setting}`.
 *
 * UpdateUserSetting updates the user setting.
 *
 * @param user - The user id.
 * @param setting - The setting id.
 * @param updateMask - Required. The list of fields to update.
 * @param name - The name of the user setting. Format:
 *   users/{user}/settings/{setting}, {setting} is the key for the setting. For
 *   example, "users/steven/settings/GENERAL" for general settings.
 * @param generalSetting - General user settings configuration.
 * @param webhooksSetting - User webhooks configuration.
 * @param tagsSetting - User-specific tag metadata.
 */
export async function userServiceUpdateUserSetting(
  config: ClientConfig,
  {
    user,
    setting,
    updateMask,
    name,
    generalSetting,
    webhooksSetting,
    tagsSetting,
  }: UserServiceUpdateUserSettingParams,
  requestOptions?: RequestOptions,
): Promise<UserSetting> {
  const _resp = await sdkRequest<UserSetting>({
    method: "PATCH",
    path: `/api/v1/users/${encodePathSegment(user)}/settings/${encodePathSegment(setting)}`,
    operationId: "userServiceUpdateUserSetting",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      updateMask: queryValue(updateMask, "form", true),
    },
    body: {
      name,
      generalSetting,
      webhooksSetting,
      tagsSetting,
    },
    config,
  });
  return _resp.data;
}

export type UserServiceListMemoViewsError = Status;

export interface UserServiceListMemoViewsParams {
  user: string;
}

/**
 * Lists a user's saved memo views, each of which stores a reusable CEL filter. Use a view's `filter` value as the `filter` argument when listing memos. The list contains the saved views for the specified user.
 *
 * ListMemoViews returns a user's memo views. Each view is a named, reusable CEL filter (see MemoView.filter); pass its filter string directly to the ListMemos `filter` argument.
 *
 * @param user - The user id.
 */
export async function userServiceListMemoViews(
  config: ClientConfig,
  { user }: UserServiceListMemoViewsParams,
  requestOptions?: RequestOptions,
): Promise<ListMemoViewsResponse> {
  const _resp = await sdkRequest<ListMemoViewsResponse>({
    method: "GET",
    path: `/api/v1/users/${encodePathSegment(user)}/views`,
    operationId: "userServiceListMemoViews",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type UserServiceCreateMemoViewError = Status;

export type UserServiceCreateMemoViewParams = MemoView & {
  user: string;
  validateOnly?: boolean;
};

/**
 * Creates a saved memo view for a user. Provide the required `title` and CEL `filter` expression; you can optionally provide a display `icon`. Set `validateOnly` to validate the request without creating the view.
 *
 * CreateMemoView creates a new memo view for a user.
 *
 * @param user - The user id.
 * @param title - The title of the memo view.
 * @param filter - The CEL filter expression for the memo view, using the same
 *   grammar as the ListMemos `filter` argument. Reuse it by passing this value to
 *   ListMemos.
 * @param validateOnly - Optional. If set, validate the request, but do not
 *   actually create the memo view.
 * @param name - The resource name of the memo view. Format:
 *   users/{user}/views/{view}
 * @param icon - Optional. Display icon. Omit when updating with the "icon" mask
 *   to reset to the default view icon.
 */
export async function userServiceCreateMemoView(
  config: ClientConfig,
  { user, title, filter, validateOnly, name, icon }: UserServiceCreateMemoViewParams,
  requestOptions?: RequestOptions,
): Promise<MemoView> {
  const _resp = await sdkRequest<MemoView>({
    method: "POST",
    path: `/api/v1/users/${encodePathSegment(user)}/views`,
    operationId: "userServiceCreateMemoView",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      validateOnly: queryValue(validateOnly, "form", true),
    },
    body: {
      title,
      filter,
      name,
      icon,
    },
    config,
  });
  return _resp.data;
}

export type UserServiceGetMemoViewError = Status;

export interface UserServiceGetMemoViewParams {
  user: string;
  view: string;
}

/**
 * Retrieves a saved memo view by name. Provide the user ID and view ID to identify the view. The response includes the saved view's CEL filter, which you can pass to the ListMemos `filter` argument.
 *
 * GetMemoView gets a memo view by name.
 *
 * @param user - The user id.
 * @param view - The view id.
 */
export async function userServiceGetMemoView(
  config: ClientConfig,
  { user, view }: UserServiceGetMemoViewParams,
  requestOptions?: RequestOptions,
): Promise<MemoView> {
  const _resp = await sdkRequest<MemoView>({
    method: "GET",
    path: `/api/v1/users/${encodePathSegment(user)}/views/${encodePathSegment(view)}`,
    operationId: "userServiceGetMemoView",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type UserServiceDeleteMemoViewError = Status;

export interface UserServiceDeleteMemoViewParams {
  user: string;
  view: string;
}

/**
 * Deletes a saved memo view for a user. Identify the user and the view to remove with the `user` and `view` path parameters.
 *
 * DeleteMemoView deletes a memo view for a user.
 *
 * @param user - The user id.
 * @param view - The view id.
 */
export async function userServiceDeleteMemoView(
  config: ClientConfig,
  { user, view }: UserServiceDeleteMemoViewParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "DELETE",
    path: `/api/v1/users/${encodePathSegment(user)}/views/${encodePathSegment(view)}`,
    operationId: "userServiceDeleteMemoView",
    responseDecoder: "empty",
    ...requestOptions,
    config,
  });
  void _resp.data;
  return;
}

export type UserServiceUpdateMemoViewError = Status;

export type UserServiceUpdateMemoViewParams = MemoView & {
  user: string;
  view: string;
  updateMask?: string;
};

/**
 * Updates a saved memo view for a user. Supply `title` and `filter`; `filter` uses the CEL grammar accepted by ListMemos, and `updateMask` limits which fields change. Include `icon` in the update mask and omit its value to reset the view icon to the default.
 *
 * UpdateMemoView updates a memo view for a user.
 *
 * @param user - The user id.
 * @param view - The view id.
 * @param title - The title of the memo view.
 * @param filter - The CEL filter expression for the memo view, using the same
 *   grammar as the ListMemos `filter` argument. Reuse it by passing this value to
 *   ListMemos.
 * @param updateMask - Optional. The list of fields to update.
 * @param name - The resource name of the memo view. Format:
 *   users/{user}/views/{view}
 * @param icon - Optional. Display icon. Omit when updating with the "icon" mask
 *   to reset to the default view icon.
 */
export async function userServiceUpdateMemoView(
  config: ClientConfig,
  { user, view, title, filter, updateMask, name, icon }: UserServiceUpdateMemoViewParams,
  requestOptions?: RequestOptions,
): Promise<MemoView> {
  const _resp = await sdkRequest<MemoView>({
    method: "PATCH",
    path: `/api/v1/users/${encodePathSegment(user)}/views/${encodePathSegment(view)}`,
    operationId: "userServiceUpdateMemoView",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      updateMask: queryValue(updateMask, "form", true),
    },
    body: {
      title,
      filter,
      name,
      icon,
    },
    config,
  });
  return _resp.data;
}

export type UserServiceListUserWebhooksError = Status;

export interface UserServiceListUserWebhooksParams {
  user: string;
}

/**
 * Lists the webhooks owned by a user. Use the `user` path parameter to select whose webhooks to retrieve; the results include webhook configuration and whether a signing secret is set.
 *
 * ListUserWebhooks returns a list of webhooks for a user.
 *
 * @param user - The user id.
 */
export async function userServiceListUserWebhooks(
  config: ClientConfig,
  { user }: UserServiceListUserWebhooksParams,
  requestOptions?: RequestOptions,
): Promise<ListUserWebhooksResponse> {
  const _resp = await sdkRequest<ListUserWebhooksResponse>({
    method: "GET",
    path: `/api/v1/users/${encodePathSegment(user)}/webhooks`,
    operationId: "userServiceListUserWebhooks",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type UserServiceCreateUserWebhookError = Status;

export type UserServiceCreateUserWebhookParams = UserWebhook & {
  user: string;
};

/**
 * Creates a webhook for a user. Provide the destination `url` and, if needed, a `signingSecret` for HMAC-SHA256 signing; the secret is not included in the response. The `name` field uses the `users/{user}/webhooks/{webhook}` resource-name format.
 *
 * CreateUserWebhook creates a new webhook for a user.
 *
 * @param user - The user id.
 * @param name - The name of the webhook. Format: users/{user}/webhooks/{webhook}
 * @param url - The URL to send the webhook to.
 * @param displayName - Optional. Human-readable name for the webhook.
 * @param createTime - The creation time of the webhook.
 * @param updateTime - The last update time of the webhook.
 * @param signingSecret - Optional. Signing secret used to HMAC-SHA256 sign the
 *   webhook request body. This field is input-only; it is never returned in
 *   responses.
 * @param signingSecretSet - Whether a signing secret is configured for this
 *   webhook.
 */
export async function userServiceCreateUserWebhook(
  config: ClientConfig,
  {
    user,
    name,
    url,
    displayName,
    createTime,
    updateTime,
    signingSecret,
    signingSecretSet,
  }: UserServiceCreateUserWebhookParams,
  requestOptions?: RequestOptions,
): Promise<UserWebhook> {
  if (createTime != null) {
    validateDateTime("createTime", createTime);
  }

  if (updateTime != null) {
    validateDateTime("updateTime", updateTime);
  }

  const _resp = await sdkRequest<UserWebhook>({
    method: "POST",
    path: `/api/v1/users/${encodePathSegment(user)}/webhooks`,
    operationId: "userServiceCreateUserWebhook",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      name,
      url,
      displayName,
      createTime,
      updateTime,
      signingSecret,
      signingSecretSet,
    },
    config,
  });
  return _resp.data;
}

export type UserServiceDeleteUserWebhookError = Status;

export interface UserServiceDeleteUserWebhookParams {
  user: string;
  webhook: string;
}

/**
 * Deletes a webhook owned by a user. Identify the owner and the webhook to remove with the `user` and `webhook` path parameters.
 *
 * DeleteUserWebhook deletes a webhook for a user.
 *
 * @param user - The user id.
 * @param webhook - The webhook id.
 */
export async function userServiceDeleteUserWebhook(
  config: ClientConfig,
  { user, webhook }: UserServiceDeleteUserWebhookParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "DELETE",
    path: `/api/v1/users/${encodePathSegment(user)}/webhooks/${encodePathSegment(webhook)}`,
    operationId: "userServiceDeleteUserWebhook",
    responseDecoder: "empty",
    ...requestOptions,
    config,
  });
  void _resp.data;
  return;
}

export type UserServiceUpdateUserWebhookError = Status;

export type UserServiceUpdateUserWebhookParams = UserWebhook & {
  user: string;
  webhook: string;
  updateMask?: string;
};

/**
 * Updates an existing webhook for a user. Use `updateMask` to identify the fields to change, and provide a `signingSecret` when you need to set or change the secret used to sign webhook requests. The `name` field uses the `users/{user}/webhooks/{webhook}` resource-name format.
 *
 * UpdateUserWebhook updates an existing webhook for a user.
 *
 * @param user - The user id.
 * @param webhook - The webhook id.
 * @param updateMask - The list of fields to update.
 * @param name - The name of the webhook. Format: users/{user}/webhooks/{webhook}
 * @param url - The URL to send the webhook to.
 * @param displayName - Optional. Human-readable name for the webhook.
 * @param createTime - The creation time of the webhook.
 * @param updateTime - The last update time of the webhook.
 * @param signingSecret - Optional. Signing secret used to HMAC-SHA256 sign the
 *   webhook request body. This field is input-only; it is never returned in
 *   responses.
 * @param signingSecretSet - Whether a signing secret is configured for this
 *   webhook.
 */
export async function userServiceUpdateUserWebhook(
  config: ClientConfig,
  {
    user,
    webhook,
    updateMask,
    name,
    url,
    displayName,
    createTime,
    updateTime,
    signingSecret,
    signingSecretSet,
  }: UserServiceUpdateUserWebhookParams,
  requestOptions?: RequestOptions,
): Promise<UserWebhook> {
  if (createTime != null) {
    validateDateTime("createTime", createTime);
  }

  if (updateTime != null) {
    validateDateTime("updateTime", updateTime);
  }

  const _resp = await sdkRequest<UserWebhook>({
    method: "PATCH",
    path: `/api/v1/users/${encodePathSegment(user)}/webhooks/${encodePathSegment(webhook)}`,
    operationId: "userServiceUpdateUserWebhook",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      updateMask: queryValue(updateMask, "form", true),
    },
    body: {
      name,
      url,
      displayName,
      createTime,
      updateTime,
      signingSecret,
      signingSecretSet,
    },
    config,
  });
  return _resp.data;
}

export type UserServiceGetUserWebhookSigningSecretError = Status;

export interface UserServiceGetUserWebhookSigningSecretParams {
  user: string;
  webhook: string;
}

/**
 * Retrieves the signing secret for a user's webhook through an explicit, owner-gated call. Use this operation when you need the secret; it is not included in webhook list, create, or update responses.
 *
 * GetUserWebhookSigningSecret returns the signing secret for a webhook. The secret is returned only through this explicit, owner-gated call; it is never included in List/Create/Update responses.
 *
 * @param user - The user id.
 * @param webhook - The webhook id.
 */
export async function userServiceGetUserWebhookSigningSecret(
  config: ClientConfig,
  { user, webhook }: UserServiceGetUserWebhookSigningSecretParams,
  requestOptions?: RequestOptions,
): Promise<GetUserWebhookSigningSecretResponse> {
  const _resp = await sdkRequest<GetUserWebhookSigningSecretResponse>({
    method: "GET",
    path: `/api/v1/users/${encodePathSegment(user)}/webhooks/${encodePathSegment(webhook)}:getSigningSecret`,
    operationId: "userServiceGetUserWebhookSigningSecret",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type UserServiceExportMemosError = Status;

export interface UserServiceExportMemosParams {
  user: string;
}

/**
 * Exports the authenticated user's memos as a ZIP archive, including comments, archived memos, and attachment files. The `user` path parameter must identify the authenticated user; the response body is the archive, and its media type is provided as `content_type`.
 *
 * ExportMemos writes every memo the user created, with comments, archived memos, and attachment files, as a Memos export file (a ZIP file, see docs/design/memos-export-format.md). Only the user may export their own memos. The body is the archive; content_type is its media type.
 *
 * @param user - The user id.
 */
export async function userServiceExportMemos(
  config: ClientConfig,
  { user }: UserServiceExportMemosParams,
  requestOptions?: RequestOptions,
): Promise<unknown> {
  const _resp = await sdkRequest<unknown>({
    method: "GET",
    path: `/api/v1/users/${encodePathSegment(user)}:exportMemos`,
    operationId: "userServiceExportMemos",
    responseDecoder: "bytes",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type UserServiceGetUserStatsError = Status;

export interface UserServiceGetUserStatsParams {
  user: string;
  filter?: string;
}

/**
 * Retrieves statistics for a specific user, including memo counts, tag counts, memo timestamps, and pinned memos. Use `filter` to select readable non-comment memos using a CEL expression compatible with ListMemos.
 *
 * GetUserStats returns statistics for a specific user.
 *
 * @param user - The user id.
 * @param filter - Optional. CEL expression selecting the readable non-comment
 *   memos to include. Supports the same fields as ListMemos, including `space`.
 */
export async function userServiceGetUserStats(
  config: ClientConfig,
  { user, filter }: UserServiceGetUserStatsParams,
  requestOptions?: RequestOptions,
): Promise<UserStats> {
  const _resp = await sdkRequest<UserStats>({
    method: "GET",
    path: `/api/v1/users/${encodePathSegment(user)}:getStats`,
    operationId: "userServiceGetUserStats",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      filter: queryValue(filter, "form", true),
    },
    config,
  });
  return _resp.data;
}

export type UserServiceImportMemosError = Status;

export type UserServiceImportMemosParams = ImportMemosRequest & {
  user: string;
};

/**
 * Imports a Memos export archive into a user's memos through bounded chunk uploads. Start with `spec`, then use the returned `uploadId` for subsequent chunks; a finishing call can validate the archive without importing it or import it and return a report. Uploads are bound to the authenticated user and expire after 30 minutes of inactivity.
 *
 * ImportMemos uploads a Memos export file in bounded chunks and imports it into the user's memos. The first call carries the spec and returns an upload_id; later calls carry that upload_id. A finishing call with validate_only returns the plan and keeps the archive staged; a finishing call without it imports and returns the report. Uploads are bound to the authenticated user, expire after 30 minutes of inactivity, and do not survive a server restart.
 *
 * @param user - The user id.
 * @param name - Required. The user who receives the memos. Must be the caller.
 *   Format: users/{user}
 * @param writeOffset - Required. Zero-based byte offset at which data is
 *   written. Must equal the committed size, except when retrying the most recently
 *   accepted chunk with identical bytes and offset, which is accepted without
 *   writing again.
 * @param spec - Starts a new upload. The same call may also carry data and
 *   finish_write.
 * @param uploadId - Continues the upload identified by a previous response.
 * @param data - Optional. Archive bytes, at most max_chunk_size long. With no
 *   data and finish_write false, the call reports progress without writing, and
 *   write_offset is ignored.
 * @param finishWrite - Optional. Finish the upload after writing data. The
 *   committed size must then equal total_size. The archive is validated and,
 *   unless validate_only is set, imported. Any later call for an imported upload
 *   returns the same report.
 * @param validateOnly - Optional. On a finishing call, validate the archive and
 *   return the plan without importing. The upload stays staged so a later
 *   finishing call can import it.
 * @param conflictPolicy - Optional. Read on the finishing call that imports.
 *   Unspecified means SKIP.
 */
export async function userServiceImportMemos(
  config: ClientConfig,
  {
    user,
    name,
    writeOffset,
    spec,
    uploadId,
    data,
    finishWrite,
    validateOnly,
    conflictPolicy,
  }: UserServiceImportMemosParams,
  requestOptions?: RequestOptions,
): Promise<ImportMemosResponse> {
  const _resp = await sdkRequest<ImportMemosResponse>({
    method: "POST",
    path: `/api/v1/users/${encodePathSegment(user)}:importMemos`,
    operationId: "userServiceImportMemos",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      name,
      writeOffset,
      spec,
      uploadId,
      data,
      finishWrite,
      validateOnly,
      conflictPolicy,
    },
    config,
  });
  return _resp.data;
}
