// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import {
  CreateLinkedIdentityRequest,
  CreatePersonalAccessTokenRequest,
  CreatePersonalAccessTokenResponse,
  LinkedIdentity,
  ListLinkedIdentitiesResponse,
  ListPersonalAccessTokensResponse,
  ListUserNotificationsResponse,
  ListUsersResponse,
  UserNotification,
} from "../../types/user-service";
import { Status, User } from "../../types/shared";
import type { ClientConfig, RequestOptions } from "../../client";
import { encodePathSegment, queryValue, sdkRequest } from "../../client";
import { validateDateTime } from "../../validation";

export type UserServiceListUsersError = Status;

export interface UserServiceListUsersParams {
  pageSize?: number;
  pageToken?: string;
  filter?: string;
  showDeleted?: boolean;
}

/**
 * Lists users on the instance, with optional filtering and inclusion of deleted users. Use `pageToken` to continue through results; `pageSize` defaults to at most 50 and values above 1000 are coerced to 1000.
 *
 * ListUsers returns a list of users.
 *
 * @param pageSize - Optional. The maximum number of users to return. The service
 *   may return fewer than this value. If unspecified, at most 50 users will be
 *   returned. The maximum value is 1000; values above 1000 will be coerced to
 *   1000.
 * @param pageToken - Optional. A page token, received from a previous
 *   `ListUsers` call. Provide this to retrieve the subsequent page.
 * @param filter - Optional. Filter to apply to the list results. Example:
 *   "username == 'steven'" Supported operators: == Supported fields: username
 * @param showDeleted - Optional. If true, show deleted users in the response.
 */
export async function userServiceListUsers(
  config: ClientConfig,
  { pageSize, pageToken, filter, showDeleted }: UserServiceListUsersParams = {},
  requestOptions?: RequestOptions,
): Promise<ListUsersResponse> {
  const _resp = await sdkRequest<ListUsersResponse>({
    method: "GET",
    path: `/api/v1/users`,
    operationId: "userServiceListUsers",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      pageSize: queryValue(pageSize, "form", true),
      pageToken: queryValue(pageToken, "form", true),
      filter: queryValue(filter, "form", true),
      showDeleted: queryValue(showDeleted, "form", true),
    },
    config,
  });
  return _resp.data;
}

export type UserServiceCreateUserError = Status;

export type UserServiceCreateUserParams = User & {
  userId?: string;
  validateOnly?: boolean;
  requestId?: string;
};

/**
 * Creates a user with a username, role, and state, along with any optional profile details. Set `validateOnly` to validate the request without creating the user, or pass `requestId` to make repeated creation requests idempotent.
 *
 * CreateUser creates a new user.
 *
 * @param role - The role of the user.
 * @param username - Required. The unique username for login.
 * @param state - The state of the user.
 * @param userId - Optional. The resource ID to use for this user. If set, it
 *   must equal user.username and follow the username format. Format:
 *   ^[a-zA-Z0-9]([a-zA-Z0-9-]{0,34}[a-zA-Z0-9])?$
 * @param validateOnly - Optional. If set, validate the request but don't
 *   actually create the user.
 * @param requestId - Optional. An idempotency token that can be used to ensure
 *   that multiple requests to create a user have the same result.
 * @param name - The resource name of the user. Format: users/{user}
 * @param email - Optional. The email address of the user. Stored trimmed and
 *   lowercased; empty means no address. An address belongs to at most one user on
 *   the instance, so writes that would reuse one fail with ALREADY_EXISTS.
 * @param displayName - Optional. The display name of the user.
 * @param avatarUrl - Optional. The avatar URL of the user.
 * @param description - Optional. The description of the user.
 * @param password - Input only. The password for the user.
 * @param createTime - Output only. The creation timestamp.
 * @param updateTime - Output only. The last update timestamp.
 */
export async function userServiceCreateUser(
  config: ClientConfig,
  {
    role,
    username,
    state,
    userId,
    validateOnly,
    requestId,
    name,
    email,
    displayName,
    avatarUrl,
    description,
    password,
    createTime,
    updateTime,
  }: UserServiceCreateUserParams,
  requestOptions?: RequestOptions,
): Promise<User> {
  if (createTime != null) {
    validateDateTime("createTime", createTime);
  }

  if (updateTime != null) {
    validateDateTime("updateTime", updateTime);
  }

  const _resp = await sdkRequest<User>({
    method: "POST",
    path: `/api/v1/users`,
    operationId: "userServiceCreateUser",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      userId: queryValue(userId, "form", true),
      validateOnly: queryValue(validateOnly, "form", true),
      requestId: queryValue(requestId, "form", true),
    },
    body: {
      role,
      username,
      state,
      name,
      email,
      displayName,
      avatarUrl,
      description,
      password,
      createTime,
      updateTime,
    },
    config,
  });
  return _resp.data;
}

export type UserServiceGetUserError = Status;

export interface UserServiceGetUserParams {
  user: string;
  readMask?: string;
}

/**
 * Retrieves a user by username. Use the `user` resource name in the format `users/{user}`; specify `readMask` to limit the fields in the response, or omit it to receive all fields.
 *
 * GetUser gets a user by username. Format: users/{user} (e.g., users/steven)
 *
 * @param user - The user id.
 * @param readMask - Optional. The fields to return in the response. If not
 *   specified, all fields are returned.
 */
export async function userServiceGetUser(
  config: ClientConfig,
  { user, readMask }: UserServiceGetUserParams,
  requestOptions?: RequestOptions,
): Promise<User> {
  const _resp = await sdkRequest<User>({
    method: "GET",
    path: `/api/v1/users/${encodePathSegment(user)}`,
    operationId: "userServiceGetUser",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      readMask: queryValue(readMask, "form", true),
    },
    config,
  });
  return _resp.data;
}

export type UserServiceDeleteUserError = Status;

export interface UserServiceDeleteUserParams {
  user: string;
  force?: boolean;
}

/**
 * Deletes a user. Set `force` to true to delete the user even when associated data exists; otherwise, the user is deleted without that override.
 *
 * DeleteUser deletes a user.
 *
 * @param user - The user id.
 * @param force - Optional. If set to true, the user will be deleted even if they
 *   have associated data.
 */
export async function userServiceDeleteUser(
  config: ClientConfig,
  { user, force }: UserServiceDeleteUserParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "DELETE",
    path: `/api/v1/users/${encodePathSegment(user)}`,
    operationId: "userServiceDeleteUser",
    responseDecoder: "empty",
    ...requestOptions,
    query: {
      force: queryValue(force, "form", true),
    },
    config,
  });
  void _resp.data;
  return;
}

export type UserServiceUpdateUserError = Status;

export type UserServiceUpdateUserParams = User & {
  user: string;
  updateMask?: string;
  allowMissing?: boolean;
};

/**
 * Updates a user's fields using a partial update. Supply the user resource name and an `updateMask` to select the fields being updated; the request body schema requires `role`, `username`, and `state`.
 *
 * UpdateUser updates a user.
 *
 * @param user - The user id.
 * @param role - The role of the user.
 * @param username - Required. The unique username for login.
 * @param state - The state of the user.
 * @param updateMask - Required. The list of fields to update.
 * @param allowMissing - Optional. If set to true, allows updating sensitive
 *   fields.
 * @param name - The resource name of the user. Format: users/{user}
 * @param email - Optional. The email address of the user. Stored trimmed and
 *   lowercased; empty means no address. An address belongs to at most one user on
 *   the instance, so writes that would reuse one fail with ALREADY_EXISTS.
 * @param displayName - Optional. The display name of the user.
 * @param avatarUrl - Optional. The avatar URL of the user.
 * @param description - Optional. The description of the user.
 * @param password - Input only. The password for the user.
 * @param createTime - Output only. The creation timestamp.
 * @param updateTime - Output only. The last update timestamp.
 */
export async function userServiceUpdateUser(
  config: ClientConfig,
  {
    user,
    role,
    username,
    state,
    updateMask,
    allowMissing,
    name,
    email,
    displayName,
    avatarUrl,
    description,
    password,
    createTime,
    updateTime,
  }: UserServiceUpdateUserParams,
  requestOptions?: RequestOptions,
): Promise<User> {
  if (createTime != null) {
    validateDateTime("createTime", createTime);
  }

  if (updateTime != null) {
    validateDateTime("updateTime", updateTime);
  }

  const _resp = await sdkRequest<User>({
    method: "PATCH",
    path: `/api/v1/users/${encodePathSegment(user)}`,
    operationId: "userServiceUpdateUser",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      updateMask: queryValue(updateMask, "form", true),
      allowMissing: queryValue(allowMissing, "form", true),
    },
    body: {
      role,
      username,
      state,
      name,
      email,
      displayName,
      avatarUrl,
      description,
      password,
      createTime,
      updateTime,
    },
    config,
  });
  return _resp.data;
}

export type UserServiceListLinkedIdentitiesError = Status;

export interface UserServiceListLinkedIdentitiesParams {
  user: string;
}

/**
 * Lists the linked SSO identities for a user. Supply the user's identifier to retrieve the identities associated with that account.
 *
 * ListLinkedIdentities returns a list of linked SSO identities for a user.
 *
 * @param user - The user id.
 */
export async function userServiceListLinkedIdentities(
  config: ClientConfig,
  { user }: UserServiceListLinkedIdentitiesParams,
  requestOptions?: RequestOptions,
): Promise<ListLinkedIdentitiesResponse> {
  const _resp = await sdkRequest<ListLinkedIdentitiesResponse>({
    method: "GET",
    path: `/api/v1/users/${encodePathSegment(user)}/linkedIdentities`,
    operationId: "userServiceListLinkedIdentities",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type UserServiceCreateLinkedIdentityError = Status;

export type UserServiceCreateLinkedIdentityParams = CreateLinkedIdentityRequest & {
  user: string;
};

/**
 * Links an SSO identity to a user through an identity provider's OAuth flow. Provide the parent user, identity provider, authorization code, and redirect URI; include `codeVerifier` when the flow uses PKCE.
 *
 * CreateLinkedIdentity links an SSO identity to the authenticated user.
 *
 * @param user - The user id.
 * @param parent - Required. The parent user who owns the linked identity.
 *   Format: users/{user}
 * @param idpName - Required. The identity provider to link. Format:
 *   identity-providers/{idp}
 * @param code - Required. The authorization code from the identity provider.
 * @param redirectUri - Required. The redirect URI used in the OAuth flow.
 * @param codeVerifier - Optional. The PKCE code verifier used in the OAuth flow.
 */
export async function userServiceCreateLinkedIdentity(
  config: ClientConfig,
  { user, parent, idpName, code, redirectUri, codeVerifier }: UserServiceCreateLinkedIdentityParams,
  requestOptions?: RequestOptions,
): Promise<LinkedIdentity> {
  const _resp = await sdkRequest<LinkedIdentity>({
    method: "POST",
    path: `/api/v1/users/${encodePathSegment(user)}/linkedIdentities`,
    operationId: "userServiceCreateLinkedIdentity",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      parent,
      idpName,
      code,
      redirectUri,
      codeVerifier,
    },
    config,
  });
  return _resp.data;
}

export type UserServiceGetLinkedIdentityError = Status;

export interface UserServiceGetLinkedIdentityParams {
  user: string;
  linkedIdentity: string;
}

/**
 * Retrieves a linked SSO identity for a user. Supply both resource identifiers to retrieve the identity associated with that user account.
 *
 * GetLinkedIdentity gets a linked SSO identity for a user.
 *
 * @param user - The user id.
 * @param linkedIdentity - The linkedIdentity id.
 */
export async function userServiceGetLinkedIdentity(
  config: ClientConfig,
  { user, linkedIdentity }: UserServiceGetLinkedIdentityParams,
  requestOptions?: RequestOptions,
): Promise<LinkedIdentity> {
  const _resp = await sdkRequest<LinkedIdentity>({
    method: "GET",
    path: `/api/v1/users/${encodePathSegment(user)}/linkedIdentities/${encodePathSegment(linkedIdentity)}`,
    operationId: "userServiceGetLinkedIdentity",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type UserServiceDeleteLinkedIdentityError = Status;

export interface UserServiceDeleteLinkedIdentityParams {
  user: string;
  linkedIdentity: string;
}

/**
 * Deletes a linked SSO identity from a user account. Supply the user and linked identity identifiers for the identity you want to unlink.
 *
 * DeleteLinkedIdentity unlinks an SSO identity from a user.
 *
 * @param user - The user id.
 * @param linkedIdentity - The linkedIdentity id.
 */
export async function userServiceDeleteLinkedIdentity(
  config: ClientConfig,
  { user, linkedIdentity }: UserServiceDeleteLinkedIdentityParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "DELETE",
    path: `/api/v1/users/${encodePathSegment(user)}/linkedIdentities/${encodePathSegment(linkedIdentity)}`,
    operationId: "userServiceDeleteLinkedIdentity",
    responseDecoder: "empty",
    ...requestOptions,
    config,
  });
  void _resp.data;
  return;
}

export type UserServiceListUserNotificationsError = Status;

export interface UserServiceListUserNotificationsParams {
  user: string;
  pageSize?: number;
  pageToken?: string;
  filter?: string;
}

/**
 * Lists notifications for a user. Use `pageSize` to control the number of results and `pageToken` to continue through paginated results; optionally use `filter` to narrow the list.
 *
 * ListUserNotifications lists notifications for a user.
 *
 * @param user - The user id.
 */
export async function userServiceListUserNotifications(
  config: ClientConfig,
  { user, pageSize, pageToken, filter }: UserServiceListUserNotificationsParams,
  requestOptions?: RequestOptions,
): Promise<ListUserNotificationsResponse> {
  const _resp = await sdkRequest<ListUserNotificationsResponse>({
    method: "GET",
    path: `/api/v1/users/${encodePathSegment(user)}/notifications`,
    operationId: "userServiceListUserNotifications",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      pageSize: queryValue(pageSize, "form", true),
      pageToken: queryValue(pageToken, "form", true),
      filter: queryValue(filter, "form", true),
    },
    config,
  });
  return _resp.data;
}

export type UserServiceDeleteUserNotificationError = Status;

export interface UserServiceDeleteUserNotificationParams {
  user: string;
  notification: string;
}

/**
 * Deletes a notification from a user's notification list. Supply the user and notification identifiers for the notification you want to delete.
 *
 * DeleteUserNotification deletes a notification.
 *
 * @param user - The user id.
 * @param notification - The notification id.
 */
export async function userServiceDeleteUserNotification(
  config: ClientConfig,
  { user, notification }: UserServiceDeleteUserNotificationParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "DELETE",
    path: `/api/v1/users/${encodePathSegment(user)}/notifications/${encodePathSegment(notification)}`,
    operationId: "userServiceDeleteUserNotification",
    responseDecoder: "empty",
    ...requestOptions,
    config,
  });
  void _resp.data;
  return;
}

export type UserServiceUpdateUserNotificationError = Status;

export type UserServiceUpdateUserNotificationParams = UserNotification & {
  user: string;
  notification: string;
  updateMask?: string;
};

/**
 * Updates a user's notification. Use `updateMask` to select the fields to change; the request body schema exposes `status` as an editable field, while the other defined fields are read-only.
 *
 * UpdateUserNotification updates a notification.
 *
 * @param user - The user id.
 * @param notification - The notification id.
 * @param name - The resource name of the notification. Format:
 *   users/{user}/notifications/{notification}
 * @param sender - The sender of the notification. Format: users/{user}
 * @param senderUser - The sender user details.
 * @param status - The status of the notification.
 * @param createTime - The creation timestamp.
 * @param type_ - The type of the notification.
 * @param memoComment - Optional API value serialized in the `memoComment` wire
 *   field.
 * @param memoMention - Optional API value serialized in the `memoMention` wire
 *   field.
 * @param spaceInvitation - Optional API value serialized in the
 *   `spaceInvitation` wire field.
 */
export async function userServiceUpdateUserNotification(
  config: ClientConfig,
  {
    user,
    notification,
    updateMask,
    name,
    sender,
    senderUser,
    status,
    createTime,
    type: type_,
    memoComment,
    memoMention,
    spaceInvitation,
  }: UserServiceUpdateUserNotificationParams,
  requestOptions?: RequestOptions,
): Promise<UserNotification> {
  if (createTime != null) {
    validateDateTime("createTime", createTime);
  }

  const _resp = await sdkRequest<UserNotification>({
    method: "PATCH",
    path: `/api/v1/users/${encodePathSegment(user)}/notifications/${encodePathSegment(notification)}`,
    operationId: "userServiceUpdateUserNotification",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      updateMask: queryValue(updateMask, "form", true),
    },
    body: {
      name,
      sender,
      senderUser,
      status,
      createTime,
      ["type"]: type_,
      memoComment,
      memoMention,
      spaceInvitation,
    },
    config,
  });
  return _resp.data;
}

export type UserServiceListPersonalAccessTokensError = Status;

export interface UserServiceListPersonalAccessTokensParams {
  user: string;
  pageSize?: number;
  pageToken?: string;
}

/**
 * Lists long-lived personal access tokens (PATs) for a user. Use `pageSize` and `pageToken` to retrieve results in pages; PATs provide API and script access and are distinct from short-lived JWTs used for session authentication.
 *
 * ListPersonalAccessTokens returns a list of Personal Access Tokens (PATs) for a user. PATs are long-lived tokens for API/script access, distinct from short-lived JWT access tokens.
 *
 * @param user - The user id.
 * @param pageSize - Optional. The maximum number of tokens to return.
 * @param pageToken - Optional. A page token for pagination.
 */
export async function userServiceListPersonalAccessTokens(
  config: ClientConfig,
  { user, pageSize, pageToken }: UserServiceListPersonalAccessTokensParams,
  requestOptions?: RequestOptions,
): Promise<ListPersonalAccessTokensResponse> {
  const _resp = await sdkRequest<ListPersonalAccessTokensResponse>({
    method: "GET",
    path: `/api/v1/users/${encodePathSegment(user)}/personalAccessTokens`,
    operationId: "userServiceListPersonalAccessTokens",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      pageSize: queryValue(pageSize, "form", true),
      pageToken: queryValue(pageToken, "form", true),
    },
    config,
  });
  return _resp.data;
}

export type UserServiceCreatePersonalAccessTokenError = Status;

export type UserServiceCreatePersonalAccessTokenParams = CreatePersonalAccessTokenRequest & {
  user: string;
};

/**
 * Creates a long-lived personal access token for a user. Supply the required `parent` resource name in the format `users/{user}`; you can optionally provide a `description` and an `expiresInDays` value. The token value is returned only when you create the token, so store it securely at that time.
 *
 * CreatePersonalAccessToken creates a new Personal Access Token for a user. The token value is only returned once upon creation.
 *
 * @param user - The user id.
 * @param parent - Required. The parent resource where this token will be
 *   created. Format: users/{user}
 * @param description - Optional. Description of the personal access token.
 * @param expiresInDays - Optional. Expiration duration in days (0 = never
 *   expires).
 */
export async function userServiceCreatePersonalAccessToken(
  config: ClientConfig,
  { user, parent, description, expiresInDays }: UserServiceCreatePersonalAccessTokenParams,
  requestOptions?: RequestOptions,
): Promise<CreatePersonalAccessTokenResponse> {
  const _resp = await sdkRequest<CreatePersonalAccessTokenResponse>({
    method: "POST",
    path: `/api/v1/users/${encodePathSegment(user)}/personalAccessTokens`,
    operationId: "userServiceCreatePersonalAccessToken",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      parent,
      description,
      expiresInDays,
    },
    config,
  });
  return _resp.data;
}

export type UserServiceDeletePersonalAccessTokenError = Status;

export interface UserServiceDeletePersonalAccessTokenParams {
  user: string;
  personalAccessToken: string;
}

/**
 * Deletes a personal access token. Provide the user and token identifiers to specify which PAT to delete. The token is a long-lived credential for API or script access.
 *
 * DeletePersonalAccessToken deletes a Personal Access Token.
 *
 * @param user - The user id.
 * @param personalAccessToken - The personalAccessToken id.
 */
export async function userServiceDeletePersonalAccessToken(
  config: ClientConfig,
  { user, personalAccessToken }: UserServiceDeletePersonalAccessTokenParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "DELETE",
    path: `/api/v1/users/${encodePathSegment(user)}/personalAccessTokens/${encodePathSegment(personalAccessToken)}`,
    operationId: "userServiceDeletePersonalAccessToken",
    responseDecoder: "empty",
    ...requestOptions,
    config,
  });
  void _resp.data;
  return;
}
