// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { Status } from "../../types/shared";
import {
  BatchGetUsersRequest,
  BatchGetUsersResponse,
  ListAllUserStatsResponse,
} from "../../types/user-service";
import type { ClientConfig, RequestOptions } from "../../client";
import { queryValue, sdkRequest } from "../../client";

export type UserServiceBatchGetUsersError = Status;

export type UserServiceBatchGetUsersParams = BatchGetUsersRequest;

/**
 * Lists active users matching the supplied usernames. Provide `usernames` as an array of strings to identify the users to look up. The response contains the matching user records.
 *
 * BatchGetUsers returns active users by usernames.
 *
 * @param usernames - Optional array value serialized in the `usernames` wire
 *   field.
 */
export async function userServiceBatchGetUsers(
  config: ClientConfig,
  { usernames }: UserServiceBatchGetUsersParams = {},
  requestOptions?: RequestOptions,
): Promise<BatchGetUsersResponse> {
  const _resp = await sdkRequest<BatchGetUsersResponse>({
    method: "POST",
    path: `/api/v1/users:batchGet`,
    operationId: "userServiceBatchGetUsers",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      usernames,
    },
    config,
  });
  return _resp.data;
}

export type UserServiceListAllUserStatsError = Status;

export interface UserServiceListAllUserStatsParams {
  state?: "STATE_UNSPECIFIED" | "NORMAL" | "ARCHIVED" | (string & {});
  filter?: string;
}

/**
 * Lists statistics for users, optionally scoped by memo state and filtered using the `ListMemos` filter syntax. `state` defaults to `NORMAL` and accepts `STATE_UNSPECIFIED`, `NORMAL`, or `ARCHIVED`.
 *
 * ListAllUserStats returns statistics for all users.
 *
 * @param state - Optional. The state of memos to include. Defaults to NORMAL.
 * @param filter - Optional. Filter to apply to memo stats. Uses the same filter
 *   syntax as ListMemos.
 */
export async function userServiceListAllUserStats(
  config: ClientConfig,
  { state, filter }: UserServiceListAllUserStatsParams = {},
  requestOptions?: RequestOptions,
): Promise<ListAllUserStatsResponse> {
  const _resp = await sdkRequest<ListAllUserStatsResponse>({
    method: "GET",
    path: `/api/v1/users:stats`,
    operationId: "userServiceListAllUserStats",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      state: queryValue(state, "form", true),
      filter: queryValue(filter, "form", true),
    },
    config,
  });
  return _resp.data;
}
