// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import {
  BatchGetLinkMetadataRequest,
  BatchGetLinkMetadataResponse,
  LinkMetadata,
  ListMemoAttachmentsResponse,
  ListMemoCommentsResponse,
  ListMemoReactionsResponse,
  ListMemosResponse,
  Memo,
  Reaction,
  SetMemoAttachmentsRequest,
  UpsertMemoReactionRequest,
} from "../../types/memo-service";
import { Status } from "../../types/shared";
import type { ClientConfig, RequestOptions } from "../../client";
import { encodePathSegment, queryValue, sdkRequest } from "../../client";
import { validateDateTime } from "../../validation";

export type MemoServiceListMemosError = Status;

export interface MemoServiceListMemosParams {
  pageSize?: number;
  pageToken?: string;
  state?: "STATE_UNSPECIFIED" | "NORMAL" | "ARCHIVED" | (string & {});
  orderBy?: string;
  filter?: string;
  showDeleted?: boolean;
}

/**
 * Lists readable, non-comment memos, with support for pagination, filtering, and sorting. Use `filter` to select memos and `orderBy` to control their order; `pageToken` continues a listing from a previous response.
 *
 * ListMemos lists readable non-comment memos with pagination and filter.
 *
 * @param pageSize - Optional. The maximum number of memos to return. The service
 *   may return fewer than this value. If unspecified, at most 50 memos will be
 *   returned. The maximum value is 1000; values above 1000 will be coerced to
 *   1000.
 * @param pageToken - Optional. A page token, received from a previous
 *   `ListMemos` call. Provide this to retrieve the subsequent page.
 * @param state - Optional. The state of the memos to list. Default to `NORMAL`.
 *   Set to `ARCHIVED` to list archived memos.
 * @param orderBy - Optional. The order to sort results by. Default to
 *   "create_time desc". Supports comma-separated list of fields following AIP-132.
 *   Example: "pinned desc, create_time desc" or "update_time asc" Supported
 *   fields: pinned, create_time, update_time, name. Note: order_by uses
 *   create_time / update_time, while the filter expression uses created_ts /
 *   updated_ts for the same timestamps.
 * @param filter - Optional. A CEL expression to filter memos. Combine terms with
 *   && and ||. Available fields: content (string), creator (string, e.g.
 *   "users/1"), created_ts / updated_ts (timestamp), pinned (bool), visibility
 *   (string: PRIVATE | PROTECTED | PUBLIC | SPACE), space (string resource name,
 *   or null when the memo has no space; supports == and comparisons against null,
 *   e.g. space != null), tags (list<string>; match with `"work" in tags`, not `tag
 *   == "work"`), has_task_list / has_link / has_code / has_incomplete_tasks
 *   (bool), has_location (bool; true when the memo has a location attached). Note:
 *   the time fields here are created_ts / updated_ts, which differ from the
 *   create_time / update_time names used by order_by. Examples: pinned == true &&
 *   visibility == "PUBLIC" space == "spaces/team" or space == null tags.exists(t,
 *   t == "urgent") content.contains("roadmap") && created_ts > now -
 *   duration("168h")
 * @param showDeleted - Optional. If true, show deleted memos in the response.
 */
export async function memoServiceListMemos(
  config: ClientConfig,
  { pageSize, pageToken, state, orderBy, filter, showDeleted }: MemoServiceListMemosParams = {},
  requestOptions?: RequestOptions,
): Promise<ListMemosResponse> {
  const _resp = await sdkRequest<ListMemosResponse>({
    method: "GET",
    path: `/api/v1/memos`,
    operationId: "memoServiceListMemos",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      pageSize: queryValue(pageSize, "form", true),
      pageToken: queryValue(pageToken, "form", true),
      state: queryValue(state, "form", true),
      orderBy: queryValue(orderBy, "form", true),
      filter: queryValue(filter, "form", true),
      showDeleted: queryValue(showDeleted, "form", true),
    },
    config,
  });
  return _resp.data;
}

export type MemoServiceCreateMemoError = Status;

export type MemoServiceCreateMemoParams = Memo & {
  memoId?: string;
};

/**
 * Creates a memo owned by the authenticated user. Supply `content` in Markdown and choose a `visibility`; visibility defaults to PRIVATE when omitted. You must authenticate to create a memo.
 *
 * CreateMemo creates a memo. The request body is a Memo; set its content (Markdown) and visibility (PRIVATE | PROTECTED | PUBLIC | SPACE, default PRIVATE). The memo is owned by the authenticated user; requires authentication.
 *
 * @param state - The state of the memo.
 * @param content - Required. The content of the memo in Markdown format.
 * @param visibility - The visibility of the memo. One of PRIVATE (creator only),
 *   PROTECTED (signed-in users), PUBLIC (anonymous-eligible), or SPACE (active
 *   space members). Defaults to PRIVATE on creation when unspecified.
 * @param memoId - Optional. The memo ID to use for this memo. If empty, a unique
 *   ID will be generated. Format: ^[a-zA-Z0-9]([a-zA-Z0-9-]{0,34}[a-zA-Z0-9])?$
 * @param name - The resource name of the memo. Format: memos/{memo}, where memo
 *   is the user-defined UID.
 * @param creator - The name of the creator. Format: users/{user}
 * @param createTime - The creation timestamp. If not set on creation, the server
 *   will set it to the current time.
 * @param updateTime - The last update timestamp. If not set on creation, the
 *   server will set it to the current time.
 * @param tags - Output only. The tags extracted from the content.
 * @param pinned - Whether the memo is pinned.
 * @param attachments - Optional. The attachments of the memo.
 * @param relations - Optional. The relations of the memo.
 * @param reactions - Output only. The reactions to the memo.
 * @param property - Output only. The computed properties of the memo.
 * @param parent - Output only. The context memo of this COMMENT relation, if
 *   any. Its identity is returned even when the caller cannot read the parent.
 *   Fetch the parent independently; this field does not grant read access. Format:
 *   memos/{memo}
 * @param snippet - Output only. The snippet of the memo content. Plain text
 *   only.
 * @param location - Optional. The location of the memo.
 * @param space - Optional. The space in which this memo is placed. Format:
 *   spaces/{space}. Every memo, including a comment, owns its placement
 *   independently.
 */
export async function memoServiceCreateMemo(
  config: ClientConfig,
  {
    state,
    content,
    visibility,
    memoId,
    name,
    creator,
    createTime,
    updateTime,
    tags,
    pinned,
    attachments,
    relations,
    reactions,
    property,
    parent,
    snippet,
    location,
    space,
  }: MemoServiceCreateMemoParams,
  requestOptions?: RequestOptions,
): Promise<Memo> {
  if (createTime != null) {
    validateDateTime("createTime", createTime);
  }

  if (updateTime != null) {
    validateDateTime("updateTime", updateTime);
  }

  const _resp = await sdkRequest<Memo>({
    method: "POST",
    path: `/api/v1/memos`,
    operationId: "memoServiceCreateMemo",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      memoId: queryValue(memoId, "form", true),
    },
    body: {
      state,
      content,
      visibility,
      name,
      creator,
      createTime,
      updateTime,
      tags,
      pinned,
      attachments,
      relations,
      reactions,
      property,
      parent,
      snippet,
      location,
      space,
    },
    config,
  });
  return _resp.data;
}

export type MemoServiceGetLinkMetadataError = Status;

export interface MemoServiceGetLinkMetadataParams {
  url?: string;
}

/**
 * Retrieves metadata for a link. Provide the link's `url` to get its title, description, and image URL.
 *
 * GetLinkMetadata gets metadata for a link.
 *
 * @param url - Required. The link URL.
 */
export async function memoServiceGetLinkMetadata(
  config: ClientConfig,
  { url }: MemoServiceGetLinkMetadataParams = {},
  requestOptions?: RequestOptions,
): Promise<LinkMetadata> {
  const _resp = await sdkRequest<LinkMetadata>({
    method: "GET",
    path: `/api/v1/memos/-/linkMetadata`,
    operationId: "memoServiceGetLinkMetadata",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      url: queryValue(url, "form", true),
    },
    config,
  });
  return _resp.data;
}

export type MemoServiceBatchGetLinkMetadataError = Status;

export type MemoServiceBatchGetLinkMetadataParams = BatchGetLinkMetadataRequest;

/**
 * Retrieves metadata for multiple links in one request. Supply the link URLs in `urls`; the response preserves the input order.
 *
 * BatchGetLinkMetadata gets metadata for links.
 *
 * @param urls - Required. The link URLs.
 */
export async function memoServiceBatchGetLinkMetadata(
  config: ClientConfig,
  { urls }: MemoServiceBatchGetLinkMetadataParams,
  requestOptions?: RequestOptions,
): Promise<BatchGetLinkMetadataResponse> {
  const _resp = await sdkRequest<BatchGetLinkMetadataResponse>({
    method: "POST",
    path: `/api/v1/memos/-/linkMetadata:batchGet`,
    operationId: "memoServiceBatchGetLinkMetadata",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      urls,
    },
    config,
  });
  return _resp.data;
}

export type MemoServiceGetMemoError = Status;

export interface MemoServiceGetMemoParams {
  memo: string;
}

/**
 * Retrieves a memo by its identifier. Use the `memo` path parameter to specify which memo to retrieve.
 *
 * GetMemo gets a memo.
 *
 * @param memo - The memo id.
 */
export async function memoServiceGetMemo(
  config: ClientConfig,
  { memo }: MemoServiceGetMemoParams,
  requestOptions?: RequestOptions,
): Promise<Memo> {
  const _resp = await sdkRequest<Memo>({
    method: "GET",
    path: `/api/v1/memos/${encodePathSegment(memo)}`,
    operationId: "memoServiceGetMemo",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type MemoServiceDeleteMemoError = Status;

export interface MemoServiceDeleteMemoParams {
  memo: string;
  force?: boolean;
}

/**
 * Deletes the named memo and its owned resources without deleting other memos. Use `force` to delete the memo even when it has associated data; incident relations are removed.
 *
 * DeleteMemo deletes only the named memo and its owned resources. It removes incident relations but never deletes another memo.
 *
 * @param memo - The memo id.
 * @param force - Optional. If set to true, the memo will be deleted even if it
 *   has associated data.
 */
export async function memoServiceDeleteMemo(
  config: ClientConfig,
  { memo, force }: MemoServiceDeleteMemoParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "DELETE",
    path: `/api/v1/memos/${encodePathSegment(memo)}`,
    operationId: "memoServiceDeleteMemo",
    responseDecoder: "empty",
    ...requestOptions,
    query: {
      force: queryValue(force, "form", true),
    },
    config,
  });
  void _resp.data;
  return;
}

export type MemoServiceUpdateMemoError = Status;

export type MemoServiceUpdateMemoParams = Memo & {
  memo: string;
  updateMask?: string;
};

/**
 * Updates a memo with the fields supplied in the request body. Use `updateMask` to identify the fields to update; `state`, `content`, and `visibility` are required by the request schema.
 *
 * UpdateMemo updates a memo.
 *
 * @param memo - The memo id.
 * @param state - The state of the memo.
 * @param content - Required. The content of the memo in Markdown format.
 * @param visibility - The visibility of the memo. One of PRIVATE (creator only),
 *   PROTECTED (signed-in users), PUBLIC (anonymous-eligible), or SPACE (active
 *   space members). Defaults to PRIVATE on creation when unspecified.
 * @param updateMask - Required. The list of fields to update.
 * @param name - The resource name of the memo. Format: memos/{memo}, where memo
 *   is the user-defined UID.
 * @param creator - The name of the creator. Format: users/{user}
 * @param createTime - The creation timestamp. If not set on creation, the server
 *   will set it to the current time.
 * @param updateTime - The last update timestamp. If not set on creation, the
 *   server will set it to the current time.
 * @param tags - Output only. The tags extracted from the content.
 * @param pinned - Whether the memo is pinned.
 * @param attachments - Optional. The attachments of the memo.
 * @param relations - Optional. The relations of the memo.
 * @param reactions - Output only. The reactions to the memo.
 * @param property - Output only. The computed properties of the memo.
 * @param parent - Output only. The context memo of this COMMENT relation, if
 *   any. Its identity is returned even when the caller cannot read the parent.
 *   Fetch the parent independently; this field does not grant read access. Format:
 *   memos/{memo}
 * @param snippet - Output only. The snippet of the memo content. Plain text
 *   only.
 * @param location - Optional. The location of the memo.
 * @param space - Optional. The space in which this memo is placed. Format:
 *   spaces/{space}. Every memo, including a comment, owns its placement
 *   independently.
 */
export async function memoServiceUpdateMemo(
  config: ClientConfig,
  {
    memo,
    state,
    content,
    visibility,
    updateMask,
    name,
    creator,
    createTime,
    updateTime,
    tags,
    pinned,
    attachments,
    relations,
    reactions,
    property,
    parent,
    snippet,
    location,
    space,
  }: MemoServiceUpdateMemoParams,
  requestOptions?: RequestOptions,
): Promise<Memo> {
  if (createTime != null) {
    validateDateTime("createTime", createTime);
  }

  if (updateTime != null) {
    validateDateTime("updateTime", updateTime);
  }

  const _resp = await sdkRequest<Memo>({
    method: "PATCH",
    path: `/api/v1/memos/${encodePathSegment(memo)}`,
    operationId: "memoServiceUpdateMemo",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      updateMask: queryValue(updateMask, "form", true),
    },
    body: {
      state,
      content,
      visibility,
      name,
      creator,
      createTime,
      updateTime,
      tags,
      pinned,
      attachments,
      relations,
      reactions,
      property,
      parent,
      snippet,
      location,
      space,
    },
    config,
  });
  return _resp.data;
}

export type MemoServiceListMemoAttachmentsError = Status;

export interface MemoServiceListMemoAttachmentsParams {
  memo: string;
  pageSize?: number;
  pageToken?: string;
}

/**
 * Lists attachments associated with a specific memo. Use `pageSize` to limit the number of results and `pageToken` to continue through the results.
 *
 * ListMemoAttachments lists attachments for a memo.
 *
 * @param memo - The memo id.
 * @param pageSize - Optional. The maximum number of attachments to return.
 * @param pageToken - Optional. A page token for pagination.
 */
export async function memoServiceListMemoAttachments(
  config: ClientConfig,
  { memo, pageSize, pageToken }: MemoServiceListMemoAttachmentsParams,
  requestOptions?: RequestOptions,
): Promise<ListMemoAttachmentsResponse> {
  const _resp = await sdkRequest<ListMemoAttachmentsResponse>({
    method: "GET",
    path: `/api/v1/memos/${encodePathSegment(memo)}/attachments`,
    operationId: "memoServiceListMemoAttachments",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      pageSize: queryValue(pageSize, "form", true),
      pageToken: queryValue(pageToken, "form", true),
    },
    config,
  });
  return _resp.data;
}

export type MemoServiceSetMemoAttachmentsError = Status;

export type MemoServiceSetMemoAttachmentsParams = SetMemoAttachmentsRequest & {
  memo: string;
};

/**
 * Replaces the full set of attachments associated with a memo. Pass the complete desired list in `attachments`; an empty list clears the memo's attachments, and repeating the same request is idempotent.
 *
 * SetMemoAttachments replaces the full set of attachments on a memo with the provided list (not an append). Pass the complete desired set; an empty list clears all attachments. Idempotent.
 *
 * @param memo - The memo id.
 * @param name - Required. The resource name of the memo. Format: memos/{memo}
 * @param attachments - Required. The attachments to set for the memo.
 */
export async function memoServiceSetMemoAttachments(
  config: ClientConfig,
  { memo, name, attachments }: MemoServiceSetMemoAttachmentsParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "PATCH",
    path: `/api/v1/memos/${encodePathSegment(memo)}/attachments`,
    operationId: "memoServiceSetMemoAttachments",
    responseDecoder: "empty",
    ...requestOptions,
    body: {
      name,
      attachments,
    },
    config,
  });
  void _resp.data;
  return;
}

export type MemoServiceListMemoCommentsError = Status;

export interface MemoServiceListMemoCommentsParams {
  memo: string;
  pageSize?: number;
  pageToken?: string;
  orderBy?: string;
}

/**
 * Lists comments associated with a specific memo. Use `pageSize` and `pageToken` to control pagination, and `orderBy` to specify the result sort order.
 *
 * ListMemoComments lists comments for a memo.
 *
 * @param memo - The memo id.
 * @param pageSize - Optional. The maximum number of comments to return.
 * @param pageToken - Optional. A page token for pagination.
 * @param orderBy - Optional. The order to sort results by.
 */
export async function memoServiceListMemoComments(
  config: ClientConfig,
  { memo, pageSize, pageToken, orderBy }: MemoServiceListMemoCommentsParams,
  requestOptions?: RequestOptions,
): Promise<ListMemoCommentsResponse> {
  const _resp = await sdkRequest<ListMemoCommentsResponse>({
    method: "GET",
    path: `/api/v1/memos/${encodePathSegment(memo)}/comments`,
    operationId: "memoServiceListMemoComments",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      pageSize: queryValue(pageSize, "form", true),
      pageToken: queryValue(pageToken, "form", true),
      orderBy: queryValue(orderBy, "form", true),
    },
    config,
  });
  return _resp.data;
}

export type MemoServiceCreateMemoCommentError = Status;

export type MemoServiceCreateMemoCommentParams = Memo & {
  memo: string;
  commentId?: string;
};

/**
 * Creates an independent memo with an immutable COMMENT relation to the specified memo. Supply `state`, `content`, and `visibility`; the new memo retains its own placement, visibility, authorship, and lifecycle.
 *
 * CreateMemoComment atomically creates an independent memo plus one immutable COMMENT context relation to the named memo. The new memo keeps its own placement, visibility, authorship, and lifecycle.
 *
 * @param memo - The memo id.
 * @param state - The state of the memo.
 * @param content - Required. The content of the memo in Markdown format.
 * @param visibility - The visibility of the memo. One of PRIVATE (creator only),
 *   PROTECTED (signed-in users), PUBLIC (anonymous-eligible), or SPACE (active
 *   space members). Defaults to PRIVATE on creation when unspecified.
 * @param commentId - Optional. The comment ID to use.
 * @param name - The resource name of the memo. Format: memos/{memo}, where memo
 *   is the user-defined UID.
 * @param creator - The name of the creator. Format: users/{user}
 * @param createTime - The creation timestamp. If not set on creation, the server
 *   will set it to the current time.
 * @param updateTime - The last update timestamp. If not set on creation, the
 *   server will set it to the current time.
 * @param tags - Output only. The tags extracted from the content.
 * @param pinned - Whether the memo is pinned.
 * @param attachments - Optional. The attachments of the memo.
 * @param relations - Optional. The relations of the memo.
 * @param reactions - Output only. The reactions to the memo.
 * @param property - Output only. The computed properties of the memo.
 * @param parent - Output only. The context memo of this COMMENT relation, if
 *   any. Its identity is returned even when the caller cannot read the parent.
 *   Fetch the parent independently; this field does not grant read access. Format:
 *   memos/{memo}
 * @param snippet - Output only. The snippet of the memo content. Plain text
 *   only.
 * @param location - Optional. The location of the memo.
 * @param space - Optional. The space in which this memo is placed. Format:
 *   spaces/{space}. Every memo, including a comment, owns its placement
 *   independently.
 */
export async function memoServiceCreateMemoComment(
  config: ClientConfig,
  {
    memo,
    state,
    content,
    visibility,
    commentId,
    name,
    creator,
    createTime,
    updateTime,
    tags,
    pinned,
    attachments,
    relations,
    reactions,
    property,
    parent,
    snippet,
    location,
    space,
  }: MemoServiceCreateMemoCommentParams,
  requestOptions?: RequestOptions,
): Promise<Memo> {
  if (createTime != null) {
    validateDateTime("createTime", createTime);
  }

  if (updateTime != null) {
    validateDateTime("updateTime", updateTime);
  }

  const _resp = await sdkRequest<Memo>({
    method: "POST",
    path: `/api/v1/memos/${encodePathSegment(memo)}/comments`,
    operationId: "memoServiceCreateMemoComment",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      commentId: queryValue(commentId, "form", true),
    },
    body: {
      state,
      content,
      visibility,
      name,
      creator,
      createTime,
      updateTime,
      tags,
      pinned,
      attachments,
      relations,
      reactions,
      property,
      parent,
      snippet,
      location,
      space,
    },
    config,
  });
  return _resp.data;
}

export type MemoServiceListMemoReactionsError = Status;

export interface MemoServiceListMemoReactionsParams {
  memo: string;
  pageSize?: number;
  pageToken?: string;
}

/**
 * Lists reactions associated with a specific memo. Use `pageSize` to limit the number of results and `pageToken` to retrieve subsequent pages.
 *
 * ListMemoReactions lists reactions for a memo.
 *
 * @param memo - The memo id.
 * @param pageSize - Optional. The maximum number of reactions to return.
 * @param pageToken - Optional. A page token for pagination.
 */
export async function memoServiceListMemoReactions(
  config: ClientConfig,
  { memo, pageSize, pageToken }: MemoServiceListMemoReactionsParams,
  requestOptions?: RequestOptions,
): Promise<ListMemoReactionsResponse> {
  const _resp = await sdkRequest<ListMemoReactionsResponse>({
    method: "GET",
    path: `/api/v1/memos/${encodePathSegment(memo)}/reactions`,
    operationId: "memoServiceListMemoReactions",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      pageSize: queryValue(pageSize, "form", true),
      pageToken: queryValue(pageToken, "form", true),
    },
    config,
  });
  return _resp.data;
}

export type MemoServiceUpsertMemoReactionError = Status;

export type MemoServiceUpsertMemoReactionParams = UpsertMemoReactionRequest & {
  memo: string;
};

/**
 * Adds or updates the authenticated user's reaction on a memo. Supply the memo resource name and the reaction with its `reactionType`; the operation upserts the authenticated user's reaction.
 *
 * UpsertMemoReaction adds or updates the authenticated user's reaction on a memo.
 *
 * @param memo - The memo id.
 * @param name - Required. The resource name of the memo. Format: memos/{memo}
 * @param reaction - Required. The reaction to upsert.
 */
export async function memoServiceUpsertMemoReaction(
  config: ClientConfig,
  { memo, name, reaction }: MemoServiceUpsertMemoReactionParams,
  requestOptions?: RequestOptions,
): Promise<Reaction> {
  const _resp = await sdkRequest<Reaction>({
    method: "POST",
    path: `/api/v1/memos/${encodePathSegment(memo)}/reactions`,
    operationId: "memoServiceUpsertMemoReaction",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      name,
      reaction,
    },
    config,
  });
  return _resp.data;
}
