// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { Status } from "../../types/shared";
import {
  ListMemoRelationsResponse,
  ListMemoSharesResponse,
  Memo,
  MemoShare,
  SetMemoRelationsRequest,
} from "../../types/memo-service";
import type { ClientConfig, RequestOptions } from "../../client";
import { encodePathSegment, queryValue, sdkRequest } from "../../client";
import { validateDateTime } from "../../validation";

export type MemoServiceDeleteMemoReactionError = Status;

export interface MemoServiceDeleteMemoReactionParams {
  memo: string;
  reaction: string;
}

/**
 * Deletes a reaction from a memo. Supply both the memo identifier and the reaction identifier to select the reaction to remove.
 *
 * DeleteMemoReaction deletes a reaction for a memo.
 *
 * @param memo - The memo id.
 * @param reaction - The reaction id.
 */
export async function memoServiceDeleteMemoReaction(
  config: ClientConfig,
  { memo, reaction }: MemoServiceDeleteMemoReactionParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "DELETE",
    path: `/api/v1/memos/${encodePathSegment(memo)}/reactions/${encodePathSegment(reaction)}`,
    operationId: "memoServiceDeleteMemoReaction",
    responseDecoder: "empty",
    ...requestOptions,
    config,
  });
  void _resp.data;
  return;
}

export type MemoServiceListMemoRelationsError = Status;

export interface MemoServiceListMemoRelationsParams {
  memo: string;
  pageSize?: number;
  pageToken?: string;
}

/**
 * Lists relations associated with a specific memo. Use `pageSize` to limit the number of results and `pageToken` to retrieve subsequent pages.
 *
 * ListMemoRelations lists relations for a memo.
 *
 * @param memo - The memo id.
 * @param pageSize - Optional. The maximum number of relations to return.
 * @param pageToken - Optional. A page token for pagination.
 */
export async function memoServiceListMemoRelations(
  config: ClientConfig,
  { memo, pageSize, pageToken }: MemoServiceListMemoRelationsParams,
  requestOptions?: RequestOptions,
): Promise<ListMemoRelationsResponse> {
  const _resp = await sdkRequest<ListMemoRelationsResponse>({
    method: "GET",
    path: `/api/v1/memos/${encodePathSegment(memo)}/relations`,
    operationId: "memoServiceListMemoRelations",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      pageSize: queryValue(pageSize, "form", true),
      pageToken: queryValue(pageToken, "form", true),
    },
    config,
  });
  return _resp.data;
}

export type MemoServiceSetMemoRelationsError = Status;

export type MemoServiceSetMemoRelationsParams = SetMemoRelationsRequest & {
  memo: string;
};

/**
 * Replaces the full set of mutable REFERENCE relations on a memo. Pass the complete desired list in `relations`; an empty list clears REFERENCE relations, while COMMENT relations remain unchanged and cannot be set through this operation.
 *
 * SetMemoRelations replaces the full set of mutable REFERENCE relations on a memo. COMMENT relations are immutable creation context and are rejected by this RPC. An empty list clears references without changing COMMENT.
 *
 * @param memo - The memo id.
 * @param name - Required. The resource name of the memo. Format: memos/{memo}
 * @param relations - Required. The REFERENCE relations to set for the memo.
 *   COMMENT is invalid.
 */
export async function memoServiceSetMemoRelations(
  config: ClientConfig,
  { memo, name, relations }: MemoServiceSetMemoRelationsParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "PATCH",
    path: `/api/v1/memos/${encodePathSegment(memo)}/relations`,
    operationId: "memoServiceSetMemoRelations",
    responseDecoder: "empty",
    ...requestOptions,
    body: {
      name,
      relations,
    },
    config,
  });
  void _resp.data;
  return;
}

export type MemoServiceListMemoSharesError = Status;

export interface MemoServiceListMemoSharesParams {
  memo: string;
}

/**
 * Lists share links that grant read-only access to a memo through opaque bearer tokens. The authenticated user must be the memo creator or an instance administrator.
 *
 * ListMemoShares lists all share links for a memo. Requires the memo creator or an instance administrator.
 *
 * @param memo - The memo id.
 */
export async function memoServiceListMemoShares(
  config: ClientConfig,
  { memo }: MemoServiceListMemoSharesParams,
  requestOptions?: RequestOptions,
): Promise<ListMemoSharesResponse> {
  const _resp = await sdkRequest<ListMemoSharesResponse>({
    method: "GET",
    path: `/api/v1/memos/${encodePathSegment(memo)}/shares`,
    operationId: "memoServiceListMemoShares",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type MemoServiceCreateMemoShareError = Status;

export type MemoServiceCreateMemoShareParams = MemoShare & {
  memo: string;
};

/**
 * Creates a share link that grants read-only access to a memo through an opaque bearer token. The authenticated user must be the memo creator or an instance administrator; set `expireTime` to limit how long the link works.
 *
 * CreateMemoShare creates a share link for a memo. Requires the memo creator or an instance administrator.
 *
 * @param memo - The memo id.
 * @param name - The resource name of the share. Format:
 *   memos/{memo}/shares/{share} The {share} segment is the opaque token used in
 *   the share URL.
 * @param createTime - Output only. When this share link was created.
 * @param expireTime - Optional. When set, the share link stops working after
 *   this time. If unset, the link never expires.
 */
export async function memoServiceCreateMemoShare(
  config: ClientConfig,
  { memo, name, createTime, expireTime }: MemoServiceCreateMemoShareParams,
  requestOptions?: RequestOptions,
): Promise<MemoShare> {
  if (createTime != null) {
    validateDateTime("createTime", createTime);
  }

  if (expireTime != null) {
    validateDateTime("expireTime", expireTime);
  }

  const _resp = await sdkRequest<MemoShare>({
    method: "POST",
    path: `/api/v1/memos/${encodePathSegment(memo)}/shares`,
    operationId: "memoServiceCreateMemoShare",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      name,
      createTime,
      expireTime,
    },
    config,
  });
  return _resp.data;
}

export type MemoServiceDeleteMemoShareError = Status;

export interface MemoServiceDeleteMemoShareParams {
  memo: string;
  share: string;
}

/**
 * Deletes a share link and revokes its read-only access to a memo. The authenticated user must be the memo creator or an instance administrator, and the share must belong to the specified memo.
 *
 * DeleteMemoShare revokes a share link. Requires the memo creator or an instance administrator.
 *
 * @param memo - The memo id.
 * @param share - The share id.
 */
export async function memoServiceDeleteMemoShare(
  config: ClientConfig,
  { memo, share }: MemoServiceDeleteMemoShareParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "DELETE",
    path: `/api/v1/memos/${encodePathSegment(memo)}/shares/${encodePathSegment(share)}`,
    operationId: "memoServiceDeleteMemoShare",
    responseDecoder: "empty",
    ...requestOptions,
    config,
  });
  void _resp.data;
  return;
}

export type MemoServiceGetSharedMemoError = Status;

export interface MemoServiceGetSharedMemoParams {
  shareToken: string;
}

/**
 * Retrieves the memo associated with a share token without requiring authentication. Use the opaque `shareToken` from the share URL; the token must be valid and unexpired to resolve the memo.
 *
 * GetSharedMemo resolves a share token to its memo. No authentication required. Returns NOT_FOUND if the token is invalid or expired.
 *
 * @param shareToken - Required. The opaque bearer token extracted from the share
 *   URL.
 */
export async function memoServiceGetSharedMemo(
  config: ClientConfig,
  { shareToken }: MemoServiceGetSharedMemoParams,
  requestOptions?: RequestOptions,
): Promise<Memo> {
  const _resp = await sdkRequest<Memo>({
    method: "GET",
    path: `/api/v1/shares/${encodePathSegment(shareToken)}/memo`,
    operationId: "memoServiceGetSharedMemo",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}
