// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * Typed representation of the `TranscribeRequest` API schema.
 */
export interface TranscribeRequest {
  /**
   * Required. Audio input.
   */
  audio: TranscriptionAudio;
}

/**
 * Typed representation of the `TranscribeResponse` API schema.
 */
export interface TranscribeResponse {
  /**
   * The transcribed text.
   */
  text?: string;
}

/**
 * Typed representation of the `TranscriptionAudio` API schema.
 */
export interface TranscriptionAudio {
  /**
   * Inline audio bytes.
   */
  content?: string;
  /**
   * URI for audio content. Reserved for future use.
   */
  uri?: string;
  /**
   * Optional. The uploaded filename.
   */
  filename?: string;
  /**
   * Optional. The MIME type of the input audio.
   */
  contentType?: string;
}
