// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { Attachment } from "./shared";

/**
 * Typed representation of the `BatchDeleteAttachmentsRequest` API schema.
 */
export interface BatchDeleteAttachmentsRequest {
  /**
   * Required array value serialized in the `names` wire field.
   */
  names: string[];
}

/**
 * Typed representation of the `ListAttachmentsResponse` API schema.
 */
export interface ListAttachmentsResponse {
  /**
   * The list of attachments.
   */
  attachments?: Attachment[];
  /**
   * A token that can be sent as `page_token` to retrieve the next page.
   *  If this field is omitted, there are no subsequent pages.
   */
  nextPageToken?: string;
}

/**
 * Typed representation of the `UploadAttachmentRequest` API schema.
 */
export interface UploadAttachmentRequest {
  /**
   * Starts a new upload. The same call may also carry data and finish_write.
   */
  spec?: UploadAttachmentSpec;
  /**
   * Continues the upload identified by a previous response.
   */
  uploadId?: string;
  /**
   * Required. Zero-based byte offset at which data is written. Must equal the
   *  committed size, except when retrying the most recently accepted chunk
   *  with identical bytes and offset, which is accepted without writing again.
   */
  writeOffset: string;
  /**
   * Optional. File bytes, at most max_chunk_size long. With no data and
   *  finish_write false, the call reports progress without writing, and
   *  write_offset is ignored.
   */
  data?: string;
  /**
   * Optional. Finalize the upload after writing data. The committed size must
   *  then equal total_size. Any later call for the same upload_id returns the
   *  created attachment.
   */
  finishWrite?: boolean;
}

/**
 * Typed representation of the `UploadAttachmentResponse` API schema.
 */
export interface UploadAttachmentResponse {
  /**
   * Opaque ID for subsequent calls. This is not a resource name.
   */
  uploadId?: string;
  /**
   * Number of file bytes committed so far.
   */
  committedSize?: string;
  /**
   * Set once the upload has been finalized.
   */
  attachment?: Attachment;
  /**
   * Maximum number of data bytes accepted in one call.
   */
  maxChunkSize?: number;
}

/**
 * Typed representation of the `UploadAttachmentSpec` API schema.
 */
export interface UploadAttachmentSpec {
  /**
   * Required. Metadata for the attachment to create. content must be empty;
   *  file bytes are sent in data.
   */
  attachment: Attachment;
  /**
   * Optional. The attachment ID to use for this attachment.
   *  If empty, a unique ID will be generated.
   *  Format: ^[a-zA-Z0-9]([a-zA-Z0-9-]{0,34}[a-zA-Z0-9])?$
   */
  attachmentId?: string;
  /**
   * Optional. Total size of the file in bytes before media processing.
   *  Zero represents an empty file.
   */
  totalSize?: string;
}
