// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { User } from "./shared";

/**
 * Typed representation of the `GetCurrentUserResponse` API schema.
 */
export interface GetCurrentUserResponse {
  /**
   * The authenticated user's information.
   */
  user?: User;
}

/**
 * Typed representation of the `RefreshTokenRequest` API schema.
 */
export type RefreshTokenRequest = Record<string, unknown>;

/**
 * Typed representation of the `RefreshTokenResponse` API schema.
 */
export interface RefreshTokenResponse {
  /**
   * The new short-lived access token.
   */
  accessToken?: string;
  /**
   * When the access token expires.
   */
  expiresAt?: string;
}

/**
 * Typed representation of the `SignInRequest` API schema.
 */
export interface SignInRequest {
  /**
   * Username and password authentication.
   */
  passwordCredentials?: SignInRequest_PasswordCredentials;
  /**
   * SSO provider authentication.
   */
  ssoCredentials?: SignInRequest_SSOCredentials;
}

/**
 * Nested message for password-based authentication credentials.
 */
export interface SignInRequest_PasswordCredentials {
  /**
   * The username to sign in with.
   */
  username: string;
  /**
   * The password to sign in with.
   */
  password: string;
}

/**
 * Nested message for SSO authentication credentials.
 */
export interface SignInRequest_SSOCredentials {
  /**
   * The resource name of the SSO provider.
   *  Format: identity-providers/{idp}
   */
  idpName: string;
  /**
   * The authorization code from the SSO provider.
   */
  code: string;
  /**
   * The redirect URI used in the SSO flow.
   */
  redirectUri: string;
  /**
   * The PKCE code verifier for enhanced security (RFC 7636).
   *  Optional - enables PKCE flow protection against authorization code interception.
   */
  codeVerifier?: string;
}

/**
 * Typed representation of the `SignInResponse` API schema.
 */
export interface SignInResponse {
  /**
   * The authenticated user's information.
   */
  user?: User;
  /**
   * The short-lived access token for API requests.
   *  Store in memory only, not in localStorage.
   */
  accessToken?: string;
  /**
   * When the access token expires.
   *  Client should call RefreshToken before this time.
   */
  accessTokenExpiresAt?: string;
}
