// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * Typed representation of the `FieldMapping` API schema.
 */
export interface FieldMapping {
  /**
   * Optional `string` value serialized in the `identifier` wire field.
   */
  identifier?: string;
  /**
   * Optional `string` value serialized in the `displayName` wire field.
   */
  displayName?: string;
  /**
   * Optional `string` value serialized in the `email` wire field.
   */
  email?: string;
  /**
   * Optional `string` value serialized in the `avatarUrl` wire field.
   */
  avatarUrl?: string;
}

/**
 * Typed representation of the `IdentityProvider` API schema.
 */
export interface IdentityProvider {
  /**
   * The resource name of the identity provider.
   *  Format: identity-providers/{idp}
   */
  name?: string;
  /**
   * Required. The type of the identity provider.
   */
  type: "TYPE_UNSPECIFIED" | "OAUTH2" | (string & {});
  /**
   * Required. The display title of the identity provider.
   */
  title: string;
  /**
   * Optional. Filter applied to user identifiers.
   */
  identifierFilter?: string;
  /**
   * Required. Configuration for the identity provider.
   */
  config: IdentityProviderConfig;
}

/**
 * Typed representation of the `IdentityProviderConfig` API schema.
 */
export interface IdentityProviderConfig {
  /**
   * Optional object value serialized in the `oauth2Config` wire field.
   */
  oauth2Config?: OAuth2Config;
}

/**
 * Typed representation of the `ListIdentityProvidersResponse` API schema.
 */
export interface ListIdentityProvidersResponse {
  /**
   * The list of identity providers.
   */
  identityProviders?: IdentityProvider[];
}

/**
 * Typed representation of the `OAuth2Config` API schema.
 */
export interface OAuth2Config {
  /**
   * Optional `string` value serialized in the `clientId` wire field.
   */
  clientId?: string;
  /**
   * Optional `string` value serialized in the `clientSecret` wire field.
   */
  clientSecret?: string;
  /**
   * Optional `string` value serialized in the `authUrl` wire field.
   */
  authUrl?: string;
  /**
   * Optional `string` value serialized in the `tokenUrl` wire field.
   */
  tokenUrl?: string;
  /**
   * Optional `string` value serialized in the `userInfoUrl` wire field.
   */
  userInfoUrl?: string;
  /**
   * Optional array value serialized in the `scopes` wire field.
   */
  scopes?: string[];
  /**
   * Optional object value serialized in the `fieldMapping` wire field.
   */
  fieldMapping?: FieldMapping;
}
