// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { Color, User } from "./shared";

/**
 * Request message for BatchGetInstanceSettings method.
 */
export interface BatchGetInstanceSettingsRequest {
  /**
   * The resource names of the instance settings.
   *  Format: instance/settings/{setting}
   */
  names: string[];
}

/**
 * Response message for BatchGetInstanceSettings method.
 */
export interface BatchGetInstanceSettingsResponse {
  /**
   * The instance settings in the same order as the input names.
   */
  settings?: InstanceSetting[];
}

/**
 * Custom profile configuration for instance branding.
 */
export interface GeneralSetting_CustomProfile {
  /**
   * Optional `string` value serialized in the `title` wire field.
   */
  title?: string;
  /**
   * Optional `string` value serialized in the `description` wire field.
   */
  description?: string;
  /**
   * Optional `string` value serialized in the `logoUrl` wire field.
   */
  logoUrl?: string;
}

/**
 * Instance profile message containing basic instance information.
 */
export interface InstanceProfile {
  /**
   * Version is the current version of instance.
   */
  version?: string;
  /**
   * Demo indicates if the instance is in demo mode.
   */
  demo?: boolean;
  /**
   * Instance URL is the URL of the instance.
   */
  instanceUrl?: string;
  /**
   * The first administrator who set up this instance, for display purposes.
   *  May be null on an instance that has lost all admins; use needs_setup to
   *  determine whether initial setup is actually required.
   */
  admin?: User;
  /**
   * Commit is the current build commit of instance.
   */
  commit?: string;
  /**
   * NeedsSetup is true when the instance has no users yet and requires initial
   *  setup (creating the first admin account). Unlike a null admin, this stays
   *  false once any user exists, so an instance that has lost its admins is not
   *  mistaken for a fresh install.
   */
  needsSetup?: boolean;
  /**
   * Access mode controls whether unauthenticated users may access instance content.
   */
  accessMode?:
    | "INSTANCE_ACCESS_MODE_UNSPECIFIED"
    | "INSTANCE_ACCESS_MODE_PRIVATE"
    | "INSTANCE_ACCESS_MODE_PUBLIC"
    | (string & {});
  /**
   * A proof-of-humanity challenge the deployment requires on signup and
   *  password sign-in. Absent when none is configured, which is the case on
   *  every self-hosted instance.
   */
  challenge?: InstanceProfile_Challenge;
}

/**
 * A proof-of-humanity challenge the deployment requires on signup and
 *  password sign-in. Absent when none is configured, which is the case on
 *  every self-hosted instance.
 */
export interface InstanceProfile_Challenge {
  /**
   * The challenge provider, which selects the widget the web app renders.
   */
  provider?: string;
  /**
   * The provider's public site key for the widget.
   */
  siteKey?: string;
}

/**
 * An instance setting resource.
 */
export interface InstanceSetting {
  /**
   * The name of the instance setting.
   *  Format: instance/settings/{setting}
   */
  name?: string;
  /**
   * General instance settings configuration.
   */
  generalSetting?: InstanceSetting_GeneralSetting;
  /**
   * Storage configuration settings for instance attachments.
   */
  storageSetting?: InstanceSetting_StorageSetting;
  /**
   * Memo-related instance settings and policies.
   */
  memoRelatedSetting?: InstanceSetting_MemoRelatedSetting;
  /**
   * Tag metadata configuration.
   *  Active tag metadata is stored in per-user tag settings.
   *  This message remains for backward compatibility with existing clients and migrations.
   */
  tagsSetting?: InstanceSetting_TagsSetting;
  /**
   * Notification transport configuration.
   */
  notificationSetting?: InstanceSetting_NotificationSetting;
  /**
   * AI provider configuration settings.
   */
  aiSetting?: InstanceSetting_AISetting;
  /**
   * Access policy configuration for the instance.
   */
  accessSetting?: InstanceSetting_AccessSetting;
}

/**
 * Access policy configuration for the instance.
 */
export interface InstanceSetting_AccessSetting {
  /**
   * Optional enumerated value serialized in the `accessMode` wire field.
   */
  accessMode?:
    | "INSTANCE_ACCESS_MODE_UNSPECIFIED"
    | "INSTANCE_ACCESS_MODE_PRIVATE"
    | "INSTANCE_ACCESS_MODE_PUBLIC"
    | (string & {});
}

/**
 * AIProviderConfig represents one callable AI provider connection.
 */
export interface InstanceSetting_AIProviderConfig {
  /**
   * Optional `string` value serialized in the `id` wire field.
   */
  id?: string;
  /**
   * Optional `string` value serialized in the `title` wire field.
   */
  title?: string;
  /**
   * Optional enumerated value serialized in the `type` wire field.
   */
  type?: "AI_PROVIDER_TYPE_UNSPECIFIED" | "OPENAI" | "GEMINI" | (string & {});
  /**
   * Optional `string` value serialized in the `endpoint` wire field.
   */
  endpoint?: string;
  /**
   * api_key is write-only and is never returned by GetInstanceSetting.
   */
  apiKey?: string;
  /**
   * api_key_set indicates whether an API key is stored for this provider.
   */
  apiKeySet?: boolean;
  /**
   * api_key_hint is a masked hint for the stored API key.
   */
  apiKeyHint?: string;
}

/**
 * AI provider configuration settings.
 */
export interface InstanceSetting_AISetting {
  /**
   * providers is the list of AI provider configurations available instance-wide.
   */
  providers?: InstanceSetting_AIProviderConfig[];
  /**
   * transcription is the speech-to-text feature configuration.
   *  When unset or transcription.provider_id is empty, transcription is disabled.
   */
  transcription?: InstanceSetting_TranscriptionConfig;
}

/**
 * General instance settings configuration.
 */
export interface InstanceSetting_GeneralSetting {
  /**
   * disallow_user_registration disallows user registration.
   */
  disallowUserRegistration?: boolean;
  /**
   * disallow_password_auth disallows password authentication.
   */
  disallowPasswordAuth?: boolean;
  /**
   * additional_script is the additional script.
   */
  additionalScript?: string;
  /**
   * additional_style is the additional style.
   */
  additionalStyle?: string;
  /**
   * custom_profile is the custom profile.
   */
  customProfile?: GeneralSetting_CustomProfile;
  /**
   * week_start_day_offset is the week start day offset from Sunday.
   *  0: Sunday, 1: Monday, 2: Tuesday, 3: Wednesday, 4: Thursday, 5: Friday, 6: Saturday
   *  Default is Sunday.
   */
  weekStartDayOffset?: number;
  /**
   * disallow_change_username disallows changing username.
   */
  disallowChangeUsername?: boolean;
  /**
   * disallow_change_nickname disallows changing nickname.
   */
  disallowChangeNickname?: boolean;
}

/**
 * Memo-related instance settings and policies.
 */
export interface InstanceSetting_MemoRelatedSetting {
  /**
   * content_length_limit is the limit of content length. Unit is byte.
   */
  contentLengthLimit?: number;
  /**
   * enable_double_click_edit enables editing on double click.
   */
  enableDoubleClickEdit?: boolean;
  /**
   * reactions is the list of reactions.
   */
  reactions?: string[];
}

/**
 * Notification transport configuration.
 */
export interface InstanceSetting_NotificationSetting {
  /**
   * Email delivery configuration for notifications.
   */
  email?: NotificationSetting_EmailSetting;
}

/**
 * Storage is a configured attachment storage instance.
 */
export interface InstanceSetting_Storage {
  /**
   * id is the stable identifier referenced by attachments.
   */
  id?: string;
  /**
   * name is the human-readable storage name.
   */
  name?: string;
  /**
   * Optional enumerated value serialized in the `type` wire field.
   */
  type?: "STORAGE_TYPE_UNSPECIFIED" | "DATABASE" | "LOCAL" | "S3" | (string & {});
  /**
   * S3 configuration for an S3-compatible object store.
   *  Reference: https://developers.cloudflare.com/r2/examples/aws/aws-sdk-go/
   */
  s3Config?: Storage_S3Config;
}

/**
 * Storage configuration settings for instance attachments.
 */
export interface InstanceSetting_StorageSetting {
  /**
   * Legacy compatibility field. New clients use default_storage_id.
   */
  storageType?: "STORAGE_TYPE_UNSPECIFIED" | "DATABASE" | "LOCAL" | "S3" | (string & {});
  /**
   * The template of file path.
   *  e.g. assets/{timestamp}_{filename}
   */
  filepathTemplate?: string;
  /**
   * The max upload size in megabytes.
   */
  uploadSizeLimitMb?: string;
  /**
   * Legacy compatibility field. New clients use storages.
   */
  s3Config?: StorageSetting_S3Config;
  /**
   * Configured storage instances, including inactive instances referenced by attachments.
   */
  storages?: InstanceSetting_Storage[];
  /**
   * Storage used for new attachments.
   */
  defaultStorageId?: string;
}

/**
 * Metadata for a tag.
 */
export interface InstanceSetting_TagMetadata {
  /**
   * Optional background color for the tag label.
   *  When unset, the default tag color is used.
   */
  backgroundColor?: Color;
  /**
   * Whether memos with this tag should have their content blurred.
   */
  blurContent?: boolean;
}

/**
 * Tag metadata configuration.
 *  Active tag metadata is stored in per-user tag settings.
 *  This message remains for backward compatibility with existing clients and migrations.
 */
export interface InstanceSetting_TagsSetting {
  /**
   * Map of tag name pattern to tag metadata.
   *  Each key is treated as an anchored regular expression (^pattern$),
   *  so a single entry like "project/.*" matches all tags under that prefix.
   *  Exact tag names are also valid (they are trivially valid regex patterns).
   */
  tags?: { [key: string]: InstanceSetting_TagMetadata };
}

/**
 * TranscriptionConfig configures the speech-to-text feature.
 */
export interface InstanceSetting_TranscriptionConfig {
  /**
   * provider_id references an entry in AISetting.providers[].id.
   *  Empty string means transcription is disabled.
   */
  providerId?: string;
  /**
   * model is the provider-specific model identifier.
   *  Empty string falls back to the engine default
   *  (whisper-1 for OPENAI providers, gemini-2.5-flash for GEMINI providers).
   */
  model?: string;
  /**
   * language is the default ISO 639-1 language hint sent to the provider.
   *  Empty string lets the provider auto-detect.
   */
  language?: string;
  /**
   * prompt is a default spelling/vocabulary hint passed to the provider.
   */
  prompt?: string;
}

/**
 * Resource usage statistics for the instance.
 */
export interface InstanceStats {
  /**
   * Database size statistics.
   */
  database?: InstanceStats_DatabaseStats;
  /**
   * Recursive size of the data directory in bytes. -1 if unavailable.
   */
  localStorageBytes?: string;
  /**
   * Server-side timestamp when the snapshot was generated.
   */
  generatedTime?: string;
}

/**
 * Database size statistics.
 */
export interface InstanceStats_DatabaseStats {
  /**
   * driver is one of "sqlite", "mysql", "postgres".
   */
  driver?: string;
  /**
   * size_bytes is the database size in bytes; -1 if unavailable.
   */
  sizeBytes?: string;
}

/**
 * Email delivery configuration for notifications.
 */
export interface NotificationSetting_EmailSetting {
  /**
   * Optional `boolean` value serialized in the `enabled` wire field.
   */
  enabled?: boolean;
  /**
   * Optional `string` value serialized in the `smtpHost` wire field.
   */
  smtpHost?: string;
  /**
   * Optional `int32`-formatted value serialized in the `smtpPort` wire field.
   */
  smtpPort?: number;
  /**
   * Optional `string` value serialized in the `smtpUsername` wire field.
   */
  smtpUsername?: string;
  /**
   * Optional `string` value serialized in the `smtpPassword` wire field.
   */
  smtpPassword?: string;
  /**
   * Optional `string` value serialized in the `fromEmail` wire field.
   */
  fromEmail?: string;
  /**
   * Optional `string` value serialized in the `fromName` wire field.
   */
  fromName?: string;
  /**
   * Optional `string` value serialized in the `replyTo` wire field.
   */
  replyTo?: string;
  /**
   * Optional `boolean` value serialized in the `useTls` wire field.
   */
  useTls?: boolean;
  /**
   * Optional `boolean` value serialized in the `useSsl` wire field.
   */
  useSsl?: boolean;
}

/**
 * S3 configuration for an S3-compatible object store.
 *  Reference: https://developers.cloudflare.com/r2/examples/aws/aws-sdk-go/
 */
export interface Storage_S3Config {
  /**
   * Optional `string` value serialized in the `accessKeyId` wire field.
   */
  accessKeyId?: string;
  /**
   * Optional `string` value serialized in the `accessKeySecret` wire field.
   */
  accessKeySecret?: string;
  /**
   * Optional `string` value serialized in the `endpoint` wire field.
   */
  endpoint?: string;
  /**
   * Optional `string` value serialized in the `region` wire field.
   */
  region?: string;
  /**
   * Optional `string` value serialized in the `bucket` wire field.
   */
  bucket?: string;
  /**
   * Optional `boolean` value serialized in the `usePathStyle` wire field.
   */
  usePathStyle?: boolean;
  /**
   * insecure_skip_tls_verify disables TLS certificate verification when connecting
   *  to the S3 endpoint. Only enable this for trusted endpoints that use a self-signed
   *  certificate; it removes protection against man-in-the-middle attacks.
   */
  insecureSkipTlsVerify?: boolean;
}

/**
 * Legacy S3 configuration retained for compatibility with existing clients.
 *  Reference: https://developers.cloudflare.com/r2/examples/aws/aws-sdk-go/
 */
export interface StorageSetting_S3Config {
  /**
   * Optional `string` value serialized in the `accessKeyId` wire field.
   */
  accessKeyId?: string;
  /**
   * Optional `string` value serialized in the `accessKeySecret` wire field.
   */
  accessKeySecret?: string;
  /**
   * Optional `string` value serialized in the `endpoint` wire field.
   */
  endpoint?: string;
  /**
   * Optional `string` value serialized in the `region` wire field.
   */
  region?: string;
  /**
   * Optional `string` value serialized in the `bucket` wire field.
   */
  bucket?: string;
  /**
   * Optional `boolean` value serialized in the `usePathStyle` wire field.
   */
  usePathStyle?: boolean;
  /**
   * insecure_skip_tls_verify disables TLS certificate verification when connecting
   *  to the S3 endpoint. Only enable this for trusted endpoints that use a self-signed
   *  certificate; it removes protection against man-in-the-middle attacks.
   */
  insecureSkipTlsVerify?: boolean;
}

/**
 * Request message for TestInstanceEmailSetting method.
 */
export interface TestInstanceEmailSettingRequest {
  /**
   * Optional. SMTP email settings to test. If omitted, the stored notification email setting is used.
   */
  email?: NotificationSetting_EmailSetting;
  /**
   * Optional. Recipient email address. If omitted, the current user's email address is used.
   */
  recipientEmail?: string;
}
