// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { Attachment } from "./shared";

/**
 * Typed representation of the `BatchGetLinkMetadataRequest` API schema.
 */
export interface BatchGetLinkMetadataRequest {
  /**
   * Required. The link URLs.
   */
  urls: string[];
}

/**
 * Typed representation of the `BatchGetLinkMetadataResponse` API schema.
 */
export interface BatchGetLinkMetadataResponse {
  /**
   * The link metadata list, in the same order as the input URLs.
   */
  linkMetadata?: LinkMetadata[];
}

/**
 * Typed representation of the `LinkMetadata` API schema.
 */
export interface LinkMetadata {
  /**
   * The original link URL.
   */
  url?: string;
  /**
   * The link title.
   */
  title?: string;
  /**
   * The link description.
   */
  description?: string;
  /**
   * The link image URL.
   */
  image?: string;
}

/**
 * Typed representation of the `ListMemoAttachmentsResponse` API schema.
 */
export interface ListMemoAttachmentsResponse {
  /**
   * The list of attachments.
   */
  attachments?: Attachment[];
  /**
   * A token for the next page of results.
   */
  nextPageToken?: string;
}

/**
 * Typed representation of the `ListMemoCommentsResponse` API schema.
 */
export interface ListMemoCommentsResponse {
  /**
   * The list of comment memos.
   */
  memos?: Memo[];
  /**
   * A token for the next page of results.
   */
  nextPageToken?: string;
}

/**
 * Typed representation of the `ListMemoReactionsResponse` API schema.
 */
export interface ListMemoReactionsResponse {
  /**
   * The list of reactions.
   */
  reactions?: Reaction[];
  /**
   * A token for the next page of results.
   */
  nextPageToken?: string;
}

/**
 * Typed representation of the `ListMemoRelationsResponse` API schema.
 */
export interface ListMemoRelationsResponse {
  /**
   * The list of relations.
   */
  relations?: MemoRelation[];
  /**
   * A token for the next page of results.
   */
  nextPageToken?: string;
}

/**
 * Typed representation of the `ListMemoSharesResponse` API schema.
 */
export interface ListMemoSharesResponse {
  /**
   * The list of share links.
   */
  memoShares?: MemoShare[];
}

/**
 * Typed representation of the `ListMemosResponse` API schema.
 */
export interface ListMemosResponse {
  /**
   * The list of memos.
   */
  memos?: Memo[];
  /**
   * A token that can be sent as `page_token` to retrieve the next page.
   *  If this field is omitted, there are no subsequent pages.
   */
  nextPageToken?: string;
}

/**
 * Typed representation of the `Location` API schema.
 */
export interface Location {
  /**
   * A placeholder text for the location.
   */
  placeholder?: string;
  /**
   * The latitude of the location.
   */
  latitude?: number;
  /**
   * The longitude of the location.
   */
  longitude?: number;
}

/**
 * Typed representation of the `Memo` API schema.
 */
export interface Memo {
  /**
   * The resource name of the memo.
   *  Format: memos/{memo}, where memo is the user-defined UID.
   */
  name?: string;
  /**
   * The state of the memo.
   */
  state: "STATE_UNSPECIFIED" | "NORMAL" | "ARCHIVED" | (string & {});
  /**
   * The name of the creator.
   *  Format: users/{user}
   */
  creator?: string;
  /**
   * The creation timestamp.
   *  If not set on creation, the server will set it to the current time.
   */
  createTime?: string;
  /**
   * The last update timestamp.
   *  If not set on creation, the server will set it to the current time.
   */
  updateTime?: string;
  /**
   * Required. The content of the memo in Markdown format.
   */
  content: string;
  /**
   * The visibility of the memo.
   *  One of PRIVATE (creator only), PROTECTED (signed-in users), PUBLIC
   *  (anonymous-eligible), or SPACE (active space members). Defaults to
   *  PRIVATE on creation when unspecified.
   */
  visibility:
    | "VISIBILITY_UNSPECIFIED"
    | "PRIVATE"
    | "PROTECTED"
    | "PUBLIC"
    | "SPACE"
    | (string & {});
  /**
   * Output only. The tags extracted from the content.
   */
  tags?: string[];
  /**
   * Whether the memo is pinned.
   */
  pinned?: boolean;
  /**
   * Optional. The attachments of the memo.
   */
  attachments?: Attachment[];
  /**
   * Optional. The relations of the memo.
   */
  relations?: MemoRelation[];
  /**
   * Output only. The reactions to the memo.
   */
  reactions?: Reaction[];
  /**
   * Output only. The computed properties of the memo.
   */
  property?: Memo_Property;
  /**
   * Output only. The context memo of this COMMENT relation, if any.
   *  Its identity is returned even when the caller cannot read the parent.
   *  Fetch the parent independently; this field does not grant read access.
   *  Format: memos/{memo}
   */
  parent?: string;
  /**
   * Output only. The snippet of the memo content. Plain text only.
   */
  snippet?: string;
  /**
   * Optional. The location of the memo.
   */
  location?: Location;
  /**
   * Optional. The space in which this memo is placed. Format: spaces/{space}.
   *  Every memo, including a comment, owns its placement independently.
   */
  space?: string;
}

/**
 * Computed properties of a memo.
 */
export interface Memo_Property {
  /**
   * Optional `boolean` value serialized in the `hasLink` wire field.
   */
  hasLink?: boolean;
  /**
   * Optional `boolean` value serialized in the `hasTaskList` wire field.
   */
  hasTaskList?: boolean;
  /**
   * Optional `boolean` value serialized in the `hasCode` wire field.
   */
  hasCode?: boolean;
  /**
   * Optional `boolean` value serialized in the `hasIncompleteTasks` wire field.
   */
  hasIncompleteTasks?: boolean;
  /**
   * The title extracted from the first H1 heading, if present.
   */
  title?: string;
}

/**
 * Typed representation of the `MemoRelation` API schema.
 */
export interface MemoRelation {
  /**
   * The memo in the relation.
   */
  memo: MemoRelation_Memo;
  /**
   * The related memo.
   */
  relatedMemo: MemoRelation_Memo;
  /**
   * Required enumerated value serialized in the `type` wire field.
   */
  type: "TYPE_UNSPECIFIED" | "REFERENCE" | "COMMENT" | (string & {});
}

/**
 * Memo reference in relations.
 */
export interface MemoRelation_Memo {
  /**
   * The resource name of the memo.
   *  Format: memos/{memo}
   */
  name: string;
  /**
   * Output only. The snippet of the memo content. Plain text only.
   */
  snippet?: string;
}

/**
 * MemoShare is an access grant that permits read-only access to a memo via an opaque bearer token.
 */
export interface MemoShare {
  /**
   * The resource name of the share. Format: memos/{memo}/shares/{share}
   *  The {share} segment is the opaque token used in the share URL.
   */
  name?: string;
  /**
   * Output only. When this share link was created.
   */
  createTime?: string;
  /**
   * Optional. When set, the share link stops working after this time.
   *  If unset, the link never expires.
   */
  expireTime?: string;
}

/**
 * Reaction is a reaction attached to a memo.
 */
export interface Reaction {
  /**
   * The resource name of the reaction.
   *  Format: memos/{memo}/reactions/{reaction}
   */
  name?: string;
  /**
   * The resource name of the creator.
   *  Format: users/{user}
   */
  creator?: string;
  /**
   * Required. The type of reaction (e.g., "👍", "❤️", "😄").
   */
  reactionType: string;
  /**
   * Output only. The creation timestamp.
   */
  createTime?: string;
}

/**
 * Typed representation of the `SetMemoAttachmentsRequest` API schema.
 */
export interface SetMemoAttachmentsRequest {
  /**
   * Required. The resource name of the memo.
   *  Format: memos/{memo}
   */
  name: string;
  /**
   * Required. The attachments to set for the memo.
   */
  attachments: Attachment[];
}

/**
 * Typed representation of the `SetMemoRelationsRequest` API schema.
 */
export interface SetMemoRelationsRequest {
  /**
   * Required. The resource name of the memo.
   *  Format: memos/{memo}
   */
  name: string;
  /**
   * Required. The REFERENCE relations to set for the memo. COMMENT is invalid.
   */
  relations: MemoRelation[];
}

/**
 * Typed representation of the `UpsertMemoReactionRequest` API schema.
 */
export interface UpsertMemoReactionRequest {
  /**
   * Required. The resource name of the memo.
   *  Format: memos/{memo}
   */
  name: string;
  /**
   * Required. The reaction to upsert.
   */
  reaction: Reaction;
}
