// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * Typed representation of the `Attachment` API schema.
 */
export interface Attachment {
  /**
   * The name of the attachment.
   *  Format: attachments/{attachment}
   */
  name?: string;
  /**
   * Output only. The creation timestamp.
   */
  createTime?: string;
  /**
   * The filename of the attachment.
   */
  filename: string;
  /**
   * Input only. The content of the attachment.
   */
  content?: string;
  /**
   * Optional. The external link of the attachment.
   */
  externalLink?: string;
  /**
   * The MIME type of the attachment.
   */
  type: string;
  /**
   * Output only. The size of the attachment in bytes.
   */
  size?: string;
  /**
   * Optional. The related memo. Refer to `Memo.name`.
   *  Format: memos/{memo}
   */
  memo?: string;
  /**
   * Optional. Motion media metadata.
   */
  motionMedia?: MotionMedia;
  /**
   * Optional. Immutable normalized media metadata explicitly supplied by the client at creation time.
   */
  mediaMetadata?: MediaMetadata;
  /**
   * Output only. The user who uploaded this attachment, which may differ from
   *  the creator of the linked memo. Format: users/{user}.
   */
  creator?: string;
}

/**
 * Represents a color in the RGBA color space. This representation is designed
 *  for simplicity of conversion to/from color representations in various
 *  languages over compactness. For example, the fields of this representation
 *  can be trivially provided to the constructor of `java.awt.Color` in Java; it
 *  can also be trivially provided to UIColor's `+colorWithRed:green:blue:alpha`
 *  method in iOS; and, with just a little work, it can be easily formatted into
 *  a CSS `rgba()` string in JavaScript.
 *
 *  This reference page doesn't carry information about the absolute color
 *  space
 *  that should be used to interpret the RGB value (e.g. sRGB, Adobe RGB,
 *  DCI-P3, BT.2020, etc.). By default, applications should assume the sRGB color
 *  space.
 *
 *  When color equality needs to be decided, implementations, unless
 *  documented otherwise, treat two colors as equal if all their red,
 *  green, blue, and alpha values each differ by at most 1e-5.
 *
 *  Example (Java):
 *
 *       import com.google.type.Color;
 *
 *       // ...
 *       public static java.awt.Color fromProto(Color protocolor) {
 *         float alpha = protocolor.hasAlpha()
 *             ? protocolor.getAlpha().getValue()
 *             : 1.0;
 *
 *         return new java.awt.Color(
 *             protocolor.getRed(),
 *             protocolor.getGreen(),
 *             protocolor.getBlue(),
 *             alpha);
 *       }
 *
 *       public static Color toProto(java.awt.Color color) {
 *         float red = (float) color.getRed();
 *         float green = (float) color.getGreen();
 *         float blue = (float) color.getBlue();
 *         float denominator = 255.0;
 *         Color.Builder resultBuilder =
 *             Color
 *                 .newBuilder()
 *                 .setRed(red / denominator)
 *                 .setGreen(green / denominator)
 *                 .setBlue(blue / denominator);
 *         int alpha = color.getAlpha();
 *         if (alpha != 255) {
 *           result.setAlpha(
 *               FloatValue
 *                   .newBuilder()
 *                   .setValue(((float) alpha) / denominator)
 *                   .build());
 *         }
 *         return resultBuilder.build();
 *       }
 *       // ...
 *
 *  Example (iOS / Obj-C):
 *
 *       // ...
 *       static UIColor* fromProto(Color* protocolor) {
 *          float red = [protocolor red];
 *          float green = [protocolor green];
 *          float blue = [protocolor blue];
 *          FloatValue* alpha_wrapper = [protocolor alpha];
 *          float alpha = 1.0;
 *          if (alpha_wrapper != nil) {
 *            alpha = [alpha_wrapper value];
 *          }
 *          return [UIColor colorWithRed:red green:green blue:blue alpha:alpha];
 *       }
 *
 *       static Color* toProto(UIColor* color) {
 *           CGFloat red, green, blue, alpha;
 *           if (![color getRed:&red green:&green blue:&blue alpha:&alpha]) {
 *             return nil;
 *           }
 *           Color* result = [[Color alloc] init];
 *           [result setRed:red];
 *           [result setGreen:green];
 *           [result setBlue:blue];
 *           if (alpha <= 0.9999) {
 *             [result setAlpha:floatWrapperWithValue(alpha)];
 *           }
 *           [result autorelease];
 *           return result;
 *      }
 *      // ...
 *
 *   Example (JavaScript):
 *
 *      // ...
 *
 *      var protoToCssColor = function(rgb_color) {
 *         var redFrac = rgb_color.red || 0.0;
 *         var greenFrac = rgb_color.green || 0.0;
 *         var blueFrac = rgb_color.blue || 0.0;
 *         var red = Math.floor(redFrac * 255);
 *         var green = Math.floor(greenFrac * 255);
 *         var blue = Math.floor(blueFrac * 255);
 *
 *         if (!('alpha' in rgb_color)) {
 *            return rgbToCssColor(red, green, blue);
 *         }
 *
 *         var alphaFrac = rgb_color.alpha.value || 0.0;
 *         var rgbParams = [red, green, blue].join(',');
 *         return ['rgba(', rgbParams, ',', alphaFrac, ')'].join('');
 *      };
 *
 *      var rgbToCssColor = function(red, green, blue) {
 *        var rgbNumber = new Number((red << 16) | (green << 8) | blue);
 *        var hexString = rgbNumber.toString(16);
 *        var missingZeros = 6 - hexString.length;
 *        var resultBuilder = ['#'];
 *        for (var i = 0; i < missingZeros; i++) {
 *           resultBuilder.push('0');
 *        }
 *        resultBuilder.push(hexString);
 *        return resultBuilder.join('');
 *      };
 *
 *      // ...
 */
export interface Color {
  /**
   * The amount of red in the color as a value in the interval [0, 1].
   */
  red?: number;
  /**
   * The amount of green in the color as a value in the interval [0, 1].
   */
  green?: number;
  /**
   * The amount of blue in the color as a value in the interval [0, 1].
   */
  blue?: number;
  /**
   * The fraction of this color that should be applied to the pixel. That is,
   *  the final pixel color is defined by the equation:
   *
   *    `pixel color = alpha * (this color) + (1.0 - alpha) * (background color)`
   *
   *  This means that a value of 1.0 corresponds to a solid color, whereas
   *  a value of 0.0 corresponds to a completely transparent color. This
   *  uses a wrapper message rather than a simple float scalar so that it is
   *  possible to distinguish between a default value and the value being unset.
   *  If omitted, this color object is rendered as a solid color
   *  (as if the alpha value had been explicitly given a value of 1.0).
   */
  alpha?: number;
}

/**
 * Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
 */
export interface GoogleProtobufAny {
  /**
   * The type of the serialized message.
   */
  type?: string;
}

/**
 * Typed representation of the `MediaCaptureTime` API schema.
 */
export interface MediaCaptureTime {
  /**
   * Optional `string` value serialized in the `localDateTime` wire field.
   */
  localDateTime?: string;
  /**
   * Optional `string` value serialized in the `utcOffset` wire field.
   */
  utcOffset?: string;
}

/**
 * Typed representation of the `MediaLocation` API schema.
 */
export interface MediaLocation {
  /**
   * Optional `double`-formatted value serialized in the `latitude` wire field.
   */
  latitude?: number;
  /**
   * Optional `double`-formatted value serialized in the `longitude` wire field.
   */
  longitude?: number;
  /**
   * Optional `double`-formatted value serialized in the `altitudeMeters` wire field.
   */
  altitudeMeters?: number;
}

/**
 * Typed representation of the `MediaMetadata` API schema.
 */
export interface MediaMetadata {
  /**
   * Optional `int32`-formatted value serialized in the `width` wire field.
   */
  width?: number;
  /**
   * Optional `int32`-formatted value serialized in the `height` wire field.
   */
  height?: number;
  /**
   * Optional object value serialized in the `photo` wire field.
   */
  photo?: PhotoMetadata;
  /**
   * Optional object value serialized in the `video` wire field.
   */
  video?: VideoMetadata;
}

/**
 * Typed representation of the `MotionMedia` API schema.
 */
export interface MotionMedia {
  /**
   * Optional enumerated value serialized in the `family` wire field.
   */
  family?:
    | "MOTION_MEDIA_FAMILY_UNSPECIFIED"
    | "APPLE_LIVE_PHOTO"
    | "ANDROID_MOTION_PHOTO"
    | (string & {});
  /**
   * Optional enumerated value serialized in the `role` wire field.
   */
  role?: "MOTION_MEDIA_ROLE_UNSPECIFIED" | "STILL" | "VIDEO" | "CONTAINER" | (string & {});
  /**
   * Optional `string` value serialized in the `groupId` wire field.
   */
  groupId?: string;
  /**
   * Optional `string` value serialized in the `presentationTimestampUs` wire field.
   */
  presentationTimestampUs?: string;
  /**
   * Optional `boolean` value serialized in the `hasEmbeddedVideo` wire field.
   */
  hasEmbeddedVideo?: boolean;
}

/**
 * Typed representation of the `PhotoMetadata` API schema.
 */
export interface PhotoMetadata {
  /**
   * Optional object value serialized in the `captureTime` wire field.
   */
  captureTime?: MediaCaptureTime;
  /**
   * Optional object value serialized in the `location` wire field.
   */
  location?: MediaLocation;
  /**
   * Optional `int32`-formatted value serialized in the `sourceExifOrientation` wire field.
   */
  sourceExifOrientation?: number;
  /**
   * Optional `string` value serialized in the `cameraMake` wire field.
   */
  cameraMake?: string;
  /**
   * Optional `string` value serialized in the `cameraModel` wire field.
   */
  cameraModel?: string;
  /**
   * Optional `string` value serialized in the `lensModel` wire field.
   */
  lensModel?: string;
  /**
   * Optional `double`-formatted value serialized in the `fNumber` wire field.
   */
  fNumber?: number;
  /**
   * Optional `double`-formatted value serialized in the `exposureTimeSeconds` wire field.
   */
  exposureTimeSeconds?: number;
  /**
   * Optional `int32`-formatted value serialized in the `iso` wire field.
   */
  iso?: number;
  /**
   * Optional `double`-formatted value serialized in the `focalLengthMm` wire field.
   */
  focalLengthMm?: number;
}

/**
 * Space is a collaboration boundary for placed memos.
 */
export interface Space {
  /**
   * The resource name of the space. Format: spaces/{space}.
   */
  name?: string;
  /**
   * Required. The human-readable title.
   */
  title: string;
  /**
   * Optional. A description of the space.
   */
  description?: string;
  /**
   * Output only. The authenticated user's membership role in this space.
   *  ROLE_UNSPECIFIED when this Space is exposed as metadata-only.
   */
  currentUserRole?: "ROLE_UNSPECIFIED" | "ADMIN" | "USER" | (string & {});
  /**
   * Output only. The number of accepted members in this space. Pending
   *  invitations are excluded. Zero when this Space is exposed as metadata-only.
   */
  memberCount?: number;
  /**
   * Optional. Display icon. Omit when updating with the "icon" mask to reset
   *  to the default Space mark.
   */
  icon?: Space_Icon;
}

/**
 * Typed representation of the `Space_Icon` API schema.
 */
export interface Space_Icon {
  /**
   * A Unicode emoji sequence.
   */
  emoji?: string;
  /**
   * A canonical Lucide icon name, such as "leaf".
   */
  lucide?: string;
}

/**
 * The `Status` type defines a logical error model that is suitable for different programming environments, including REST APIs and RPC APIs. It is used by [gRPC](https://github.com/grpc). Each `Status` message contains three pieces of data: error code, error message, and error details. You can find out more about this error model and how to work with it in the [API Design Guide](https://cloud.google.com/apis/design/errors).
 */
export interface Status {
  /**
   * The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
   */
  code?: number;
  /**
   * A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client.
   */
  message?: string;
  /**
   * A list of messages that carry the error details.  There is a common set of message types for APIs to use.
   */
  details?: GoogleProtobufAny[];
}

/**
 * Typed representation of the `User` API schema.
 */
export interface User {
  /**
   * The resource name of the user.
   *  Format: users/{user}
   */
  name?: string;
  /**
   * The role of the user.
   */
  role: "ROLE_UNSPECIFIED" | "ADMIN" | "USER" | (string & {});
  /**
   * Required. The unique username for login.
   */
  username: string;
  /**
   * Optional. The email address of the user. Stored trimmed and lowercased;
   *  empty means no address. An address belongs to at most one user on the
   *  instance, so writes that would reuse one fail with ALREADY_EXISTS.
   */
  email?: string;
  /**
   * Optional. The display name of the user.
   */
  displayName?: string;
  /**
   * Optional. The avatar URL of the user.
   */
  avatarUrl?: string;
  /**
   * Optional. The description of the user.
   */
  description?: string;
  /**
   * Input only. The password for the user.
   */
  password?: string;
  /**
   * The state of the user.
   */
  state: "STATE_UNSPECIFIED" | "NORMAL" | "ARCHIVED" | (string & {});
  /**
   * Output only. The creation timestamp.
   */
  createTime?: string;
  /**
   * Output only. The last update timestamp.
   */
  updateTime?: string;
}

/**
 * Typed representation of the `VideoMetadata` API schema.
 */
export interface VideoMetadata {
  /**
   * Optional `double`-formatted value serialized in the `durationSeconds` wire field.
   */
  durationSeconds?: number;
}
