// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { Space } from "./shared";

/**
 * Typed representation of the `AcceptSpaceInvitationRequest` API schema.
 */
export interface AcceptSpaceInvitationRequest {
  /**
   * Required. Format: spaces/{space}/invitations/{username}.
   */
  name: string;
}

/**
 * Typed representation of the `DeclineSpaceInvitationRequest` API schema.
 */
export interface DeclineSpaceInvitationRequest {
  /**
   * Required. Format: spaces/{space}/invitations/{username}.
   */
  name: string;
}

/**
 * Typed representation of the `ListSpaceInvitationsResponse` API schema.
 */
export interface ListSpaceInvitationsResponse {
  /**
   * Optional array value serialized in the `spaceInvitations` wire field.
   */
  spaceInvitations?: SpaceInvitation[];
  /**
   * Optional `string` value serialized in the `nextPageToken` wire field.
   */
  nextPageToken?: string;
}

/**
 * Typed representation of the `ListSpaceMembersResponse` API schema.
 */
export interface ListSpaceMembersResponse {
  /**
   * Optional array value serialized in the `spaceMembers` wire field.
   */
  spaceMembers?: SpaceMember[];
  /**
   * Optional `string` value serialized in the `nextPageToken` wire field.
   */
  nextPageToken?: string;
}

/**
 * Typed representation of the `ListSpacesResponse` API schema.
 */
export interface ListSpacesResponse {
  /**
   * Optional array value serialized in the `spaces` wire field.
   */
  spaces?: Space[];
  /**
   * Optional `string` value serialized in the `nextPageToken` wire field.
   */
  nextPageToken?: string;
}

/**
 * Typed representation of the `ListUserSpaceInvitationsResponse` API schema.
 */
export interface ListUserSpaceInvitationsResponse {
  /**
   * Optional array value serialized in the `spaceInvitations` wire field.
   */
  spaceInvitations?: SpaceInvitation[];
  /**
   * Optional `string` value serialized in the `nextPageToken` wire field.
   */
  nextPageToken?: string;
}

/**
 * SpaceInvitation is a pending invitation for an existing user to join a space.
 */
export interface SpaceInvitation {
  /**
   * The resource name. Format: spaces/{space}/invitations/{username}.
   */
  name?: string;
  /**
   * Required. The invited user. Format: users/{username}.
   */
  invitee: string;
  /**
   * Required. The role the user will receive after accepting the invitation.
   */
  role: "ROLE_UNSPECIFIED" | "ADMIN" | "USER" | (string & {});
  /**
   * Output only. The Space the user is invited to. This lets an invitee
   *  understand the invitation without granting membership-based GetSpace access.
   */
  space?: Space;
}

/**
 * SpaceMember is a user's membership and governance role in a space.
 */
export interface SpaceMember {
  /**
   * The resource name. Format: spaces/{space}/members/{username}.
   */
  name?: string;
  /**
   * Required. The member user. Format: users/{username}.
   */
  user: string;
  /**
   * Required. The member's role within this space.
   */
  role: "ROLE_UNSPECIFIED" | "ADMIN" | "USER" | (string & {});
}
