// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { Space, User } from "./shared";

import type { UserSetting, UserStats, UserWebhook } from "./user-service.part002";

/**
 * Typed representation of the `BatchGetUsersRequest` API schema.
 */
export interface BatchGetUsersRequest {
  /**
   * Optional array value serialized in the `usernames` wire field.
   */
  usernames?: string[];
}

/**
 * Typed representation of the `BatchGetUsersResponse` API schema.
 */
export interface BatchGetUsersResponse {
  /**
   * Optional array value serialized in the `users` wire field.
   */
  users?: User[];
}

/**
 * Typed representation of the `CreateLinkedIdentityRequest` API schema.
 */
export interface CreateLinkedIdentityRequest {
  /**
   * Required. The parent user who owns the linked identity.
   *  Format: users/{user}
   */
  parent: string;
  /**
   * Required. The identity provider to link.
   *  Format: identity-providers/{idp}
   */
  idpName: string;
  /**
   * Required. The authorization code from the identity provider.
   */
  code: string;
  /**
   * Required. The redirect URI used in the OAuth flow.
   */
  redirectUri: string;
  /**
   * Optional. The PKCE code verifier used in the OAuth flow.
   */
  codeVerifier?: string;
}

/**
 * Typed representation of the `CreatePersonalAccessTokenRequest` API schema.
 */
export interface CreatePersonalAccessTokenRequest {
  /**
   * Required. The parent resource where this token will be created.
   *  Format: users/{user}
   */
  parent: string;
  /**
   * Optional. Description of the personal access token.
   */
  description?: string;
  /**
   * Optional. Expiration duration in days (0 = never expires).
   */
  expiresInDays?: number;
}

/**
 * Typed representation of the `CreatePersonalAccessTokenResponse` API schema.
 */
export interface CreatePersonalAccessTokenResponse {
  /**
   * The personal access token metadata.
   */
  personalAccessToken?: PersonalAccessToken;
  /**
   * The actual token value - only returned on creation.
   *  This is the only time the token value will be visible.
   */
  token?: string;
}

/**
 * Typed representation of the `GetUserWebhookSigningSecretResponse` API schema.
 */
export interface GetUserWebhookSigningSecretResponse {
  /**
   * The signing secret, in the Standard Webhooks "whsec_<base64>" form.
   */
  signingSecret?: string;
}

/**
 * Typed representation of the `ImportMemosRequest` API schema.
 */
export interface ImportMemosRequest {
  /**
   * Required. The user who receives the memos. Must be the caller.
   *  Format: users/{user}
   */
  name: string;
  /**
   * Starts a new upload. The same call may also carry data and finish_write.
   */
  spec?: ImportMemosSpec;
  /**
   * Continues the upload identified by a previous response.
   */
  uploadId?: string;
  /**
   * Required. Zero-based byte offset at which data is written. Must equal the
   *  committed size, except when retrying the most recently accepted chunk
   *  with identical bytes and offset, which is accepted without writing again.
   */
  writeOffset: string;
  /**
   * Optional. Archive bytes, at most max_chunk_size long. With no data and
   *  finish_write false, the call reports progress without writing, and
   *  write_offset is ignored.
   */
  data?: string;
  /**
   * Optional. Finish the upload after writing data. The committed size must
   *  then equal total_size. The archive is validated and, unless
   *  validate_only is set, imported. Any later call for an imported upload
   *  returns the same report.
   */
  finishWrite?: boolean;
  /**
   * Optional. On a finishing call, validate the archive and return the plan
   *  without importing. The upload stays staged so a later finishing call can
   *  import it.
   */
  validateOnly?: boolean;
  /**
   * Optional. Read on the finishing call that imports. Unspecified means SKIP.
   */
  conflictPolicy?: "CONFLICT_POLICY_UNSPECIFIED" | "SKIP" | "REPLACE" | "DUPLICATE" | (string & {});
}

/**
 * Typed representation of the `ImportMemosResponse` API schema.
 */
export interface ImportMemosResponse {
  /**
   * Opaque ID for subsequent calls. This is not a resource name.
   */
  uploadId?: string;
  /**
   * Number of archive bytes committed so far.
   */
  committedSize?: string;
  /**
   * Maximum number of data bytes accepted in one call.
   */
  maxChunkSize?: number;
  /**
   * What the import would do. Set by a finishing call with validate_only.
   */
  plan?: MemoImportPlan;
  /**
   * What the import did. Set by a finishing call that imported.
   */
  report?: MemoImportReport;
}

/**
 * Typed representation of the `ImportMemosSpec` API schema.
 */
export interface ImportMemosSpec {
  /**
   * Optional. Total size of the archive in bytes.
   */
  totalSize?: string;
}

/**
 * LinkedIdentity represents an SSO identity linked to a user account.
 */
export interface LinkedIdentity {
  /**
   * The resource name of the linked identity.
   *  Format: users/{user}/linkedIdentities/{linked_identity}
   */
  name?: string;
  /**
   * The resource name of the identity provider.
   *  Format: identity-providers/{idp}
   */
  idpName?: string;
  /**
   * The external user identifier from the identity provider.
   */
  externUid?: string;
}

/**
 * Typed representation of the `ListAllUserStatsResponse` API schema.
 */
export interface ListAllUserStatsResponse {
  /**
   * The list of user statistics.
   */
  stats?: UserStats[];
}

/**
 * Typed representation of the `ListLinkedIdentitiesResponse` API schema.
 */
export interface ListLinkedIdentitiesResponse {
  /**
   * The list of linked identities.
   */
  linkedIdentities?: LinkedIdentity[];
}

/**
 * Typed representation of the `ListMemoViewsResponse` API schema.
 */
export interface ListMemoViewsResponse {
  /**
   * The list of memo views.
   */
  memoViews?: MemoView[];
}

/**
 * Typed representation of the `ListPersonalAccessTokensResponse` API schema.
 */
export interface ListPersonalAccessTokensResponse {
  /**
   * The list of personal access tokens.
   */
  personalAccessTokens?: PersonalAccessToken[];
  /**
   * A token for the next page of results.
   */
  nextPageToken?: string;
}

/**
 * Typed representation of the `ListUserNotificationsResponse` API schema.
 */
export interface ListUserNotificationsResponse {
  /**
   * Optional array value serialized in the `notifications` wire field.
   */
  notifications?: UserNotification[];
  /**
   * Optional `string` value serialized in the `nextPageToken` wire field.
   */
  nextPageToken?: string;
}

/**
 * Response message for ListUserSettings method.
 */
export interface ListUserSettingsResponse {
  /**
   * The list of user settings.
   */
  settings?: UserSetting[];
  /**
   * A token that can be sent as `page_token` to retrieve the next page.
   *  If this field is omitted, there are no subsequent pages.
   */
  nextPageToken?: string;
}

/**
 * Typed representation of the `ListUsersResponse` API schema.
 */
export interface ListUsersResponse {
  /**
   * The list of users.
   */
  users?: User[];
  /**
   * A token that can be sent as `page_token` to retrieve the next page.
   *  If this field is omitted, there are no subsequent pages.
   */
  nextPageToken?: string;
}

/**
 * Typed representation of the `ListUserWebhooksResponse` API schema.
 */
export interface ListUserWebhooksResponse {
  /**
   * The list of webhooks.
   */
  webhooks?: UserWebhook[];
}

/**
 * MemoImportIssue is one warning or failure of an import, tied to the memo
 *  UID from the archive when there is one.
 */
export interface MemoImportIssue {
  /**
   * The archive memo UID the issue concerns, if any.
   */
  memo?: string;
  /**
   * Optional `string` value serialized in the `message` wire field.
   */
  message?: string;
}

/**
 * MemoImportPlan describes what importing a staged archive would do.
 */
export interface MemoImportPlan {
  /**
   * When the archive was written.
   */
  exportTime?: string;
  /**
   * Username of the user who exported the archive.
   */
  exporter?: string;
  /**
   * The software that wrote the archive.
   */
  generator?: string;
  /**
   * Number of memo records in the archive.
   */
  memos?: number;
  /**
   * Number of attachment files in the archive.
   */
  attachments?: number;
  /**
   * Memos whose UID nobody on the instance holds.
   */
  new?: number;
  /**
   * Memos the user already holds; the conflict policy applies to them.
   */
  existing?: number;
  /**
   * Memos whose UID another account holds; they are imported under fresh UIDs.
   */
  renamed?: number;
  /**
   * Deviations the archive reader corrected while validating.
   */
  warnings?: MemoImportIssue[];
}

/**
 * MemoImportReport is the outcome of an import.
 */
export interface MemoImportReport {
  /**
   * Optional `int32`-formatted value serialized in the `created` wire field.
   */
  created?: number;
  /**
   * Optional `int32`-formatted value serialized in the `updated` wire field.
   */
  updated?: number;
  /**
   * Optional `int32`-formatted value serialized in the `skipped` wire field.
   */
  skipped?: number;
  /**
   * Optional `int32`-formatted value serialized in the `failed` wire field.
   */
  failed?: number;
  /**
   * Optional array value serialized in the `warnings` wire field.
   */
  warnings?: MemoImportIssue[];
  /**
   * One entry per failed memo, with the reason.
   */
  failures?: MemoImportIssue[];
}

/**
 * Saved memo view messages
 */
export interface MemoView {
  /**
   * The resource name of the memo view.
   *  Format: users/{user}/views/{view}
   */
  name?: string;
  /**
   * The title of the memo view.
   */
  title: string;
  /**
   * The CEL filter expression for the memo view, using the same grammar as the
   *  ListMemos `filter` argument. Reuse it by passing this value to ListMemos.
   */
  filter: string;
  /**
   * Optional. Display icon. Omit when updating with the "icon" mask to reset
   *  to the default view icon.
   */
  icon?: MemoView_Icon;
}

/**
 * Typed representation of the `MemoView_Icon` API schema.
 */
export interface MemoView_Icon {
  /**
   * A Unicode emoji sequence.
   */
  emoji?: string;
  /**
   * A canonical Lucide icon name, such as "leaf".
   */
  lucide?: string;
}

/**
 * PersonalAccessToken represents a long-lived token for API/script access.
 *  PATs are distinct from short-lived JWT access tokens used for session authentication.
 */
export interface PersonalAccessToken {
  /**
   * The resource name of the personal access token.
   *  Format: users/{user}/personalAccessTokens/{personal_access_token}
   */
  name?: string;
  /**
   * The description of the token.
   */
  description?: string;
  /**
   * Output only. The creation timestamp.
   */
  createdAt?: string;
  /**
   * Optional. The expiration timestamp.
   */
  expiresAt?: string;
  /**
   * Output only. The last used timestamp.
   */
  lastUsedAt?: string;
}

/**
 * Typed representation of the `UserNotification` API schema.
 */
export interface UserNotification {
  /**
   * The resource name of the notification.
   *  Format: users/{user}/notifications/{notification}
   */
  name?: string;
  /**
   * The sender of the notification.
   *  Format: users/{user}
   */
  sender?: string;
  /**
   * The sender user details.
   */
  senderUser?: User;
  /**
   * The status of the notification.
   */
  status?: "STATUS_UNSPECIFIED" | "UNREAD" | "ARCHIVED" | (string & {});
  /**
   * The creation timestamp.
   */
  createTime?: string;
  /**
   * The type of the notification.
   */
  type?: "TYPE_UNSPECIFIED" | "MEMO_COMMENT" | "MEMO_MENTION" | "SPACE_INVITATION" | (string & {});
  /**
   * Optional API value serialized in the `memoComment` wire field.
   */
  memoComment?: UserNotification_MemoCommentPayload;
  /**
   * Optional API value serialized in the `memoMention` wire field.
   */
  memoMention?: UserNotification_MemoMentionPayload;
  /**
   * Optional API value serialized in the `spaceInvitation` wire field.
   */
  spaceInvitation?: UserNotification_SpaceInvitationPayload;
}

/**
 * Typed representation of the `UserNotification_MemoCommentPayload` API schema.
 */
export interface UserNotification_MemoCommentPayload {
  /**
   * The memo name of comment.
   *  Format: memos/{memo}
   */
  memo?: string;
  /**
   * The name of related memo.
   *  Format: memos/{memo}
   */
  relatedMemo?: string;
  /**
   * Preview text of the comment memo.
   */
  memoSnippet?: string;
  /**
   * Preview text of the related memo.
   */
  relatedMemoSnippet?: string;
}

/**
 * Typed representation of the `UserNotification_MemoMentionPayload` API schema.
 */
export interface UserNotification_MemoMentionPayload {
  /**
   * The memo that contains the mention.
   *  Format: memos/{memo}
   */
  memo?: string;
  /**
   * The related parent memo when the mention was created in a comment.
   *  Format: memos/{memo}
   */
  relatedMemo?: string;
  /**
   * Preview text of the memo that contains the mention.
   */
  memoSnippet?: string;
  /**
   * Preview text of the related parent memo.
   */
  relatedMemoSnippet?: string;
}

/**
 * Typed representation of the `UserNotification_SpaceInvitationPayload` API schema.
 */
export interface UserNotification_SpaceInvitationPayload {
  /**
   * The invitation resource.
   *  Format: spaces/{space}/invitations/{username}
   */
  spaceInvitation?: string;
  /**
   * The read-only Space summary carried by the invitation.
   */
  space?: Space;
  /**
   * The role the invitation offers.
   */
  role?: "ROLE_UNSPECIFIED" | "ADMIN" | "USER" | (string & {});
  /**
   * The current state of the invitation for the receiver.
   */
  state?: "STATE_UNSPECIFIED" | "PENDING" | "ACCEPTED" | (string & {});
}
