// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { Color } from "./shared";

/**
 * User settings message
 */
export interface UserSetting {
  /**
   * The name of the user setting.
   *  Format: users/{user}/settings/{setting}, {setting} is the key for the setting.
   *  For example, "users/steven/settings/GENERAL" for general settings.
   */
  name?: string;
  /**
   * General user settings configuration.
   */
  generalSetting?: UserSetting_GeneralSetting;
  /**
   * User webhooks configuration.
   */
  webhooksSetting?: UserSetting_WebhooksSetting;
  /**
   * User-specific tag metadata.
   */
  tagsSetting?: UserSetting_TagsSetting;
}

/**
 * General user settings configuration.
 */
export interface UserSetting_GeneralSetting {
  /**
   * The preferred locale of the user.
   */
  locale?: string;
  /**
   * The default visibility of the memo.
   */
  memoVisibility?: string;
  /**
   * The preferred theme of the user.
   *  This references a CSS file in the web/public/themes/ directory.
   *  If not set, the default theme will be used.
   */
  theme?: string;
  /**
   * Whether the official client should save metadata from future media uploads.
   */
  saveMediaMetadata?: boolean;
}

/**
 * Tag metadata for user-specific display rules.
 */
export interface UserSetting_TagMetadata {
  /**
   * Optional background color for the tag label.
   *  When unset, the default tag color is used.
   */
  backgroundColor?: Color;
  /**
   * Whether memos with this tag should have their content blurred.
   */
  blurContent?: boolean;
}

/**
 * User-specific tag metadata.
 */
export interface UserSetting_TagsSetting {
  /**
   * Map of tag name pattern to tag metadata.
   *  Each key is treated as an anchored regular expression (^pattern$).
   */
  tags?: { [key: string]: UserSetting_TagMetadata };
}

/**
 * User webhooks configuration.
 */
export interface UserSetting_WebhooksSetting {
  /**
   * List of user webhooks.
   */
  webhooks?: UserWebhook[];
}

/**
 * User statistics messages
 */
export interface UserStats {
  /**
   * The resource name of the user statistics singleton.
   *  Format: users/{user}/stats
   */
  name?: string;
  /**
   * The stats of memo types.
   */
  memoTypeStats?: UserStats_MemoTypeStats;
  /**
   * The count of tags.
   */
  tagCount?: { [key: string]: number };
  /**
   * The creation timestamps of the user's memos.
   */
  memoCreatedTimestamps?: string[];
  /**
   * The latest update timestamps of the user's memos (one per memo,
   *  mirrors memo_created_timestamps). Used by the activity heatmap when
   *  the client's view is set to update_time basis.
   */
  memoUpdatedTimestamps?: string[];
  /**
   * The pinned memos of the user.
   */
  pinnedMemos?: string[];
  /**
   * Total memo count.
   */
  totalMemoCount?: number;
  /**
   * Total persisted attachment size in bytes, including unlinked uploads and
   *  attachments in all spaces. Excludes temporary uploads and derived files.
   *  Returned only by GetUserStats for the authenticated user's own stats,
   *  independently of the request's memo filter.
   */
  attachmentStorageBytes?: string;
}

/**
 * Memo type statistics.
 */
export interface UserStats_MemoTypeStats {
  /**
   * Optional `int32`-formatted value serialized in the `linkCount` wire field.
   */
  linkCount?: number;
  /**
   * Optional `int32`-formatted value serialized in the `codeCount` wire field.
   */
  codeCount?: number;
  /**
   * Optional `int32`-formatted value serialized in the `todoCount` wire field.
   */
  todoCount?: number;
  /**
   * Optional `int32`-formatted value serialized in the `undoCount` wire field.
   */
  undoCount?: number;
}

/**
 * UserWebhook represents a webhook owned by a user.
 */
export interface UserWebhook {
  /**
   * The name of the webhook.
   *  Format: users/{user}/webhooks/{webhook}
   */
  name?: string;
  /**
   * The URL to send the webhook to.
   */
  url?: string;
  /**
   * Optional. Human-readable name for the webhook.
   */
  displayName?: string;
  /**
   * The creation time of the webhook.
   */
  createTime?: string;
  /**
   * The last update time of the webhook.
   */
  updateTime?: string;
  /**
   * Optional. Signing secret used to HMAC-SHA256 sign the webhook request body.
   *  This field is input-only; it is never returned in responses.
   */
  signingSecret?: string;
  /**
   * Whether a signing secret is configured for this webhook.
   */
  signingSecretSet?: boolean;
}
