// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import assert from "node:assert/strict";
import test from "node:test";

import {
  argumentsFor,
  echoedKeys,
  expectedResponses,
  matchesBytes,
  matchesExpected,
  matchesPagedExpected,
  routeFor,
  startMockServer,
} from "../../helpers/mock-sdk.mjs";
import { configureClient } from "../../../dist/client.js";
import { SdkHttpError } from "../../../dist/errors.js";
import {
  memoServiceListMemos,
  memoServiceCreateMemo,
  memoServiceGetLinkMetadata,
  memoServiceBatchGetLinkMetadata,
  memoServiceGetMemo,
  memoServiceDeleteMemo,
  memoServiceUpdateMemo,
  memoServiceListMemoAttachments,
  memoServiceSetMemoAttachments,
  memoServiceListMemoComments,
  memoServiceCreateMemoComment,
  memoServiceListMemoReactions,
  memoServiceUpsertMemoReaction,
} from "../../../dist/methods/memoService/part1.js";

// Assigned once the mock server has a port. Declared at module scope because
// the call map below is built here too, and a config-first SDK's call
// expressions reference `config` as their first argument — a `const` inside
// the test body would leave those references unresolved at call time.
let config;

// operationId → how to call that method with a resolved argument bag. This is
// the generated part: it encodes each method's real signature (argument order
// for positional style, the params object otherwise).
const CALL = {
  memoServiceListMemos: {
    route: "MemoService_ListMemos",
    mediaType: null,
    invoke: (bag) =>
      memoServiceListMemos(config, {
        pageSize: bag["pageSize"],
        pageToken: bag["pageToken"],
        state: bag["state"],
        orderBy: bag["orderBy"],
        filter: bag["filter"],
        showDeleted: bag["showDeleted"],
      }),
  },
  memoServiceCreateMemo: {
    route: "MemoService_CreateMemo",
    mediaType: "application/json",
    invoke: (bag) =>
      memoServiceCreateMemo(config, {
        state: bag.__body?.["state"],
        content: bag.__body?.["content"],
        visibility: bag.__body?.["visibility"],
        name: bag.__body?.["name"],
        creator: bag.__body?.["creator"],
        createTime: bag.__body?.["createTime"],
        updateTime: bag.__body?.["updateTime"],
        tags: bag.__body?.["tags"],
        pinned: bag.__body?.["pinned"],
        attachments: bag.__body?.["attachments"],
        relations: bag.__body?.["relations"],
        reactions: bag.__body?.["reactions"],
        property: bag.__body?.["property"],
        parent: bag.__body?.["parent"],
        snippet: bag.__body?.["snippet"],
        location: bag.__body?.["location"],
        space: bag.__body?.["space"],
        memoId: bag["memoId"],
      }),
  },
  memoServiceGetLinkMetadata: {
    route: "MemoService_GetLinkMetadata",
    mediaType: null,
    invoke: (bag) => memoServiceGetLinkMetadata(config, { url: bag["url"] }),
  },
  memoServiceBatchGetLinkMetadata: {
    route: "MemoService_BatchGetLinkMetadata",
    mediaType: "application/json",
    invoke: (bag) => memoServiceBatchGetLinkMetadata(config, { urls: bag.__body?.["urls"] }),
  },
  memoServiceGetMemo: {
    route: "MemoService_GetMemo",
    mediaType: null,
    invoke: (bag) => memoServiceGetMemo(config, { memo: bag["memo"] }),
  },
  memoServiceDeleteMemo: {
    route: "MemoService_DeleteMemo",
    mediaType: null,
    invoke: (bag) => memoServiceDeleteMemo(config, { memo: bag["memo"], force: bag["force"] }),
  },
  memoServiceUpdateMemo: {
    route: "MemoService_UpdateMemo",
    mediaType: "application/json",
    invoke: (bag) =>
      memoServiceUpdateMemo(config, {
        state: bag.__body?.["state"],
        content: bag.__body?.["content"],
        visibility: bag.__body?.["visibility"],
        name: bag.__body?.["name"],
        creator: bag.__body?.["creator"],
        createTime: bag.__body?.["createTime"],
        updateTime: bag.__body?.["updateTime"],
        tags: bag.__body?.["tags"],
        pinned: bag.__body?.["pinned"],
        attachments: bag.__body?.["attachments"],
        relations: bag.__body?.["relations"],
        reactions: bag.__body?.["reactions"],
        property: bag.__body?.["property"],
        parent: bag.__body?.["parent"],
        snippet: bag.__body?.["snippet"],
        location: bag.__body?.["location"],
        space: bag.__body?.["space"],
        memo: bag["memo"],
        updateMask: bag["updateMask"],
      }),
  },
  memoServiceListMemoAttachments: {
    route: "MemoService_ListMemoAttachments",
    mediaType: null,
    invoke: (bag) =>
      memoServiceListMemoAttachments(config, {
        memo: bag["memo"],
        pageSize: bag["pageSize"],
        pageToken: bag["pageToken"],
      }),
  },
  memoServiceSetMemoAttachments: {
    route: "MemoService_SetMemoAttachments",
    mediaType: "application/json",
    invoke: (bag) =>
      memoServiceSetMemoAttachments(config, {
        name: bag.__body?.["name"],
        attachments: bag.__body?.["attachments"],
        memo: bag["memo"],
      }),
  },
  memoServiceListMemoComments: {
    route: "MemoService_ListMemoComments",
    mediaType: null,
    invoke: (bag) =>
      memoServiceListMemoComments(config, {
        memo: bag["memo"],
        pageSize: bag["pageSize"],
        pageToken: bag["pageToken"],
        orderBy: bag["orderBy"],
      }),
  },
  memoServiceCreateMemoComment: {
    route: "MemoService_CreateMemoComment",
    mediaType: "application/json",
    invoke: (bag) =>
      memoServiceCreateMemoComment(config, {
        state: bag.__body?.["state"],
        content: bag.__body?.["content"],
        visibility: bag.__body?.["visibility"],
        name: bag.__body?.["name"],
        creator: bag.__body?.["creator"],
        createTime: bag.__body?.["createTime"],
        updateTime: bag.__body?.["updateTime"],
        tags: bag.__body?.["tags"],
        pinned: bag.__body?.["pinned"],
        attachments: bag.__body?.["attachments"],
        relations: bag.__body?.["relations"],
        reactions: bag.__body?.["reactions"],
        property: bag.__body?.["property"],
        parent: bag.__body?.["parent"],
        snippet: bag.__body?.["snippet"],
        location: bag.__body?.["location"],
        space: bag.__body?.["space"],
        memo: bag["memo"],
        commentId: bag["commentId"],
      }),
  },
  memoServiceListMemoReactions: {
    route: "MemoService_ListMemoReactions",
    mediaType: null,
    invoke: (bag) =>
      memoServiceListMemoReactions(config, {
        memo: bag["memo"],
        pageSize: bag["pageSize"],
        pageToken: bag["pageToken"],
      }),
  },
  memoServiceUpsertMemoReaction: {
    route: "MemoService_UpsertMemoReaction",
    mediaType: "application/json",
    invoke: (bag) =>
      memoServiceUpsertMemoReaction(config, {
        name: bag.__body?.["name"],
        reaction: bag.__body?.["reaction"],
        memo: bag["memo"],
      }),
  },
};

test("memoService/part1 methods reach the mock server and decode its responses", async (t) => {
  const mock = await startMockServer();
  config = configureClient({ baseUrl: mock.baseUrl });
  void config;
  try {
    for (const [methodName, entry] of Object.entries(CALL)) {
      await t.test(methodName, async () => {
        const route = routeFor(entry.route);
        assert.ok(route, `no mock route for ${entry.route}`);

        let invocationError = null;
        let response;
        let streamed = false;
        try {
          const invoked = entry.invoke(argumentsFor(route, entry.mediaType));
          if (invoked?.[Symbol.asyncIterator]) {
            streamed = true;
            const events = [];
            // An auto-paginating method is an async generator over a static
            // mock: an example carrying has_more: true would never terminate.
            for await (const event of invoked) {
              events.push(event);
              if (events.length >= 50) break;
            }
            response = events.length === 1 ? events[0] : events;
          } else {
            response = await invoked;
          }
        } catch (error) {
          invocationError = error;
        }

        const expected = expectedResponses(route);
        if ((route.responseModes ?? []).length === 0) {
          assert.ok(
            invocationError instanceof SdkHttpError,
            `${methodName} should surface the declared non-2xx response as an HTTP error`,
          );
          return;
        }
        if (invocationError) throw invocationError;
        if (expected.length > 0) {
          assert.ok(
            expected.some(
              (mode) =>
                matchesBytes(response, mode) ||
                matchesExpected(response, mode.example, echoedKeys(route)) ||
                (streamed && matchesPagedExpected(response, mode.example, echoedKeys(route))),
            ),
            `${methodName} decoded a response matching none of its declared 2xx examples`,
          );
        }
      });
    }
  } finally {
    mock.stop();
  }
});
