// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import assert from "node:assert/strict";
import test from "node:test";

import {
  argumentsFor,
  echoedKeys,
  expectedResponses,
  matchesBytes,
  matchesExpected,
  matchesPagedExpected,
  routeFor,
  startMockServer,
} from "../helpers/mock-sdk.mjs";
import { configureClient } from "../../dist/client.js";
import { SdkHttpError } from "../../dist/errors.js";
import {
  attachmentServiceListAttachments,
  attachmentServiceCreateAttachment,
  attachmentServiceGetAttachment,
  attachmentServiceDeleteAttachment,
  attachmentServiceUpdateAttachment,
  attachmentServiceBatchDeleteAttachments,
  attachmentServiceUploadAttachment,
} from "../../dist/methods/attachmentService.js";

// Assigned once the mock server has a port. Declared at module scope because
// the call map below is built here too, and a config-first SDK's call
// expressions reference `config` as their first argument — a `const` inside
// the test body would leave those references unresolved at call time.
let config;

// operationId → how to call that method with a resolved argument bag. This is
// the generated part: it encodes each method's real signature (argument order
// for positional style, the params object otherwise).
const CALL = {
  attachmentServiceListAttachments: {
    route: "AttachmentService_ListAttachments",
    mediaType: null,
    invoke: (bag) =>
      attachmentServiceListAttachments(config, {
        pageSize: bag["pageSize"],
        pageToken: bag["pageToken"],
        filter: bag["filter"],
        orderBy: bag["orderBy"],
      }),
  },
  attachmentServiceCreateAttachment: {
    route: "AttachmentService_CreateAttachment",
    mediaType: "application/json",
    invoke: (bag) =>
      attachmentServiceCreateAttachment(config, {
        filename: bag.__body?.["filename"],
        ["type"]: bag.__body?.["type"],
        name: bag.__body?.["name"],
        createTime: bag.__body?.["createTime"],
        content: bag.__body?.["content"],
        externalLink: bag.__body?.["externalLink"],
        size: bag.__body?.["size"],
        memo: bag.__body?.["memo"],
        motionMedia: bag.__body?.["motionMedia"],
        mediaMetadata: bag.__body?.["mediaMetadata"],
        creator: bag.__body?.["creator"],
        attachmentId: bag["attachmentId"],
      }),
  },
  attachmentServiceGetAttachment: {
    route: "AttachmentService_GetAttachment",
    mediaType: null,
    invoke: (bag) => attachmentServiceGetAttachment(config, { attachment: bag["attachment"] }),
  },
  attachmentServiceDeleteAttachment: {
    route: "AttachmentService_DeleteAttachment",
    mediaType: null,
    invoke: (bag) => attachmentServiceDeleteAttachment(config, { attachment: bag["attachment"] }),
  },
  attachmentServiceUpdateAttachment: {
    route: "AttachmentService_UpdateAttachment",
    mediaType: "application/json",
    invoke: (bag) =>
      attachmentServiceUpdateAttachment(config, {
        filename: bag.__body?.["filename"],
        ["type"]: bag.__body?.["type"],
        name: bag.__body?.["name"],
        createTime: bag.__body?.["createTime"],
        content: bag.__body?.["content"],
        externalLink: bag.__body?.["externalLink"],
        size: bag.__body?.["size"],
        memo: bag.__body?.["memo"],
        motionMedia: bag.__body?.["motionMedia"],
        mediaMetadata: bag.__body?.["mediaMetadata"],
        creator: bag.__body?.["creator"],
        attachment: bag["attachment"],
        updateMask: bag["updateMask"],
      }),
  },
  attachmentServiceBatchDeleteAttachments: {
    route: "AttachmentService_BatchDeleteAttachments",
    mediaType: "application/json",
    invoke: (bag) =>
      attachmentServiceBatchDeleteAttachments(config, { names: bag.__body?.["names"] }),
  },
  attachmentServiceUploadAttachment: {
    route: "AttachmentService_UploadAttachment",
    mediaType: "application/json",
    invoke: (bag) =>
      attachmentServiceUploadAttachment(config, {
        writeOffset: bag.__body?.["writeOffset"],
        spec: bag.__body?.["spec"],
        uploadId: bag.__body?.["uploadId"],
        data: bag.__body?.["data"],
        finishWrite: bag.__body?.["finishWrite"],
      }),
  },
};

test("attachmentService methods reach the mock server and decode its responses", async (t) => {
  const mock = await startMockServer();
  config = configureClient({ baseUrl: mock.baseUrl });
  void config;
  try {
    for (const [methodName, entry] of Object.entries(CALL)) {
      await t.test(methodName, async () => {
        const route = routeFor(entry.route);
        assert.ok(route, `no mock route for ${entry.route}`);

        let invocationError = null;
        let response;
        let streamed = false;
        try {
          const invoked = entry.invoke(argumentsFor(route, entry.mediaType));
          if (invoked?.[Symbol.asyncIterator]) {
            streamed = true;
            const events = [];
            // An auto-paginating method is an async generator over a static
            // mock: an example carrying has_more: true would never terminate.
            for await (const event of invoked) {
              events.push(event);
              if (events.length >= 50) break;
            }
            response = events.length === 1 ? events[0] : events;
          } else {
            response = await invoked;
          }
        } catch (error) {
          invocationError = error;
        }

        const expected = expectedResponses(route);
        if ((route.responseModes ?? []).length === 0) {
          assert.ok(
            invocationError instanceof SdkHttpError,
            `${methodName} should surface the declared non-2xx response as an HTTP error`,
          );
          return;
        }
        if (invocationError) throw invocationError;
        if (expected.length > 0) {
          assert.ok(
            expected.some(
              (mode) =>
                matchesBytes(response, mode) ||
                matchesExpected(response, mode.example, echoedKeys(route)) ||
                (streamed && matchesPagedExpected(response, mode.example, echoedKeys(route))),
            ),
            `${methodName} decoded a response matching none of its declared 2xx examples`,
          );
        }
      });
    }
  } finally {
    mock.stop();
  }
});
