// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import assert from "node:assert/strict";
import test from "node:test";

import {
  argumentsFor,
  echoedKeys,
  expectedResponses,
  matchesBytes,
  matchesExpected,
  matchesPagedExpected,
  routeFor,
  startMockServer,
} from "../helpers/mock-sdk.mjs";
import { configureClient } from "../../dist/client.js";
import { SdkHttpError } from "../../dist/errors.js";
import {
  spaceServiceListSpaces,
  spaceServiceCreateSpace,
  spaceServiceGetSpace,
  spaceServiceDeleteSpace,
  spaceServiceUpdateSpace,
  spaceServiceListSpaceInvitations,
  spaceServiceCreateSpaceInvitation,
  spaceServiceGetSpaceInvitation,
  spaceServiceDeleteSpaceInvitation,
  spaceServiceAcceptSpaceInvitation,
  spaceServiceDeclineSpaceInvitation,
  spaceServiceListSpaceMembers,
  spaceServiceGetSpaceMember,
  spaceServiceDeleteSpaceMember,
  spaceServiceUpdateSpaceMember,
  spaceServiceListUserSpaceInvitations,
} from "../../dist/methods/spaceService.js";

// Assigned once the mock server has a port. Declared at module scope because
// the call map below is built here too, and a config-first SDK's call
// expressions reference `config` as their first argument — a `const` inside
// the test body would leave those references unresolved at call time.
let config;

// operationId → how to call that method with a resolved argument bag. This is
// the generated part: it encodes each method's real signature (argument order
// for positional style, the params object otherwise).
const CALL = {
  spaceServiceListSpaces: {
    route: "SpaceService_ListSpaces",
    mediaType: null,
    invoke: (bag) =>
      spaceServiceListSpaces(config, { pageSize: bag["pageSize"], pageToken: bag["pageToken"] }),
  },
  spaceServiceCreateSpace: {
    route: "SpaceService_CreateSpace",
    mediaType: "application/json",
    invoke: (bag) =>
      spaceServiceCreateSpace(config, {
        title: bag.__body?.["title"],
        name: bag.__body?.["name"],
        description: bag.__body?.["description"],
        currentUserRole: bag.__body?.["currentUserRole"],
        memberCount: bag.__body?.["memberCount"],
        icon: bag.__body?.["icon"],
        spaceId: bag["spaceId"],
      }),
  },
  spaceServiceGetSpace: {
    route: "SpaceService_GetSpace",
    mediaType: null,
    invoke: (bag) => spaceServiceGetSpace(config, { space: bag["space"] }),
  },
  spaceServiceDeleteSpace: {
    route: "SpaceService_DeleteSpace",
    mediaType: null,
    invoke: (bag) => spaceServiceDeleteSpace(config, { space: bag["space"] }),
  },
  spaceServiceUpdateSpace: {
    route: "SpaceService_UpdateSpace",
    mediaType: "application/json",
    invoke: (bag) =>
      spaceServiceUpdateSpace(config, {
        title: bag.__body?.["title"],
        name: bag.__body?.["name"],
        description: bag.__body?.["description"],
        currentUserRole: bag.__body?.["currentUserRole"],
        memberCount: bag.__body?.["memberCount"],
        icon: bag.__body?.["icon"],
        space: bag["space"],
        updateMask: bag["updateMask"],
      }),
  },
  spaceServiceListSpaceInvitations: {
    route: "SpaceService_ListSpaceInvitations",
    mediaType: null,
    invoke: (bag) =>
      spaceServiceListSpaceInvitations(config, {
        space: bag["space"],
        pageSize: bag["pageSize"],
        pageToken: bag["pageToken"],
      }),
  },
  spaceServiceCreateSpaceInvitation: {
    route: "SpaceService_CreateSpaceInvitation",
    mediaType: "application/json",
    invoke: (bag) =>
      spaceServiceCreateSpaceInvitation(config, {
        invitee: bag.__body?.["invitee"],
        role: bag.__body?.["role"],
        name: bag.__body?.["name"],
        space_2: bag.__body?.["space"],
        space: bag["space"],
      }),
  },
  spaceServiceGetSpaceInvitation: {
    route: "SpaceService_GetSpaceInvitation",
    mediaType: null,
    invoke: (bag) =>
      spaceServiceGetSpaceInvitation(config, {
        space: bag["space"],
        invitation: bag["invitation"],
      }),
  },
  spaceServiceDeleteSpaceInvitation: {
    route: "SpaceService_DeleteSpaceInvitation",
    mediaType: null,
    invoke: (bag) =>
      spaceServiceDeleteSpaceInvitation(config, {
        space: bag["space"],
        invitation: bag["invitation"],
      }),
  },
  spaceServiceAcceptSpaceInvitation: {
    route: "SpaceService_AcceptSpaceInvitation",
    mediaType: "application/json",
    invoke: (bag) =>
      spaceServiceAcceptSpaceInvitation(config, {
        name: bag.__body?.["name"],
        space: bag["space"],
        invitation: bag["invitation"],
      }),
  },
  spaceServiceDeclineSpaceInvitation: {
    route: "SpaceService_DeclineSpaceInvitation",
    mediaType: "application/json",
    invoke: (bag) =>
      spaceServiceDeclineSpaceInvitation(config, {
        name: bag.__body?.["name"],
        space: bag["space"],
        invitation: bag["invitation"],
      }),
  },
  spaceServiceListSpaceMembers: {
    route: "SpaceService_ListSpaceMembers",
    mediaType: null,
    invoke: (bag) =>
      spaceServiceListSpaceMembers(config, {
        space: bag["space"],
        pageSize: bag["pageSize"],
        pageToken: bag["pageToken"],
      }),
  },
  spaceServiceGetSpaceMember: {
    route: "SpaceService_GetSpaceMember",
    mediaType: null,
    invoke: (bag) =>
      spaceServiceGetSpaceMember(config, { space: bag["space"], member: bag["member"] }),
  },
  spaceServiceDeleteSpaceMember: {
    route: "SpaceService_DeleteSpaceMember",
    mediaType: null,
    invoke: (bag) =>
      spaceServiceDeleteSpaceMember(config, { space: bag["space"], member: bag["member"] }),
  },
  spaceServiceUpdateSpaceMember: {
    route: "SpaceService_UpdateSpaceMember",
    mediaType: "application/json",
    invoke: (bag) =>
      spaceServiceUpdateSpaceMember(config, {
        user: bag.__body?.["user"],
        role: bag.__body?.["role"],
        name: bag.__body?.["name"],
        space: bag["space"],
        member: bag["member"],
        updateMask: bag["updateMask"],
      }),
  },
  spaceServiceListUserSpaceInvitations: {
    route: "SpaceService_ListUserSpaceInvitations",
    mediaType: null,
    invoke: (bag) =>
      spaceServiceListUserSpaceInvitations(config, {
        user: bag["user"],
        pageSize: bag["pageSize"],
        pageToken: bag["pageToken"],
      }),
  },
};

test("spaceService methods reach the mock server and decode its responses", async (t) => {
  const mock = await startMockServer();
  config = configureClient({ baseUrl: mock.baseUrl });
  void config;
  try {
    for (const [methodName, entry] of Object.entries(CALL)) {
      await t.test(methodName, async () => {
        const route = routeFor(entry.route);
        assert.ok(route, `no mock route for ${entry.route}`);

        let invocationError = null;
        let response;
        let streamed = false;
        try {
          const invoked = entry.invoke(argumentsFor(route, entry.mediaType));
          if (invoked?.[Symbol.asyncIterator]) {
            streamed = true;
            const events = [];
            // An auto-paginating method is an async generator over a static
            // mock: an example carrying has_more: true would never terminate.
            for await (const event of invoked) {
              events.push(event);
              if (events.length >= 50) break;
            }
            response = events.length === 1 ? events[0] : events;
          } else {
            response = await invoked;
          }
        } catch (error) {
          invocationError = error;
        }

        const expected = expectedResponses(route);
        if ((route.responseModes ?? []).length === 0) {
          assert.ok(
            invocationError instanceof SdkHttpError,
            `${methodName} should surface the declared non-2xx response as an HTTP error`,
          );
          return;
        }
        if (invocationError) throw invocationError;
        if (expected.length > 0) {
          assert.ok(
            expected.some(
              (mode) =>
                matchesBytes(response, mode) ||
                matchesExpected(response, mode.example, echoedKeys(route)) ||
                (streamed && matchesPagedExpected(response, mode.example, echoedKeys(route))),
            ),
            `${methodName} decoded a response matching none of its declared 2xx examples`,
          );
        }
      });
    }
  } finally {
    mock.stop();
  }
});
