// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import assert from "node:assert/strict";
import test from "node:test";

import {
  argumentsFor,
  echoedKeys,
  expectedResponses,
  matchesBytes,
  matchesExpected,
  matchesPagedExpected,
  routeFor,
  startMockServer,
} from "../../helpers/mock-sdk.mjs";
import { configureClient } from "../../../dist/client.js";
import { SdkHttpError } from "../../../dist/errors.js";
import {
  userServiceListUserSettings,
  userServiceGetUserSetting,
  userServiceUpdateUserSetting,
  userServiceListMemoViews,
  userServiceCreateMemoView,
  userServiceGetMemoView,
  userServiceDeleteMemoView,
  userServiceUpdateMemoView,
  userServiceListUserWebhooks,
  userServiceCreateUserWebhook,
  userServiceDeleteUserWebhook,
  userServiceUpdateUserWebhook,
  userServiceGetUserWebhookSigningSecret,
  userServiceExportMemos,
  userServiceGetUserStats,
  userServiceImportMemos,
} from "../../../dist/methods/userService/part2.js";

// Assigned once the mock server has a port. Declared at module scope because
// the call map below is built here too, and a config-first SDK's call
// expressions reference `config` as their first argument — a `const` inside
// the test body would leave those references unresolved at call time.
let config;

// operationId → how to call that method with a resolved argument bag. This is
// the generated part: it encodes each method's real signature (argument order
// for positional style, the params object otherwise).
const CALL = {
  userServiceListUserSettings: {
    route: "UserService_ListUserSettings",
    mediaType: null,
    invoke: (bag) =>
      userServiceListUserSettings(config, {
        user: bag["user"],
        pageSize: bag["pageSize"],
        pageToken: bag["pageToken"],
      }),
  },
  userServiceGetUserSetting: {
    route: "UserService_GetUserSetting",
    mediaType: null,
    invoke: (bag) =>
      userServiceGetUserSetting(config, { user: bag["user"], setting: bag["setting"] }),
  },
  userServiceUpdateUserSetting: {
    route: "UserService_UpdateUserSetting",
    mediaType: "application/json",
    invoke: (bag) =>
      userServiceUpdateUserSetting(config, {
        name: bag.__body?.["name"],
        generalSetting: bag.__body?.["generalSetting"],
        webhooksSetting: bag.__body?.["webhooksSetting"],
        tagsSetting: bag.__body?.["tagsSetting"],
        user: bag["user"],
        setting: bag["setting"],
        updateMask: bag["updateMask"],
      }),
  },
  userServiceListMemoViews: {
    route: "UserService_ListMemoViews",
    mediaType: null,
    invoke: (bag) => userServiceListMemoViews(config, { user: bag["user"] }),
  },
  userServiceCreateMemoView: {
    route: "UserService_CreateMemoView",
    mediaType: "application/json",
    invoke: (bag) =>
      userServiceCreateMemoView(config, {
        title: bag.__body?.["title"],
        filter: bag.__body?.["filter"],
        name: bag.__body?.["name"],
        icon: bag.__body?.["icon"],
        user: bag["user"],
        validateOnly: bag["validateOnly"],
      }),
  },
  userServiceGetMemoView: {
    route: "UserService_GetMemoView",
    mediaType: null,
    invoke: (bag) => userServiceGetMemoView(config, { user: bag["user"], view: bag["view"] }),
  },
  userServiceDeleteMemoView: {
    route: "UserService_DeleteMemoView",
    mediaType: null,
    invoke: (bag) => userServiceDeleteMemoView(config, { user: bag["user"], view: bag["view"] }),
  },
  userServiceUpdateMemoView: {
    route: "UserService_UpdateMemoView",
    mediaType: "application/json",
    invoke: (bag) =>
      userServiceUpdateMemoView(config, {
        title: bag.__body?.["title"],
        filter: bag.__body?.["filter"],
        name: bag.__body?.["name"],
        icon: bag.__body?.["icon"],
        user: bag["user"],
        view: bag["view"],
        updateMask: bag["updateMask"],
      }),
  },
  userServiceListUserWebhooks: {
    route: "UserService_ListUserWebhooks",
    mediaType: null,
    invoke: (bag) => userServiceListUserWebhooks(config, { user: bag["user"] }),
  },
  userServiceCreateUserWebhook: {
    route: "UserService_CreateUserWebhook",
    mediaType: "application/json",
    invoke: (bag) =>
      userServiceCreateUserWebhook(config, {
        name: bag.__body?.["name"],
        url: bag.__body?.["url"],
        displayName: bag.__body?.["displayName"],
        createTime: bag.__body?.["createTime"],
        updateTime: bag.__body?.["updateTime"],
        signingSecret: bag.__body?.["signingSecret"],
        signingSecretSet: bag.__body?.["signingSecretSet"],
        user: bag["user"],
      }),
  },
  userServiceDeleteUserWebhook: {
    route: "UserService_DeleteUserWebhook",
    mediaType: null,
    invoke: (bag) =>
      userServiceDeleteUserWebhook(config, { user: bag["user"], webhook: bag["webhook"] }),
  },
  userServiceUpdateUserWebhook: {
    route: "UserService_UpdateUserWebhook",
    mediaType: "application/json",
    invoke: (bag) =>
      userServiceUpdateUserWebhook(config, {
        name: bag.__body?.["name"],
        url: bag.__body?.["url"],
        displayName: bag.__body?.["displayName"],
        createTime: bag.__body?.["createTime"],
        updateTime: bag.__body?.["updateTime"],
        signingSecret: bag.__body?.["signingSecret"],
        signingSecretSet: bag.__body?.["signingSecretSet"],
        user: bag["user"],
        webhook: bag["webhook"],
        updateMask: bag["updateMask"],
      }),
  },
  userServiceGetUserWebhookSigningSecret: {
    route: "UserService_GetUserWebhookSigningSecret",
    mediaType: null,
    invoke: (bag) =>
      userServiceGetUserWebhookSigningSecret(config, {
        user: bag["user"],
        webhook: bag["webhook"],
      }),
  },
  userServiceExportMemos: {
    route: "UserService_ExportMemos",
    mediaType: null,
    invoke: (bag) => userServiceExportMemos(config, { user: bag["user"] }),
  },
  userServiceGetUserStats: {
    route: "UserService_GetUserStats",
    mediaType: null,
    invoke: (bag) => userServiceGetUserStats(config, { user: bag["user"], filter: bag["filter"] }),
  },
  userServiceImportMemos: {
    route: "UserService_ImportMemos",
    mediaType: "application/json",
    invoke: (bag) =>
      userServiceImportMemos(config, {
        name: bag.__body?.["name"],
        writeOffset: bag.__body?.["writeOffset"],
        spec: bag.__body?.["spec"],
        uploadId: bag.__body?.["uploadId"],
        data: bag.__body?.["data"],
        finishWrite: bag.__body?.["finishWrite"],
        validateOnly: bag.__body?.["validateOnly"],
        conflictPolicy: bag.__body?.["conflictPolicy"],
        user: bag["user"],
      }),
  },
};

test("userService/part2 methods reach the mock server and decode its responses", async (t) => {
  const mock = await startMockServer();
  config = configureClient({ baseUrl: mock.baseUrl });
  void config;
  try {
    for (const [methodName, entry] of Object.entries(CALL)) {
      await t.test(methodName, async () => {
        const route = routeFor(entry.route);
        assert.ok(route, `no mock route for ${entry.route}`);

        let invocationError = null;
        let response;
        let streamed = false;
        try {
          const invoked = entry.invoke(argumentsFor(route, entry.mediaType));
          if (invoked?.[Symbol.asyncIterator]) {
            streamed = true;
            const events = [];
            // An auto-paginating method is an async generator over a static
            // mock: an example carrying has_more: true would never terminate.
            for await (const event of invoked) {
              events.push(event);
              if (events.length >= 50) break;
            }
            response = events.length === 1 ? events[0] : events;
          } else {
            response = await invoked;
          }
        } catch (error) {
          invocationError = error;
        }

        const expected = expectedResponses(route);
        if ((route.responseModes ?? []).length === 0) {
          assert.ok(
            invocationError instanceof SdkHttpError,
            `${methodName} should surface the declared non-2xx response as an HTTP error`,
          );
          return;
        }
        if (invocationError) throw invocationError;
        if (expected.length > 0) {
          assert.ok(
            expected.some(
              (mode) =>
                matchesBytes(response, mode) ||
                matchesExpected(response, mode.example, echoedKeys(route)) ||
                (streamed && matchesPagedExpected(response, mode.example, echoedKeys(route))),
            ),
            `${methodName} decoded a response matching none of its declared 2xx examples`,
          );
        }
      });
    }
  } finally {
    mock.stop();
  }
});
