// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import assert from "node:assert/strict";
import test from "node:test";

import {
  argumentsFor,
  echoedKeys,
  expectedResponses,
  matchesBytes,
  matchesExpected,
  matchesPagedExpected,
  routeFor,
  startMockServer,
} from "../../helpers/mock-sdk.mjs";
import { configureClient } from "../../../dist/client.js";
import { SdkHttpError } from "../../../dist/errors.js";
import {
  userServiceListUsers,
  userServiceCreateUser,
  userServiceGetUser,
  userServiceDeleteUser,
  userServiceUpdateUser,
  userServiceListLinkedIdentities,
  userServiceCreateLinkedIdentity,
  userServiceGetLinkedIdentity,
  userServiceDeleteLinkedIdentity,
  userServiceListUserNotifications,
  userServiceDeleteUserNotification,
  userServiceUpdateUserNotification,
  userServiceListPersonalAccessTokens,
  userServiceCreatePersonalAccessToken,
  userServiceDeletePersonalAccessToken,
} from "../../../dist/methods/userService/part1.js";

// Assigned once the mock server has a port. Declared at module scope because
// the call map below is built here too, and a config-first SDK's call
// expressions reference `config` as their first argument — a `const` inside
// the test body would leave those references unresolved at call time.
let config;

// operationId → how to call that method with a resolved argument bag. This is
// the generated part: it encodes each method's real signature (argument order
// for positional style, the params object otherwise).
const CALL = {
  userServiceListUsers: {
    route: "UserService_ListUsers",
    mediaType: null,
    invoke: (bag) =>
      userServiceListUsers(config, {
        pageSize: bag["pageSize"],
        pageToken: bag["pageToken"],
        filter: bag["filter"],
        showDeleted: bag["showDeleted"],
      }),
  },
  userServiceCreateUser: {
    route: "UserService_CreateUser",
    mediaType: "application/json",
    invoke: (bag) =>
      userServiceCreateUser(config, {
        role: bag.__body?.["role"],
        username: bag.__body?.["username"],
        state: bag.__body?.["state"],
        name: bag.__body?.["name"],
        email: bag.__body?.["email"],
        displayName: bag.__body?.["displayName"],
        avatarUrl: bag.__body?.["avatarUrl"],
        description: bag.__body?.["description"],
        password: bag.__body?.["password"],
        createTime: bag.__body?.["createTime"],
        updateTime: bag.__body?.["updateTime"],
        userId: bag["userId"],
        validateOnly: bag["validateOnly"],
        requestId: bag["requestId"],
      }),
  },
  userServiceGetUser: {
    route: "UserService_GetUser",
    mediaType: null,
    invoke: (bag) => userServiceGetUser(config, { user: bag["user"], readMask: bag["readMask"] }),
  },
  userServiceDeleteUser: {
    route: "UserService_DeleteUser",
    mediaType: null,
    invoke: (bag) => userServiceDeleteUser(config, { user: bag["user"], force: bag["force"] }),
  },
  userServiceUpdateUser: {
    route: "UserService_UpdateUser",
    mediaType: "application/json",
    invoke: (bag) =>
      userServiceUpdateUser(config, {
        role: bag.__body?.["role"],
        username: bag.__body?.["username"],
        state: bag.__body?.["state"],
        name: bag.__body?.["name"],
        email: bag.__body?.["email"],
        displayName: bag.__body?.["displayName"],
        avatarUrl: bag.__body?.["avatarUrl"],
        description: bag.__body?.["description"],
        password: bag.__body?.["password"],
        createTime: bag.__body?.["createTime"],
        updateTime: bag.__body?.["updateTime"],
        user: bag["user"],
        updateMask: bag["updateMask"],
        allowMissing: bag["allowMissing"],
      }),
  },
  userServiceListLinkedIdentities: {
    route: "UserService_ListLinkedIdentities",
    mediaType: null,
    invoke: (bag) => userServiceListLinkedIdentities(config, { user: bag["user"] }),
  },
  userServiceCreateLinkedIdentity: {
    route: "UserService_CreateLinkedIdentity",
    mediaType: "application/json",
    invoke: (bag) =>
      userServiceCreateLinkedIdentity(config, {
        parent: bag.__body?.["parent"],
        idpName: bag.__body?.["idpName"],
        code: bag.__body?.["code"],
        redirectUri: bag.__body?.["redirectUri"],
        codeVerifier: bag.__body?.["codeVerifier"],
        user: bag["user"],
      }),
  },
  userServiceGetLinkedIdentity: {
    route: "UserService_GetLinkedIdentity",
    mediaType: null,
    invoke: (bag) =>
      userServiceGetLinkedIdentity(config, {
        user: bag["user"],
        linkedIdentity: bag["linkedIdentity"],
      }),
  },
  userServiceDeleteLinkedIdentity: {
    route: "UserService_DeleteLinkedIdentity",
    mediaType: null,
    invoke: (bag) =>
      userServiceDeleteLinkedIdentity(config, {
        user: bag["user"],
        linkedIdentity: bag["linkedIdentity"],
      }),
  },
  userServiceListUserNotifications: {
    route: "UserService_ListUserNotifications",
    mediaType: null,
    invoke: (bag) =>
      userServiceListUserNotifications(config, {
        user: bag["user"],
        pageSize: bag["pageSize"],
        pageToken: bag["pageToken"],
        filter: bag["filter"],
      }),
  },
  userServiceDeleteUserNotification: {
    route: "UserService_DeleteUserNotification",
    mediaType: null,
    invoke: (bag) =>
      userServiceDeleteUserNotification(config, {
        user: bag["user"],
        notification: bag["notification"],
      }),
  },
  userServiceUpdateUserNotification: {
    route: "UserService_UpdateUserNotification",
    mediaType: "application/json",
    invoke: (bag) =>
      userServiceUpdateUserNotification(config, {
        name: bag.__body?.["name"],
        sender: bag.__body?.["sender"],
        senderUser: bag.__body?.["senderUser"],
        status: bag.__body?.["status"],
        createTime: bag.__body?.["createTime"],
        ["type"]: bag.__body?.["type"],
        memoComment: bag.__body?.["memoComment"],
        memoMention: bag.__body?.["memoMention"],
        spaceInvitation: bag.__body?.["spaceInvitation"],
        user: bag["user"],
        notification: bag["notification"],
        updateMask: bag["updateMask"],
      }),
  },
  userServiceListPersonalAccessTokens: {
    route: "UserService_ListPersonalAccessTokens",
    mediaType: null,
    invoke: (bag) =>
      userServiceListPersonalAccessTokens(config, {
        user: bag["user"],
        pageSize: bag["pageSize"],
        pageToken: bag["pageToken"],
      }),
  },
  userServiceCreatePersonalAccessToken: {
    route: "UserService_CreatePersonalAccessToken",
    mediaType: "application/json",
    invoke: (bag) =>
      userServiceCreatePersonalAccessToken(config, {
        parent: bag.__body?.["parent"],
        description: bag.__body?.["description"],
        expiresInDays: bag.__body?.["expiresInDays"],
        user: bag["user"],
      }),
  },
  userServiceDeletePersonalAccessToken: {
    route: "UserService_DeletePersonalAccessToken",
    mediaType: null,
    invoke: (bag) =>
      userServiceDeletePersonalAccessToken(config, {
        user: bag["user"],
        personalAccessToken: bag["personalAccessToken"],
      }),
  },
};

test("userService/part1 methods reach the mock server and decode its responses", async (t) => {
  const mock = await startMockServer();
  config = configureClient({ baseUrl: mock.baseUrl });
  void config;
  try {
    for (const [methodName, entry] of Object.entries(CALL)) {
      await t.test(methodName, async () => {
        const route = routeFor(entry.route);
        assert.ok(route, `no mock route for ${entry.route}`);

        let invocationError = null;
        let response;
        let streamed = false;
        try {
          const invoked = entry.invoke(argumentsFor(route, entry.mediaType));
          if (invoked?.[Symbol.asyncIterator]) {
            streamed = true;
            const events = [];
            // An auto-paginating method is an async generator over a static
            // mock: an example carrying has_more: true would never terminate.
            for await (const event of invoked) {
              events.push(event);
              if (events.length >= 50) break;
            }
            response = events.length === 1 ? events[0] : events;
          } else {
            response = await invoked;
          }
        } catch (error) {
          invocationError = error;
        }

        const expected = expectedResponses(route);
        if ((route.responseModes ?? []).length === 0) {
          assert.ok(
            invocationError instanceof SdkHttpError,
            `${methodName} should surface the declared non-2xx response as an HTTP error`,
          );
          return;
        }
        if (invocationError) throw invocationError;
        if (expected.length > 0) {
          assert.ok(
            expected.some(
              (mode) =>
                matchesBytes(response, mode) ||
                matchesExpected(response, mode.example, echoedKeys(route)) ||
                (streamed && matchesPagedExpected(response, mode.example, echoedKeys(route))),
            ),
            `${methodName} decoded a response matching none of its declared 2xx examples`,
          );
        }
      });
    }
  } finally {
    mock.stop();
  }
});
