// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { SdkValidationError } from "./errors";

import { validateDateTime } from "./validation";

type RuntimeRecord = Record<string, unknown>;

interface RuntimeSchema {
  ref?: string;
  type?: string | readonly string[];
  nullable?: boolean;
  enum?: readonly unknown[];
  required?: readonly string[];
  properties?: Readonly<Record<string, RuntimeSchema>>;
  items?: RuntimeSchema;
  additionalProperties?: RuntimeSchema;
  oneOf?: readonly RuntimeSchema[];
  anyOf?: readonly RuntimeSchema[];
  allOf?: readonly RuntimeSchema[];
  minimum?: number;
  maximum?: number;
  exclusiveMinimum?: number | boolean;
  exclusiveMaximum?: number | boolean;
  multipleOf?: number;
  minLength?: number;
  maxLength?: number;
  minItems?: number;
  maxItems?: number;
  pattern?: string;
  format?: "email" | "uri" | "uuid" | "date" | "date-time";
}

const modelSchemas: Readonly<Record<string, RuntimeSchema>> = {
  AcceptSpaceInvitationRequest: { type: "object", required: ["name"] },
  Attachment: {
    type: "object",
    required: ["filename", "type"],
    properties: {
      createTime: { type: "string", format: "date-time" },
      motionMedia: { allOf: [{ ref: "MotionMedia" }] },
    },
  },
  BatchDeleteAttachmentsRequest: { type: "object", required: ["names"] },
  BatchGetInstanceSettingsRequest: { type: "object", required: ["names"] },
  BatchGetInstanceSettingsResponse: {
    type: "object",
    properties: { settings: { type: "array", items: { ref: "InstanceSetting" } } },
  },
  BatchGetLinkMetadataRequest: { type: "object", required: ["urls"] },
  BatchGetUsersResponse: {
    type: "object",
    properties: { users: { type: "array", items: { ref: "User" } } },
  },
  CreateLinkedIdentityRequest: {
    type: "object",
    required: ["parent", "idpName", "code", "redirectUri"],
  },
  CreatePersonalAccessTokenRequest: { type: "object", required: ["parent"] },
  CreatePersonalAccessTokenResponse: {
    type: "object",
    properties: { personalAccessToken: { allOf: [{ ref: "PersonalAccessToken" }] } },
  },
  DeclineSpaceInvitationRequest: { type: "object", required: ["name"] },
  GetCurrentUserResponse: { type: "object", properties: { user: { allOf: [{ ref: "User" }] } } },
  IdentityProvider: { type: "object", required: ["type", "title", "config"] },
  ImportMemosRequest: { type: "object", required: ["name", "writeOffset"] },
  ImportMemosResponse: {
    type: "object",
    properties: { plan: { allOf: [{ ref: "MemoImportPlan" }] } },
  },
  InstanceProfile: { type: "object", properties: { admin: { allOf: [{ ref: "User" }] } } },
  InstanceSetting: {
    type: "object",
    properties: {
      storageSetting: { ref: "InstanceSetting_StorageSetting" },
      aiSetting: { ref: "InstanceSetting_AISetting" },
      accessSetting: { ref: "InstanceSetting_AccessSetting" },
    },
  },
  InstanceSetting_AISetting: {
    type: "object",
    properties: {
      providers: { type: "array", items: { ref: "InstanceSetting_AIProviderConfig" } },
    },
  },
  InstanceSetting_StorageSetting: {
    type: "object",
    properties: { storages: { type: "array", items: { ref: "InstanceSetting_Storage" } } },
  },
  InstanceStats: {
    type: "object",
    properties: { generatedTime: { type: "string", format: "date-time" } },
  },
  ListAllUserStatsResponse: {
    type: "object",
    properties: { stats: { type: "array", items: { ref: "UserStats" } } },
  },
  ListAttachmentsResponse: {
    type: "object",
    properties: { attachments: { type: "array", items: { ref: "Attachment" } } },
  },
  ListIdentityProvidersResponse: {
    type: "object",
    properties: { identityProviders: { type: "array", items: { ref: "IdentityProvider" } } },
  },
  ListMemoAttachmentsResponse: {
    type: "object",
    properties: { attachments: { type: "array", items: { ref: "Attachment" } } },
  },
  ListMemoCommentsResponse: {
    type: "object",
    properties: { memos: { type: "array", items: { ref: "Memo" } } },
  },
  ListMemoReactionsResponse: {
    type: "object",
    properties: { reactions: { type: "array", items: { ref: "Reaction" } } },
  },
  ListMemoRelationsResponse: {
    type: "object",
    properties: { relations: { type: "array", items: { ref: "MemoRelation" } } },
  },
  ListMemoSharesResponse: {
    type: "object",
    properties: { memoShares: { type: "array", items: { ref: "MemoShare" } } },
  },
  ListMemoViewsResponse: {
    type: "object",
    properties: { memoViews: { type: "array", items: { ref: "MemoView" } } },
  },
  ListMemosResponse: {
    type: "object",
    properties: { memos: { type: "array", items: { ref: "Memo" } } },
  },
  ListPersonalAccessTokensResponse: {
    type: "object",
    properties: { personalAccessTokens: { type: "array", items: { ref: "PersonalAccessToken" } } },
  },
  ListSpaceInvitationsResponse: {
    type: "object",
    properties: { spaceInvitations: { type: "array", items: { ref: "SpaceInvitation" } } },
  },
  ListSpaceMembersResponse: {
    type: "object",
    properties: { spaceMembers: { type: "array", items: { ref: "SpaceMember" } } },
  },
  ListSpacesResponse: {
    type: "object",
    properties: { spaces: { type: "array", items: { ref: "Space" } } },
  },
  ListUserNotificationsResponse: {
    type: "object",
    properties: { notifications: { type: "array", items: { ref: "UserNotification" } } },
  },
  ListUserSettingsResponse: {
    type: "object",
    properties: { settings: { type: "array", items: { ref: "UserSetting" } } },
  },
  ListUserSpaceInvitationsResponse: {
    type: "object",
    properties: { spaceInvitations: { type: "array", items: { ref: "SpaceInvitation" } } },
  },
  ListUserWebhooksResponse: {
    type: "object",
    properties: { webhooks: { type: "array", items: { ref: "UserWebhook" } } },
  },
  ListUsersResponse: {
    type: "object",
    properties: { users: { type: "array", items: { ref: "User" } } },
  },
  Memo: {
    type: "object",
    required: ["state", "content", "visibility"],
    properties: {
      createTime: { type: "string", format: "date-time" },
      updateTime: { type: "string", format: "date-time" },
      attachments: { type: "array", items: { ref: "Attachment" } },
      relations: { type: "array", items: { ref: "MemoRelation" } },
      reactions: { type: "array", items: { ref: "Reaction" } },
    },
  },
  MemoImportPlan: {
    type: "object",
    properties: { exportTime: { type: "string", format: "date-time" } },
  },
  MemoRelation: {
    type: "object",
    required: ["memo", "relatedMemo", "type"],
    properties: {
      memo: { allOf: [{ ref: "MemoRelation_Memo" }] },
      relatedMemo: { allOf: [{ ref: "MemoRelation_Memo" }] },
    },
  },
  MemoRelation_Memo: { type: "object", required: ["name"] },
  MemoShare: {
    type: "object",
    properties: {
      createTime: { type: "string", format: "date-time" },
      expireTime: { type: "string", format: "date-time" },
    },
  },
  MemoView: { type: "object", required: ["title", "filter"] },
  PersonalAccessToken: {
    type: "object",
    properties: {
      createdAt: { type: "string", format: "date-time" },
      expiresAt: { type: "string", format: "date-time" },
      lastUsedAt: { type: "string", format: "date-time" },
    },
  },
  Reaction: {
    type: "object",
    required: ["reactionType"],
    properties: { createTime: { type: "string", format: "date-time" } },
  },
  RefreshTokenResponse: {
    type: "object",
    properties: { expiresAt: { type: "string", format: "date-time" } },
  },
  SetMemoAttachmentsRequest: {
    type: "object",
    required: ["name", "attachments"],
    properties: { attachments: { type: "array", items: { ref: "Attachment" } } },
  },
  SetMemoRelationsRequest: {
    type: "object",
    required: ["name", "relations"],
    properties: { relations: { type: "array", items: { ref: "MemoRelation" } } },
  },
  SignInRequest: {
    type: "object",
    properties: {
      passwordCredentials: { allOf: [{ ref: "SignInRequest_PasswordCredentials" }] },
      ssoCredentials: { allOf: [{ ref: "SignInRequest_SSOCredentials" }] },
    },
  },
  SignInRequest_PasswordCredentials: { type: "object", required: ["username", "password"] },
  SignInRequest_SSOCredentials: { type: "object", required: ["idpName", "code", "redirectUri"] },
  SignInResponse: {
    type: "object",
    properties: {
      user: { allOf: [{ ref: "User" }] },
      accessTokenExpiresAt: { type: "string", format: "date-time" },
    },
  },
  Space: { type: "object", required: ["title"] },
  SpaceInvitation: {
    type: "object",
    required: ["invitee", "role"],
    properties: { space: { allOf: [{ ref: "Space" }] } },
  },
  SpaceMember: { type: "object", required: ["user", "role"] },
  TranscribeRequest: { type: "object", required: ["audio"] },
  UploadAttachmentRequest: {
    type: "object",
    required: ["writeOffset"],
    properties: { spec: { allOf: [{ ref: "UploadAttachmentSpec" }] } },
  },
  UploadAttachmentResponse: {
    type: "object",
    properties: { attachment: { allOf: [{ ref: "Attachment" }] } },
  },
  UploadAttachmentSpec: {
    type: "object",
    required: ["attachment"],
    properties: { attachment: { allOf: [{ ref: "Attachment" }] } },
  },
  UpsertMemoReactionRequest: {
    type: "object",
    required: ["name", "reaction"],
    properties: { reaction: { allOf: [{ ref: "Reaction" }] } },
  },
  User: {
    type: "object",
    required: ["role", "username", "state"],
    properties: {
      createTime: { type: "string", format: "date-time" },
      updateTime: { type: "string", format: "date-time" },
    },
  },
  UserNotification: {
    type: "object",
    properties: {
      senderUser: { allOf: [{ ref: "User" }] },
      createTime: { type: "string", format: "date-time" },
      spaceInvitation: { allOf: [{ ref: "UserNotification_SpaceInvitationPayload" }] },
    },
  },
  UserNotification_SpaceInvitationPayload: {
    type: "object",
    properties: { space: { allOf: [{ ref: "Space" }] } },
  },
  UserSetting: {
    type: "object",
    properties: { webhooksSetting: { ref: "UserSetting_WebhooksSetting" } },
  },
  UserSetting_WebhooksSetting: {
    type: "object",
    properties: { webhooks: { type: "array", items: { ref: "UserWebhook" } } },
  },
  UserStats: {
    type: "object",
    properties: {
      memoCreatedTimestamps: { type: "array", items: { type: "string", format: "date-time" } },
      memoUpdatedTimestamps: { type: "array", items: { type: "string", format: "date-time" } },
    },
  },
  UserWebhook: {
    type: "object",
    properties: {
      createTime: { type: "string", format: "date-time" },
      updateTime: { type: "string", format: "date-time" },
    },
  },
};

const isRecord = (value: unknown): value is RuntimeRecord =>
  value !== null && typeof value === "object" && !Array.isArray(value);

const validationFailure = (field: string, message: string): never => {
  throw new SdkValidationError(field, "required", message);
};

const requiredValue = (field: string): never =>
  validationFailure(field, `Validation failed for '${field}': value is required`);

const childField = (field: string, property: string): string =>
  field ? `${field}.${property}` : property;

const hasType = (schema: RuntimeSchema, type: string): boolean =>
  schema.type === type || (Array.isArray(schema.type) && schema.type.includes(type));

const validateNode = (value: unknown, schema: RuntimeSchema, field: string): unknown => {
  if (value === null) {
    if (schema.nullable === true || hasType(schema, "null")) return value;
    return validationFailure(field, `Validation failed for '${field}': value is not nullable`);
  }

  if (schema.ref) {
    const referenced = modelSchemas[schema.ref];
    return referenced ? validateNode(value, referenced, field) : value;
  }

  if (schema.allOf) {
    for (const member of schema.allOf) validateNode(value, member, field);
  }

  if (schema.oneOf || schema.anyOf) {
    const members = schema.oneOf ?? schema.anyOf ?? [];
    let firstError: unknown;
    for (const member of members) {
      try {
        return validateNode(value, member, field);
      } catch (error) {
        firstError ??= error;
      }
    }
    if (firstError instanceof Error) throw firstError;
  }

  if (hasType(schema, "object") || schema.properties) {
    if (!isRecord(value)) return value;
    for (const property of schema.required ?? []) {
      const propertyValue = value[property];
      if (!Object.prototype.hasOwnProperty.call(value, property) || propertyValue === undefined) {
        requiredValue(childField(field, property));
      }
    }
    for (const [property, propertySchema] of Object.entries(schema.properties ?? {})) {
      if (Object.prototype.hasOwnProperty.call(value, property)) {
        validateNode(value[property], propertySchema, childField(field, property));
      }
    }
    if (schema.additionalProperties) {
      for (const [property, propertyValue] of Object.entries(value)) {
        if (!(property in (schema.properties ?? {}))) {
          validateNode(propertyValue, schema.additionalProperties, childField(field, property));
        }
      }
    }
  }

  if (hasType(schema, "array")) {
    if (!Array.isArray(value)) return value;
    if (schema.items) {
      value.forEach((item, index) =>
        validateNode(item, schema.items as RuntimeSchema, childField(field, String(index))),
      );
    }
  }

  if (schema.format === "date-time") validateDateTime(field, value as string);

  return value;
};

/** Validates a decoded component model and returns the original value. */
export function decodeModel<T>(value: unknown, typeName: string): T {
  const schema = modelSchemas[typeName];
  if (!schema) return value as T;
  return validateNode(value, schema, "") as T;
}
