// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type * as Types from "./types";
import { fromWire, toWire } from "./client";
import { SdkValidationError } from "./errors";

import { validateDateTime } from "./validation";

type RuntimeRecord = Record<string, unknown>;

interface RuntimeSchema {
  ref?: string;
  type?: string | readonly string[];
  nullable?: boolean;
  enum?: readonly unknown[];
  required?: readonly string[];
  properties?: Readonly<Record<string, RuntimeSchema>>;
  items?: RuntimeSchema;
  additionalProperties?: RuntimeSchema;
  oneOf?: readonly RuntimeSchema[];
  anyOf?: readonly RuntimeSchema[];
  allOf?: readonly RuntimeSchema[];
  minimum?: number;
  maximum?: number;
  exclusiveMinimum?: number | boolean;
  exclusiveMaximum?: number | boolean;
  multipleOf?: number;
  minLength?: number;
  maxLength?: number;
  minItems?: number;
  maxItems?: number;
  pattern?: string;
  format?: "email" | "uri" | "uuid" | "date" | "date-time";
}

const modelSchemas: Readonly<Record<string, RuntimeSchema>> = {
  AcceptSpaceInvitationRequest: {
    type: "object",
    required: ["name"],
    properties: { name: { type: "string" } },
  },
  Attachment: {
    type: "object",
    required: ["filename", "type"],
    properties: {
      name: { type: "string" },
      createTime: { type: "string", format: "date-time" },
      filename: { type: "string" },
      content: { type: "string" },
      externalLink: { type: "string" },
      type: { type: "string" },
      size: { type: "string" },
      memo: { type: "string" },
      motionMedia: { allOf: [{ ref: "MotionMedia" }] },
      mediaMetadata: { allOf: [{ ref: "MediaMetadata" }] },
      creator: { type: "string" },
    },
  },
  BatchDeleteAttachmentsRequest: {
    type: "object",
    required: ["names"],
    properties: { names: { type: "array", items: { type: "string" } } },
  },
  BatchGetInstanceSettingsRequest: {
    type: "object",
    required: ["names"],
    properties: { names: { type: "array", items: { type: "string" } } },
  },
  BatchGetLinkMetadataRequest: {
    type: "object",
    required: ["urls"],
    properties: { urls: { type: "array", items: { type: "string" } } },
  },
  BatchGetUsersResponse: {
    type: "object",
    properties: { users: { type: "array", items: { ref: "User" } } },
  },
  CreateLinkedIdentityRequest: {
    type: "object",
    required: ["parent", "idpName", "code", "redirectUri"],
    properties: {
      parent: { type: "string" },
      idpName: { type: "string" },
      code: { type: "string" },
      redirectUri: { type: "string" },
      codeVerifier: { type: "string" },
    },
  },
  CreatePersonalAccessTokenRequest: {
    type: "object",
    required: ["parent"],
    properties: {
      parent: { type: "string" },
      description: { type: "string" },
      expiresInDays: { type: "integer" },
    },
  },
  DeclineSpaceInvitationRequest: {
    type: "object",
    required: ["name"],
    properties: { name: { type: "string" } },
  },
  IdentityProvider: {
    type: "object",
    required: ["type", "title", "config"],
    properties: {
      name: { type: "string" },
      type: { type: "string" },
      title: { type: "string" },
      identifierFilter: { type: "string" },
      config: { allOf: [{ ref: "IdentityProviderConfig" }] },
    },
  },
  ImportMemosRequest: {
    type: "object",
    required: ["name", "writeOffset"],
    properties: {
      name: { type: "string" },
      spec: { allOf: [{ ref: "ImportMemosSpec" }] },
      uploadId: { type: "string" },
      writeOffset: { type: "string" },
      data: { type: "string" },
      finishWrite: { type: "boolean" },
      validateOnly: { type: "boolean" },
      conflictPolicy: { type: "string" },
    },
  },
  InstanceStats: {
    type: "object",
    properties: {
      database: { ref: "InstanceStats_DatabaseStats" },
      localStorageBytes: { type: "string" },
      generatedTime: { type: "string", format: "date-time" },
    },
  },
  ListAllUserStatsResponse: {
    type: "object",
    properties: { stats: { type: "array", items: { ref: "UserStats" } } },
  },
  ListAttachmentsResponse: {
    type: "object",
    properties: {
      attachments: { type: "array", items: { ref: "Attachment" } },
      nextPageToken: { type: "string" },
    },
  },
  ListIdentityProvidersResponse: {
    type: "object",
    properties: { identityProviders: { type: "array", items: { ref: "IdentityProvider" } } },
  },
  ListMemoAttachmentsResponse: {
    type: "object",
    properties: {
      attachments: { type: "array", items: { ref: "Attachment" } },
      nextPageToken: { type: "string" },
    },
  },
  ListMemoCommentsResponse: {
    type: "object",
    properties: {
      memos: { type: "array", items: { ref: "Memo" } },
      nextPageToken: { type: "string" },
    },
  },
  ListMemoReactionsResponse: {
    type: "object",
    properties: {
      reactions: { type: "array", items: { ref: "Reaction" } },
      nextPageToken: { type: "string" },
    },
  },
  ListMemoRelationsResponse: {
    type: "object",
    properties: {
      relations: { type: "array", items: { ref: "MemoRelation" } },
      nextPageToken: { type: "string" },
    },
  },
  ListMemoSharesResponse: {
    type: "object",
    properties: { memoShares: { type: "array", items: { ref: "MemoShare" } } },
  },
  ListMemoViewsResponse: {
    type: "object",
    properties: { memoViews: { type: "array", items: { ref: "MemoView" } } },
  },
  ListMemosResponse: {
    type: "object",
    properties: {
      memos: { type: "array", items: { ref: "Memo" } },
      nextPageToken: { type: "string" },
    },
  },
  ListPersonalAccessTokensResponse: {
    type: "object",
    properties: {
      personalAccessTokens: { type: "array", items: { ref: "PersonalAccessToken" } },
      nextPageToken: { type: "string" },
    },
  },
  ListSpaceInvitationsResponse: {
    type: "object",
    properties: {
      spaceInvitations: { type: "array", items: { ref: "SpaceInvitation" } },
      nextPageToken: { type: "string" },
    },
  },
  ListSpaceMembersResponse: {
    type: "object",
    properties: {
      spaceMembers: { type: "array", items: { ref: "SpaceMember" } },
      nextPageToken: { type: "string" },
    },
  },
  ListSpacesResponse: {
    type: "object",
    properties: {
      spaces: { type: "array", items: { ref: "Space" } },
      nextPageToken: { type: "string" },
    },
  },
  ListUserNotificationsResponse: {
    type: "object",
    properties: {
      notifications: { type: "array", items: { ref: "UserNotification" } },
      nextPageToken: { type: "string" },
    },
  },
  ListUserSettingsResponse: {
    type: "object",
    properties: {
      settings: { type: "array", items: { ref: "UserSetting" } },
      nextPageToken: { type: "string" },
    },
  },
  ListUserSpaceInvitationsResponse: {
    type: "object",
    properties: {
      spaceInvitations: { type: "array", items: { ref: "SpaceInvitation" } },
      nextPageToken: { type: "string" },
    },
  },
  ListUserWebhooksResponse: {
    type: "object",
    properties: { webhooks: { type: "array", items: { ref: "UserWebhook" } } },
  },
  ListUsersResponse: {
    type: "object",
    properties: {
      users: { type: "array", items: { ref: "User" } },
      nextPageToken: { type: "string" },
    },
  },
  Memo: {
    type: "object",
    required: ["state", "content", "visibility"],
    properties: {
      name: { type: "string" },
      state: { type: "string" },
      creator: { type: "string" },
      createTime: { type: "string", format: "date-time" },
      updateTime: { type: "string", format: "date-time" },
      content: { type: "string" },
      visibility: { type: "string" },
      tags: { type: "array", items: { type: "string" } },
      pinned: { type: "boolean" },
      attachments: { type: "array", items: { ref: "Attachment" } },
      relations: { type: "array", items: { ref: "MemoRelation" } },
      reactions: { type: "array", items: { ref: "Reaction" } },
      property: { allOf: [{ ref: "Memo_Property" }] },
      parent: { type: "string" },
      snippet: { type: "string" },
      location: { allOf: [{ ref: "Location" }] },
      space: { type: "string" },
    },
  },
  MemoImportPlan: {
    type: "object",
    properties: {
      exportTime: { type: "string", format: "date-time" },
      exporter: { type: "string" },
      generator: { type: "string" },
      memos: { type: "integer" },
      attachments: { type: "integer" },
      new: { type: "integer" },
      existing: { type: "integer" },
      renamed: { type: "integer" },
      warnings: { type: "array", items: { ref: "MemoImportIssue" } },
    },
  },
  MemoRelation: {
    type: "object",
    required: ["memo", "relatedMemo", "type"],
    properties: {
      memo: { allOf: [{ ref: "MemoRelation_Memo" }] },
      relatedMemo: { allOf: [{ ref: "MemoRelation_Memo" }] },
      type: { type: "string" },
    },
  },
  MemoRelation_Memo: {
    type: "object",
    required: ["name"],
    properties: { name: { type: "string" }, snippet: { type: "string" } },
  },
  MemoShare: {
    type: "object",
    properties: {
      name: { type: "string" },
      createTime: { type: "string", format: "date-time" },
      expireTime: { type: "string", format: "date-time" },
    },
  },
  MemoView: {
    type: "object",
    required: ["title", "filter"],
    properties: {
      name: { type: "string" },
      title: { type: "string" },
      filter: { type: "string" },
      icon: { allOf: [{ ref: "MemoView_Icon" }] },
    },
  },
  PersonalAccessToken: {
    type: "object",
    properties: {
      name: { type: "string" },
      description: { type: "string" },
      createdAt: { type: "string", format: "date-time" },
      expiresAt: { type: "string", format: "date-time" },
      lastUsedAt: { type: "string", format: "date-time" },
    },
  },
  Reaction: {
    type: "object",
    required: ["reactionType"],
    properties: {
      name: { type: "string" },
      creator: { type: "string" },
      reactionType: { type: "string" },
      createTime: { type: "string", format: "date-time" },
    },
  },
  RefreshTokenResponse: {
    type: "object",
    properties: {
      accessToken: { type: "string" },
      expiresAt: { type: "string", format: "date-time" },
    },
  },
  SetMemoAttachmentsRequest: {
    type: "object",
    required: ["name", "attachments"],
    properties: {
      name: { type: "string" },
      attachments: { type: "array", items: { ref: "Attachment" } },
    },
  },
  SetMemoRelationsRequest: {
    type: "object",
    required: ["name", "relations"],
    properties: {
      name: { type: "string" },
      relations: { type: "array", items: { ref: "MemoRelation" } },
    },
  },
  SignInRequest_PasswordCredentials: {
    type: "object",
    required: ["username", "password"],
    properties: { username: { type: "string" }, password: { type: "string" } },
  },
  SignInRequest_SSOCredentials: {
    type: "object",
    required: ["idpName", "code", "redirectUri"],
    properties: {
      idpName: { type: "string" },
      code: { type: "string" },
      redirectUri: { type: "string" },
      codeVerifier: { type: "string" },
    },
  },
  SignInResponse: {
    type: "object",
    properties: {
      user: { allOf: [{ ref: "User" }] },
      accessToken: { type: "string" },
      accessTokenExpiresAt: { type: "string", format: "date-time" },
    },
  },
  Space: {
    type: "object",
    required: ["title"],
    properties: {
      name: { type: "string" },
      title: { type: "string" },
      description: { type: "string" },
      currentUserRole: { type: "string" },
      memberCount: { type: "integer" },
      icon: { allOf: [{ ref: "Space_Icon" }] },
    },
  },
  SpaceInvitation: {
    type: "object",
    required: ["invitee", "role"],
    properties: {
      name: { type: "string" },
      invitee: { type: "string" },
      role: { type: "string" },
      space: { allOf: [{ ref: "Space" }] },
    },
  },
  SpaceMember: {
    type: "object",
    required: ["user", "role"],
    properties: { name: { type: "string" }, user: { type: "string" }, role: { type: "string" } },
  },
  TranscribeRequest: {
    type: "object",
    required: ["audio"],
    properties: { audio: { allOf: [{ ref: "TranscriptionAudio" }] } },
  },
  UploadAttachmentRequest: {
    type: "object",
    required: ["writeOffset"],
    properties: {
      spec: { allOf: [{ ref: "UploadAttachmentSpec" }] },
      uploadId: { type: "string" },
      writeOffset: { type: "string" },
      data: { type: "string" },
      finishWrite: { type: "boolean" },
    },
  },
  UploadAttachmentSpec: {
    type: "object",
    required: ["attachment"],
    properties: {
      attachment: { allOf: [{ ref: "Attachment" }] },
      attachmentId: { type: "string" },
      totalSize: { type: "string" },
    },
  },
  UpsertMemoReactionRequest: {
    type: "object",
    required: ["name", "reaction"],
    properties: { name: { type: "string" }, reaction: { allOf: [{ ref: "Reaction" }] } },
  },
  User: {
    type: "object",
    required: ["role", "username", "state"],
    properties: {
      name: { type: "string" },
      role: { type: "string" },
      username: { type: "string" },
      email: { type: "string" },
      displayName: { type: "string" },
      avatarUrl: { type: "string" },
      description: { type: "string" },
      password: { type: "string" },
      state: { type: "string" },
      createTime: { type: "string", format: "date-time" },
      updateTime: { type: "string", format: "date-time" },
    },
  },
  UserNotification: {
    type: "object",
    properties: {
      name: { type: "string" },
      sender: { type: "string" },
      senderUser: { allOf: [{ ref: "User" }] },
      status: { type: "string" },
      createTime: { type: "string", format: "date-time" },
      type: { type: "string" },
      memoComment: { allOf: [{ ref: "UserNotification_MemoCommentPayload" }] },
      memoMention: { allOf: [{ ref: "UserNotification_MemoMentionPayload" }] },
      spaceInvitation: { allOf: [{ ref: "UserNotification_SpaceInvitationPayload" }] },
    },
  },
  UserSetting: {
    type: "object",
    properties: {
      name: { type: "string" },
      generalSetting: { ref: "UserSetting_GeneralSetting" },
      webhooksSetting: { ref: "UserSetting_WebhooksSetting" },
      tagsSetting: { ref: "UserSetting_TagsSetting" },
    },
  },
  UserSetting_WebhooksSetting: {
    type: "object",
    properties: { webhooks: { type: "array", items: { ref: "UserWebhook" } } },
  },
  UserStats: {
    type: "object",
    properties: {
      name: { type: "string" },
      memoTypeStats: { allOf: [{ ref: "UserStats_MemoTypeStats" }] },
      tagCount: { type: "object", additionalProperties: { type: "integer" } },
      memoCreatedTimestamps: { type: "array", items: { type: "string", format: "date-time" } },
      memoUpdatedTimestamps: { type: "array", items: { type: "string", format: "date-time" } },
      pinnedMemos: { type: "array", items: { type: "string" } },
      totalMemoCount: { type: "integer" },
      attachmentStorageBytes: { type: "string" },
    },
  },
  UserWebhook: {
    type: "object",
    properties: {
      name: { type: "string" },
      url: { type: "string" },
      displayName: { type: "string" },
      createTime: { type: "string", format: "date-time" },
      updateTime: { type: "string", format: "date-time" },
      signingSecret: { type: "string" },
      signingSecretSet: { type: "boolean" },
    },
  },
};

const isRecord = (value: unknown): value is RuntimeRecord =>
  value !== null && typeof value === "object" && !Array.isArray(value);

const childField = (field: string, property: string): string =>
  field ? `${field}.${property}` : property;

const hasType = (schema: RuntimeSchema, type: string): boolean =>
  schema.type === type || (Array.isArray(schema.type) && schema.type.includes(type));

const allowsNull = (schema: RuntimeSchema | undefined, seen = new Set<string>()): boolean => {
  if (!schema) return false;
  if (schema.nullable === true || hasType(schema, "null")) return true;
  if (!schema.ref || seen.has(schema.ref)) return false;
  seen.add(schema.ref);
  const referenced = modelSchemas[schema.ref];
  return referenced ? allowsNull(referenced, seen) : false;
};

const validationFailure = (field: string, code: "required", message: string): never => {
  throw new SdkValidationError(field, code, message);
};

const validateNode = (value: unknown, schema: RuntimeSchema, field: string): unknown => {
  if (schema.ref) {
    const referenced = modelSchemas[schema.ref];
    return referenced ? validateNode(value, referenced, field) : value;
  }

  if (value === null) {
    if (schema.nullable === true || hasType(schema, "null")) return value;
    return value;
  }

  if (schema.allOf) {
    for (const member of schema.allOf) validateNode(value, member, field);
  }

  if (schema.oneOf || schema.anyOf) {
    const members = schema.oneOf ?? schema.anyOf ?? [];
    let firstError: unknown;
    for (const member of members) {
      try {
        return validateNode(value, member, field);
      } catch (error) {
        firstError ??= error;
      }
    }
    if (firstError instanceof Error) throw firstError;
  }

  if (hasType(schema, "object") || schema.properties) {
    if (!isRecord(value)) return value;
    for (const property of schema.required ?? []) {
      const propertyValue = value[property];
      const propertySchema = schema.properties?.[property];
      const missing =
        !Object.prototype.hasOwnProperty.call(value, property) || propertyValue === undefined;
      const invalidNull = propertyValue === null && !allowsNull(propertySchema);
      if (missing || invalidNull) {
        validationFailure(
          childField(field, property),
          "required",
          `Validation failed for '${childField(field, property)}': value is required`,
        );
      }
    }
    for (const [property, propertySchema] of Object.entries(schema.properties ?? {})) {
      if (Object.prototype.hasOwnProperty.call(value, property)) {
        validateNode(value[property], propertySchema, childField(field, property));
      }
    }
    if (schema.additionalProperties) {
      for (const [property, propertyValue] of Object.entries(value)) {
        if (!(property in (schema.properties ?? {}))) {
          validateNode(propertyValue, schema.additionalProperties, childField(field, property));
        }
      }
    }
  }

  if (hasType(schema, "array")) {
    if (!Array.isArray(value)) return value;
    if (schema.items) {
      value.forEach((item, index) =>
        validateNode(item, schema.items as RuntimeSchema, childField(field, String(index))),
      );
    }
  }

  if (schema.format === "date-time") validateDateTime(field, value as string);

  return value;
};

const validateModel = <T>(value: T, typeName: string): T => {
  const schema = modelSchemas[typeName];
  return schema ? (validateNode(value, schema, "") as T) : value;
};

export const modelConstructionStyle = "typed-record" as const;

/** Constructs a validated AcceptSpaceInvitationRequest model value. */
export function createAcceptSpaceInvitationRequest(
  value: Types.AcceptSpaceInvitationRequest,
): Types.AcceptSpaceInvitationRequest {
  return validateModel({ ...value }, "AcceptSpaceInvitationRequest");
}

/** Constructs a validated Attachment model value. */
export function createAttachment(value: Types.Attachment): Types.Attachment {
  return validateModel({ ...value }, "Attachment");
}

/** Constructs a validated BatchDeleteAttachmentsRequest model value. */
export function createBatchDeleteAttachmentsRequest(
  value: Types.BatchDeleteAttachmentsRequest,
): Types.BatchDeleteAttachmentsRequest {
  return validateModel({ ...value }, "BatchDeleteAttachmentsRequest");
}

/** Constructs a validated BatchGetInstanceSettingsRequest model value. */
export function createBatchGetInstanceSettingsRequest(
  value: Types.BatchGetInstanceSettingsRequest,
): Types.BatchGetInstanceSettingsRequest {
  return validateModel({ ...value }, "BatchGetInstanceSettingsRequest");
}

/** Constructs a validated BatchGetInstanceSettingsResponse model value. */
export function createBatchGetInstanceSettingsResponse(
  value: Types.BatchGetInstanceSettingsResponse,
): Types.BatchGetInstanceSettingsResponse {
  return validateModel({ ...value }, "BatchGetInstanceSettingsResponse");
}

/** Constructs a validated BatchGetLinkMetadataRequest model value. */
export function createBatchGetLinkMetadataRequest(
  value: Types.BatchGetLinkMetadataRequest,
): Types.BatchGetLinkMetadataRequest {
  return validateModel({ ...value }, "BatchGetLinkMetadataRequest");
}

/** Constructs a validated BatchGetLinkMetadataResponse model value. */
export function createBatchGetLinkMetadataResponse(
  value: Types.BatchGetLinkMetadataResponse,
): Types.BatchGetLinkMetadataResponse {
  return validateModel({ ...value }, "BatchGetLinkMetadataResponse");
}

/** Constructs a validated BatchGetUsersRequest model value. */
export function createBatchGetUsersRequest(
  value: Types.BatchGetUsersRequest,
): Types.BatchGetUsersRequest {
  return validateModel({ ...value }, "BatchGetUsersRequest");
}

/** Constructs a validated BatchGetUsersResponse model value. */
export function createBatchGetUsersResponse(
  value: Types.BatchGetUsersResponse,
): Types.BatchGetUsersResponse {
  return validateModel({ ...value }, "BatchGetUsersResponse");
}

/** Constructs a validated Color model value. */
export function createColor(value: Types.Color): Types.Color {
  return validateModel({ ...value }, "Color");
}

/** Constructs a validated CreateLinkedIdentityRequest model value. */
export function createCreateLinkedIdentityRequest(
  value: Types.CreateLinkedIdentityRequest,
): Types.CreateLinkedIdentityRequest {
  return validateModel({ ...value }, "CreateLinkedIdentityRequest");
}

/** Constructs a validated CreatePersonalAccessTokenRequest model value. */
export function createCreatePersonalAccessTokenRequest(
  value: Types.CreatePersonalAccessTokenRequest,
): Types.CreatePersonalAccessTokenRequest {
  return validateModel({ ...value }, "CreatePersonalAccessTokenRequest");
}

/** Constructs a validated CreatePersonalAccessTokenResponse model value. */
export function createCreatePersonalAccessTokenResponse(
  value: Types.CreatePersonalAccessTokenResponse,
): Types.CreatePersonalAccessTokenResponse {
  return validateModel({ ...value }, "CreatePersonalAccessTokenResponse");
}

/** Constructs a validated DeclineSpaceInvitationRequest model value. */
export function createDeclineSpaceInvitationRequest(
  value: Types.DeclineSpaceInvitationRequest,
): Types.DeclineSpaceInvitationRequest {
  return validateModel({ ...value }, "DeclineSpaceInvitationRequest");
}

/** Constructs a validated FieldMapping model value. */
export function createFieldMapping(value: Types.FieldMapping): Types.FieldMapping {
  return validateModel({ ...value }, "FieldMapping");
}

/** Constructs a validated GeneralSetting_CustomProfile model value. */
export function createGeneralSetting_CustomProfile(
  value: Types.GeneralSetting_CustomProfile,
): Types.GeneralSetting_CustomProfile {
  return validateModel({ ...value }, "GeneralSetting_CustomProfile");
}

/** Constructs a validated GetCurrentUserResponse model value. */
export function createGetCurrentUserResponse(
  value: Types.GetCurrentUserResponse,
): Types.GetCurrentUserResponse {
  return validateModel({ ...value }, "GetCurrentUserResponse");
}

/** Constructs a validated GetUserWebhookSigningSecretResponse model value. */
export function createGetUserWebhookSigningSecretResponse(
  value: Types.GetUserWebhookSigningSecretResponse,
): Types.GetUserWebhookSigningSecretResponse {
  return validateModel({ ...value }, "GetUserWebhookSigningSecretResponse");
}

/** Constructs a validated GoogleProtobufAny model value. */
export function createGoogleProtobufAny(value: Types.GoogleProtobufAny): Types.GoogleProtobufAny {
  return validateModel({ ...value }, "GoogleProtobufAny");
}

/** Constructs a validated IdentityProvider model value. */
export function createIdentityProvider(value: Types.IdentityProvider): Types.IdentityProvider {
  return validateModel({ ...value }, "IdentityProvider");
}

/** Constructs a validated IdentityProviderConfig model value. */
export function createIdentityProviderConfig(
  value: Types.IdentityProviderConfig,
): Types.IdentityProviderConfig {
  return validateModel({ ...value }, "IdentityProviderConfig");
}

/** Constructs a validated ImportMemosRequest model value. */
export function createImportMemosRequest(
  value: Types.ImportMemosRequest,
): Types.ImportMemosRequest {
  return validateModel({ ...value }, "ImportMemosRequest");
}

/** Constructs a validated ImportMemosResponse model value. */
export function createImportMemosResponse(
  value: Types.ImportMemosResponse,
): Types.ImportMemosResponse {
  return validateModel({ ...value }, "ImportMemosResponse");
}

/** Constructs a validated ImportMemosSpec model value. */
export function createImportMemosSpec(value: Types.ImportMemosSpec): Types.ImportMemosSpec {
  return validateModel({ ...value }, "ImportMemosSpec");
}

/** Constructs a validated InstanceProfile model value. */
export function createInstanceProfile(value: Types.InstanceProfile): Types.InstanceProfile {
  return validateModel({ ...value }, "InstanceProfile");
}

/** Constructs a validated InstanceProfile_Challenge model value. */
export function createInstanceProfile_Challenge(
  value: Types.InstanceProfile_Challenge,
): Types.InstanceProfile_Challenge {
  return validateModel({ ...value }, "InstanceProfile_Challenge");
}

/** Constructs a validated InstanceSetting model value. */
export function createInstanceSetting(value: Types.InstanceSetting): Types.InstanceSetting {
  return validateModel({ ...value }, "InstanceSetting");
}

/** Constructs a validated InstanceSetting_AIProviderConfig model value. */
export function createInstanceSetting_AIProviderConfig(
  value: Types.InstanceSetting_AIProviderConfig,
): Types.InstanceSetting_AIProviderConfig {
  return validateModel({ ...value }, "InstanceSetting_AIProviderConfig");
}

/** Constructs a validated InstanceSetting_AISetting model value. */
export function createInstanceSetting_AISetting(
  value: Types.InstanceSetting_AISetting,
): Types.InstanceSetting_AISetting {
  return validateModel({ ...value }, "InstanceSetting_AISetting");
}

/** Constructs a validated InstanceSetting_AccessSetting model value. */
export function createInstanceSetting_AccessSetting(
  value: Types.InstanceSetting_AccessSetting,
): Types.InstanceSetting_AccessSetting {
  return validateModel({ ...value }, "InstanceSetting_AccessSetting");
}

/** Constructs a validated InstanceSetting_GeneralSetting model value. */
export function createInstanceSetting_GeneralSetting(
  value: Types.InstanceSetting_GeneralSetting,
): Types.InstanceSetting_GeneralSetting {
  return validateModel({ ...value }, "InstanceSetting_GeneralSetting");
}

/** Constructs a validated InstanceSetting_MemoRelatedSetting model value. */
export function createInstanceSetting_MemoRelatedSetting(
  value: Types.InstanceSetting_MemoRelatedSetting,
): Types.InstanceSetting_MemoRelatedSetting {
  return validateModel({ ...value }, "InstanceSetting_MemoRelatedSetting");
}

/** Constructs a validated InstanceSetting_NotificationSetting model value. */
export function createInstanceSetting_NotificationSetting(
  value: Types.InstanceSetting_NotificationSetting,
): Types.InstanceSetting_NotificationSetting {
  return validateModel({ ...value }, "InstanceSetting_NotificationSetting");
}

/** Constructs a validated InstanceSetting_Storage model value. */
export function createInstanceSetting_Storage(
  value: Types.InstanceSetting_Storage,
): Types.InstanceSetting_Storage {
  return validateModel({ ...value }, "InstanceSetting_Storage");
}

/** Constructs a validated InstanceSetting_StorageSetting model value. */
export function createInstanceSetting_StorageSetting(
  value: Types.InstanceSetting_StorageSetting,
): Types.InstanceSetting_StorageSetting {
  return validateModel({ ...value }, "InstanceSetting_StorageSetting");
}

/** Constructs a validated InstanceSetting_TagMetadata model value. */
export function createInstanceSetting_TagMetadata(
  value: Types.InstanceSetting_TagMetadata,
): Types.InstanceSetting_TagMetadata {
  return validateModel({ ...value }, "InstanceSetting_TagMetadata");
}

/** Constructs a validated InstanceSetting_TagsSetting model value. */
export function createInstanceSetting_TagsSetting(
  value: Types.InstanceSetting_TagsSetting,
): Types.InstanceSetting_TagsSetting {
  return validateModel({ ...value }, "InstanceSetting_TagsSetting");
}

/** Constructs a validated InstanceSetting_TranscriptionConfig model value. */
export function createInstanceSetting_TranscriptionConfig(
  value: Types.InstanceSetting_TranscriptionConfig,
): Types.InstanceSetting_TranscriptionConfig {
  return validateModel({ ...value }, "InstanceSetting_TranscriptionConfig");
}

/** Constructs a validated InstanceStats model value. */
export function createInstanceStats(value: Types.InstanceStats): Types.InstanceStats {
  return validateModel({ ...value }, "InstanceStats");
}

/** Constructs a validated InstanceStats_DatabaseStats model value. */
export function createInstanceStats_DatabaseStats(
  value: Types.InstanceStats_DatabaseStats,
): Types.InstanceStats_DatabaseStats {
  return validateModel({ ...value }, "InstanceStats_DatabaseStats");
}

/** Constructs a validated LinkMetadata model value. */
export function createLinkMetadata(value: Types.LinkMetadata): Types.LinkMetadata {
  return validateModel({ ...value }, "LinkMetadata");
}

/** Constructs a validated LinkedIdentity model value. */
export function createLinkedIdentity(value: Types.LinkedIdentity): Types.LinkedIdentity {
  return validateModel({ ...value }, "LinkedIdentity");
}

/** Constructs a validated ListAllUserStatsResponse model value. */
export function createListAllUserStatsResponse(
  value: Types.ListAllUserStatsResponse,
): Types.ListAllUserStatsResponse {
  return validateModel({ ...value }, "ListAllUserStatsResponse");
}

/** Constructs a validated ListAttachmentsResponse model value. */
export function createListAttachmentsResponse(
  value: Types.ListAttachmentsResponse,
): Types.ListAttachmentsResponse {
  return validateModel({ ...value }, "ListAttachmentsResponse");
}

/** Constructs a validated ListIdentityProvidersResponse model value. */
export function createListIdentityProvidersResponse(
  value: Types.ListIdentityProvidersResponse,
): Types.ListIdentityProvidersResponse {
  return validateModel({ ...value }, "ListIdentityProvidersResponse");
}

/** Constructs a validated ListLinkedIdentitiesResponse model value. */
export function createListLinkedIdentitiesResponse(
  value: Types.ListLinkedIdentitiesResponse,
): Types.ListLinkedIdentitiesResponse {
  return validateModel({ ...value }, "ListLinkedIdentitiesResponse");
}

/** Constructs a validated ListMemoAttachmentsResponse model value. */
export function createListMemoAttachmentsResponse(
  value: Types.ListMemoAttachmentsResponse,
): Types.ListMemoAttachmentsResponse {
  return validateModel({ ...value }, "ListMemoAttachmentsResponse");
}

/** Constructs a validated ListMemoCommentsResponse model value. */
export function createListMemoCommentsResponse(
  value: Types.ListMemoCommentsResponse,
): Types.ListMemoCommentsResponse {
  return validateModel({ ...value }, "ListMemoCommentsResponse");
}

/** Constructs a validated ListMemoReactionsResponse model value. */
export function createListMemoReactionsResponse(
  value: Types.ListMemoReactionsResponse,
): Types.ListMemoReactionsResponse {
  return validateModel({ ...value }, "ListMemoReactionsResponse");
}

/** Constructs a validated ListMemoRelationsResponse model value. */
export function createListMemoRelationsResponse(
  value: Types.ListMemoRelationsResponse,
): Types.ListMemoRelationsResponse {
  return validateModel({ ...value }, "ListMemoRelationsResponse");
}

/** Constructs a validated ListMemoSharesResponse model value. */
export function createListMemoSharesResponse(
  value: Types.ListMemoSharesResponse,
): Types.ListMemoSharesResponse {
  return validateModel({ ...value }, "ListMemoSharesResponse");
}

/** Constructs a validated ListMemoViewsResponse model value. */
export function createListMemoViewsResponse(
  value: Types.ListMemoViewsResponse,
): Types.ListMemoViewsResponse {
  return validateModel({ ...value }, "ListMemoViewsResponse");
}

/** Constructs a validated ListMemosResponse model value. */
export function createListMemosResponse(value: Types.ListMemosResponse): Types.ListMemosResponse {
  return validateModel({ ...value }, "ListMemosResponse");
}

/** Constructs a validated ListPersonalAccessTokensResponse model value. */
export function createListPersonalAccessTokensResponse(
  value: Types.ListPersonalAccessTokensResponse,
): Types.ListPersonalAccessTokensResponse {
  return validateModel({ ...value }, "ListPersonalAccessTokensResponse");
}

/** Constructs a validated ListSpaceInvitationsResponse model value. */
export function createListSpaceInvitationsResponse(
  value: Types.ListSpaceInvitationsResponse,
): Types.ListSpaceInvitationsResponse {
  return validateModel({ ...value }, "ListSpaceInvitationsResponse");
}

/** Constructs a validated ListSpaceMembersResponse model value. */
export function createListSpaceMembersResponse(
  value: Types.ListSpaceMembersResponse,
): Types.ListSpaceMembersResponse {
  return validateModel({ ...value }, "ListSpaceMembersResponse");
}

/** Constructs a validated ListSpacesResponse model value. */
export function createListSpacesResponse(
  value: Types.ListSpacesResponse,
): Types.ListSpacesResponse {
  return validateModel({ ...value }, "ListSpacesResponse");
}

/** Constructs a validated ListUserNotificationsResponse model value. */
export function createListUserNotificationsResponse(
  value: Types.ListUserNotificationsResponse,
): Types.ListUserNotificationsResponse {
  return validateModel({ ...value }, "ListUserNotificationsResponse");
}

/** Constructs a validated ListUserSettingsResponse model value. */
export function createListUserSettingsResponse(
  value: Types.ListUserSettingsResponse,
): Types.ListUserSettingsResponse {
  return validateModel({ ...value }, "ListUserSettingsResponse");
}

/** Constructs a validated ListUserSpaceInvitationsResponse model value. */
export function createListUserSpaceInvitationsResponse(
  value: Types.ListUserSpaceInvitationsResponse,
): Types.ListUserSpaceInvitationsResponse {
  return validateModel({ ...value }, "ListUserSpaceInvitationsResponse");
}

/** Constructs a validated ListUserWebhooksResponse model value. */
export function createListUserWebhooksResponse(
  value: Types.ListUserWebhooksResponse,
): Types.ListUserWebhooksResponse {
  return validateModel({ ...value }, "ListUserWebhooksResponse");
}

/** Constructs a validated ListUsersResponse model value. */
export function createListUsersResponse(value: Types.ListUsersResponse): Types.ListUsersResponse {
  return validateModel({ ...value }, "ListUsersResponse");
}

/** Constructs a validated Location model value. */
export function createLocation(value: Types.Location): Types.Location {
  return validateModel({ ...value }, "Location");
}

/** Constructs a validated MediaCaptureTime model value. */
export function createMediaCaptureTime(value: Types.MediaCaptureTime): Types.MediaCaptureTime {
  return validateModel({ ...value }, "MediaCaptureTime");
}

/** Constructs a validated MediaLocation model value. */
export function createMediaLocation(value: Types.MediaLocation): Types.MediaLocation {
  return validateModel({ ...value }, "MediaLocation");
}

/** Constructs a validated MediaMetadata model value. */
export function createMediaMetadata(value: Types.MediaMetadata): Types.MediaMetadata {
  return validateModel({ ...value }, "MediaMetadata");
}

/** Constructs a validated Memo model value. */
export function createMemo(value: Types.Memo): Types.Memo {
  return validateModel({ ...value }, "Memo");
}

/** Constructs a validated MemoImportIssue model value. */
export function createMemoImportIssue(value: Types.MemoImportIssue): Types.MemoImportIssue {
  return validateModel({ ...value }, "MemoImportIssue");
}

/** Constructs a validated MemoImportPlan model value. */
export function createMemoImportPlan(value: Types.MemoImportPlan): Types.MemoImportPlan {
  return validateModel({ ...value }, "MemoImportPlan");
}

/** Constructs a validated MemoImportReport model value. */
export function createMemoImportReport(value: Types.MemoImportReport): Types.MemoImportReport {
  return validateModel({ ...value }, "MemoImportReport");
}

/** Constructs a validated MemoRelation model value. */
export function createMemoRelation(value: Types.MemoRelation): Types.MemoRelation {
  return validateModel({ ...value }, "MemoRelation");
}

/** Constructs a validated MemoRelation_Memo model value. */
export function createMemoRelation_Memo(value: Types.MemoRelation_Memo): Types.MemoRelation_Memo {
  return validateModel({ ...value }, "MemoRelation_Memo");
}

/** Constructs a validated MemoShare model value. */
export function createMemoShare(value: Types.MemoShare): Types.MemoShare {
  return validateModel({ ...value }, "MemoShare");
}

/** Constructs a validated MemoView model value. */
export function createMemoView(value: Types.MemoView): Types.MemoView {
  return validateModel({ ...value }, "MemoView");
}

/** Constructs a validated MemoView_Icon model value. */
export function createMemoView_Icon(value: Types.MemoView_Icon): Types.MemoView_Icon {
  return validateModel({ ...value }, "MemoView_Icon");
}

/** Constructs a validated Memo_Property model value. */
export function createMemo_Property(value: Types.Memo_Property): Types.Memo_Property {
  return validateModel({ ...value }, "Memo_Property");
}

/** Constructs a validated MotionMedia model value. */
export function createMotionMedia(value: Types.MotionMedia): Types.MotionMedia {
  return validateModel({ ...value }, "MotionMedia");
}

/** Constructs a validated NotificationSetting_EmailSetting model value. */
export function createNotificationSetting_EmailSetting(
  value: Types.NotificationSetting_EmailSetting,
): Types.NotificationSetting_EmailSetting {
  return validateModel({ ...value }, "NotificationSetting_EmailSetting");
}

/** Constructs a validated OAuth2Config model value. */
export function createOAuth2Config(value: Types.OAuth2Config): Types.OAuth2Config {
  return validateModel({ ...value }, "OAuth2Config");
}

/** Constructs a validated PersonalAccessToken model value. */
export function createPersonalAccessToken(
  value: Types.PersonalAccessToken,
): Types.PersonalAccessToken {
  return validateModel({ ...value }, "PersonalAccessToken");
}

/** Constructs a validated PhotoMetadata model value. */
export function createPhotoMetadata(value: Types.PhotoMetadata): Types.PhotoMetadata {
  return validateModel({ ...value }, "PhotoMetadata");
}

/** Constructs a validated Reaction model value. */
export function createReaction(value: Types.Reaction): Types.Reaction {
  return validateModel({ ...value }, "Reaction");
}

/** Constructs a validated RefreshTokenRequest model value. */
export function createRefreshTokenRequest(
  value: Types.RefreshTokenRequest,
): Types.RefreshTokenRequest {
  return validateModel({ ...value }, "RefreshTokenRequest");
}

/** Constructs a validated RefreshTokenResponse model value. */
export function createRefreshTokenResponse(
  value: Types.RefreshTokenResponse,
): Types.RefreshTokenResponse {
  return validateModel({ ...value }, "RefreshTokenResponse");
}

/** Constructs a validated SetMemoAttachmentsRequest model value. */
export function createSetMemoAttachmentsRequest(
  value: Types.SetMemoAttachmentsRequest,
): Types.SetMemoAttachmentsRequest {
  return validateModel({ ...value }, "SetMemoAttachmentsRequest");
}

/** Constructs a validated SetMemoRelationsRequest model value. */
export function createSetMemoRelationsRequest(
  value: Types.SetMemoRelationsRequest,
): Types.SetMemoRelationsRequest {
  return validateModel({ ...value }, "SetMemoRelationsRequest");
}

/** Constructs a validated SignInRequest model value. */
export function createSignInRequest(value: Types.SignInRequest): Types.SignInRequest {
  return validateModel({ ...value }, "SignInRequest");
}

/** Constructs a validated SignInRequest_PasswordCredentials model value. */
export function createSignInRequest_PasswordCredentials(
  value: Types.SignInRequest_PasswordCredentials,
): Types.SignInRequest_PasswordCredentials {
  return validateModel({ ...value }, "SignInRequest_PasswordCredentials");
}

/** Constructs a validated SignInRequest_SSOCredentials model value. */
export function createSignInRequest_SSOCredentials(
  value: Types.SignInRequest_SSOCredentials,
): Types.SignInRequest_SSOCredentials {
  return validateModel({ ...value }, "SignInRequest_SSOCredentials");
}

/** Constructs a validated SignInResponse model value. */
export function createSignInResponse(value: Types.SignInResponse): Types.SignInResponse {
  return validateModel({ ...value }, "SignInResponse");
}

/** Constructs a validated Space model value. */
export function createSpace(value: Types.Space): Types.Space {
  return validateModel({ ...value }, "Space");
}

/** Constructs a validated SpaceInvitation model value. */
export function createSpaceInvitation(value: Types.SpaceInvitation): Types.SpaceInvitation {
  return validateModel({ ...value }, "SpaceInvitation");
}

/** Constructs a validated SpaceMember model value. */
export function createSpaceMember(value: Types.SpaceMember): Types.SpaceMember {
  return validateModel({ ...value }, "SpaceMember");
}

/** Constructs a validated Space_Icon model value. */
export function createSpace_Icon(value: Types.Space_Icon): Types.Space_Icon {
  return validateModel({ ...value }, "Space_Icon");
}

/** Constructs a validated Status model value. */
export function createStatus(value: Types.Status): Types.Status {
  return validateModel({ ...value }, "Status");
}

/** Constructs a validated StorageSetting_S3Config model value. */
export function createStorageSetting_S3Config(
  value: Types.StorageSetting_S3Config,
): Types.StorageSetting_S3Config {
  return validateModel({ ...value }, "StorageSetting_S3Config");
}

/** Constructs a validated Storage_S3Config model value. */
export function createStorage_S3Config(value: Types.Storage_S3Config): Types.Storage_S3Config {
  return validateModel({ ...value }, "Storage_S3Config");
}

/** Constructs a validated TestInstanceEmailSettingRequest model value. */
export function createTestInstanceEmailSettingRequest(
  value: Types.TestInstanceEmailSettingRequest,
): Types.TestInstanceEmailSettingRequest {
  return validateModel({ ...value }, "TestInstanceEmailSettingRequest");
}

/** Constructs a validated TranscribeRequest model value. */
export function createTranscribeRequest(value: Types.TranscribeRequest): Types.TranscribeRequest {
  return validateModel({ ...value }, "TranscribeRequest");
}

/** Constructs a validated TranscribeResponse model value. */
export function createTranscribeResponse(
  value: Types.TranscribeResponse,
): Types.TranscribeResponse {
  return validateModel({ ...value }, "TranscribeResponse");
}

/** Constructs a validated TranscriptionAudio model value. */
export function createTranscriptionAudio(
  value: Types.TranscriptionAudio,
): Types.TranscriptionAudio {
  return validateModel({ ...value }, "TranscriptionAudio");
}

/** Constructs a validated UploadAttachmentRequest model value. */
export function createUploadAttachmentRequest(
  value: Types.UploadAttachmentRequest,
): Types.UploadAttachmentRequest {
  return validateModel({ ...value }, "UploadAttachmentRequest");
}

/** Constructs a validated UploadAttachmentResponse model value. */
export function createUploadAttachmentResponse(
  value: Types.UploadAttachmentResponse,
): Types.UploadAttachmentResponse {
  return validateModel({ ...value }, "UploadAttachmentResponse");
}

/** Constructs a validated UploadAttachmentSpec model value. */
export function createUploadAttachmentSpec(
  value: Types.UploadAttachmentSpec,
): Types.UploadAttachmentSpec {
  return validateModel({ ...value }, "UploadAttachmentSpec");
}

/** Constructs a validated UpsertMemoReactionRequest model value. */
export function createUpsertMemoReactionRequest(
  value: Types.UpsertMemoReactionRequest,
): Types.UpsertMemoReactionRequest {
  return validateModel({ ...value }, "UpsertMemoReactionRequest");
}

/** Constructs a validated User model value. */
export function createUser(value: Types.User): Types.User {
  return validateModel({ ...value }, "User");
}

/** Constructs a validated UserNotification model value. */
export function createUserNotification(value: Types.UserNotification): Types.UserNotification {
  return validateModel({ ...value }, "UserNotification");
}

/** Constructs a validated UserNotification_MemoCommentPayload model value. */
export function createUserNotification_MemoCommentPayload(
  value: Types.UserNotification_MemoCommentPayload,
): Types.UserNotification_MemoCommentPayload {
  return validateModel({ ...value }, "UserNotification_MemoCommentPayload");
}

/** Constructs a validated UserNotification_MemoMentionPayload model value. */
export function createUserNotification_MemoMentionPayload(
  value: Types.UserNotification_MemoMentionPayload,
): Types.UserNotification_MemoMentionPayload {
  return validateModel({ ...value }, "UserNotification_MemoMentionPayload");
}

/** Constructs a validated UserNotification_SpaceInvitationPayload model value. */
export function createUserNotification_SpaceInvitationPayload(
  value: Types.UserNotification_SpaceInvitationPayload,
): Types.UserNotification_SpaceInvitationPayload {
  return validateModel({ ...value }, "UserNotification_SpaceInvitationPayload");
}

/** Constructs a validated UserSetting model value. */
export function createUserSetting(value: Types.UserSetting): Types.UserSetting {
  return validateModel({ ...value }, "UserSetting");
}

/** Constructs a validated UserSetting_GeneralSetting model value. */
export function createUserSetting_GeneralSetting(
  value: Types.UserSetting_GeneralSetting,
): Types.UserSetting_GeneralSetting {
  return validateModel({ ...value }, "UserSetting_GeneralSetting");
}

/** Constructs a validated UserSetting_TagMetadata model value. */
export function createUserSetting_TagMetadata(
  value: Types.UserSetting_TagMetadata,
): Types.UserSetting_TagMetadata {
  return validateModel({ ...value }, "UserSetting_TagMetadata");
}

/** Constructs a validated UserSetting_TagsSetting model value. */
export function createUserSetting_TagsSetting(
  value: Types.UserSetting_TagsSetting,
): Types.UserSetting_TagsSetting {
  return validateModel({ ...value }, "UserSetting_TagsSetting");
}

/** Constructs a validated UserSetting_WebhooksSetting model value. */
export function createUserSetting_WebhooksSetting(
  value: Types.UserSetting_WebhooksSetting,
): Types.UserSetting_WebhooksSetting {
  return validateModel({ ...value }, "UserSetting_WebhooksSetting");
}

/** Constructs a validated UserStats model value. */
export function createUserStats(value: Types.UserStats): Types.UserStats {
  return validateModel({ ...value }, "UserStats");
}

/** Constructs a validated UserStats_MemoTypeStats model value. */
export function createUserStats_MemoTypeStats(
  value: Types.UserStats_MemoTypeStats,
): Types.UserStats_MemoTypeStats {
  return validateModel({ ...value }, "UserStats_MemoTypeStats");
}

/** Constructs a validated UserWebhook model value. */
export function createUserWebhook(value: Types.UserWebhook): Types.UserWebhook {
  return validateModel({ ...value }, "UserWebhook");
}

/** Constructs a validated VideoMetadata model value. */
export function createVideoMetadata(value: Types.VideoMetadata): Types.VideoMetadata {
  return validateModel({ ...value }, "VideoMetadata");
}

/** Serializes a constructed model using the generated wire-name mapping. */
export function serializeModel<T>(value: T, typeName: string): unknown {
  return toWire(validateModel(value, typeName), typeName);
}

/** Decodes and validates a wire model through the generated public surface. */
export function deserializeModel<T>(value: unknown, typeName: string): T {
  return validateModel<T>(fromWire(value, typeName) as T, typeName);
}
