// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { ClientConfig, LoggingConfig } from "./client";
import { AiServiceNamespace } from "./methods/aiService";
import { AttachmentServiceNamespace } from "./methods/attachmentService";
import { AuthServiceNamespace } from "./methods/authService";
import { IdentityProviderServiceNamespace } from "./methods/identityProviderService";
import { InstanceServiceNamespace } from "./methods/instanceService";
import { MemoServiceNamespace } from "./methods/memoService";
import { SpaceServiceNamespace } from "./methods/spaceService";
import { UserServiceNamespace } from "./methods/userService";

export class Sdk {
  private readonly _config: ClientConfig;
  readonly aiService: AiServiceNamespace;
  readonly attachmentService: AttachmentServiceNamespace;
  readonly authService: AuthServiceNamespace;
  readonly identityProviderService: IdentityProviderServiceNamespace;
  readonly instanceService: InstanceServiceNamespace;
  readonly memoService: MemoServiceNamespace;
  readonly spaceService: SpaceServiceNamespace;
  readonly userService: UserServiceNamespace;

  constructor(config: ClientConfig) {
    this._config = config;
    this.aiService = new AiServiceNamespace(config);
    this.attachmentService = new AttachmentServiceNamespace(config);
    this.authService = new AuthServiceNamespace(config);
    this.identityProviderService = new IdentityProviderServiceNamespace(config);
    this.instanceService = new InstanceServiceNamespace(config);
    this.memoService = new MemoServiceNamespace(config);
    this.spaceService = new SpaceServiceNamespace(config);
    this.userService = new UserServiceNamespace(config);
  }

  /**
   * Turns SDK logging on and configures it. Logging is OFF by default — this
   * SDK reports nothing until you call this (or construct the client with
   * `logging: { enabled: true }`). Reports go to the endpoint this build was
   * generated with, or to the `endpoint` you pass; with neither, nothing is sent.
   * Pass `{ enabled: false }` to turn it off.
   */
  setLoggingConfig(config: LoggingConfig): void {
    this._config.logging = { ...this._config.logging, enabled: true, ...config };
  }
}
