// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { SdkValidationError } from "./errors";

const DATE_TIME_RE =
  /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.\d+)?(Z|[+-](\d{2}):(\d{2}))$/;
const isValidDateTimeCalendar = (match: RegExpExecArray): boolean => {
  const year = Number(match[1]);
  const month = Number(match[2]);
  const day = Number(match[3]);
  const hour = Number(match[4]);
  const minute = Number(match[5]);
  const second = Number(match[6]);
  const offsetHour = match[8] === undefined ? 0 : Number(match[8]);
  const offsetMinute = match[9] === undefined ? 0 : Number(match[9]);
  const leapYear = year % 4 === 0 && (year % 100 !== 0 || year % 400 === 0);
  const daysInMonth = [31, leapYear ? 29 : 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31][month - 1];
  return (
    daysInMonth !== undefined &&
    day >= 1 &&
    day <= daysInMonth &&
    hour <= 23 &&
    minute <= 59 &&
    second <= 59 &&
    offsetHour <= 23 &&
    offsetMinute <= 59
  );
};
export function validateDateTime(field: string, value: string | Date): void {
  const asString =
    value instanceof Date ? (Number.isNaN(value.getTime()) ? "" : value.toISOString()) : value;
  const match = DATE_TIME_RE.exec(asString);
  if (match === null || !isValidDateTimeCalendar(match) || Number.isNaN(Date.parse(asString))) {
    throw new SdkValidationError(
      field,
      "format:date-time",
      `Validation failed for '${field}': must be a valid ISO 8601 date-time`,
    );
  }
}
